<?php

use App\Http\Controllers\TenantAuthController;
use App\Http\Controllers\TenantCalendarController;
use App\Http\Controllers\TenantCrmController;
use App\Http\Controllers\TenantEngagementController;
use App\Http\Controllers\TenantFinanceController;
use App\Http\Controllers\TenantHealthController;
use App\Http\Controllers\TenantIntegrationAuditController;
use App\Http\Controllers\TenantLeadController;
use App\Http\Controllers\TenantPermissionController;
use App\Http\Controllers\TenantRoleController;
use App\Http\Controllers\TenantSettingsController;
use App\Http\Controllers\TenantSharedPrimitiveController;
use App\Http\Controllers\TenantStaffController;
use App\Http\Controllers\TenantHrmsController;
use App\Http\Controllers\TenantDashboardController;
use App\Http\Controllers\TenantTeamController;
use App\Http\Controllers\TenantTodoController;
use App\Http\Controllers\TenantWorkController;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Route;

Route::get('health', TenantHealthController::class);

Route::middleware('tenant.context')->group(function (): void {
    Route::post('forgot-password', [TenantAuthController::class, 'forgotPassword'])->middleware('throttle:api-password-forgot');
    Route::post('reset-password', [TenantAuthController::class, 'resetPassword'])->middleware('throttle:api-password-reset');
});

Route::middleware(['tenant.context', 'auth:sanctum', 'tenant.token', 'throttle:api-authenticated'])->group(function (): void {
    Route::post('logout', [TenantAuthController::class, 'logout']);
    Route::post('refresh', [TenantAuthController::class, 'refresh']);
    Route::get('me', [TenantAuthController::class, 'me']);
    Route::post('verify-email/resend', [TenantAuthController::class, 'resendVerification']);
    Route::post('2fa/enable', [TenantAuthController::class, 'enable2fa']);
    Route::post('2fa/confirm', [TenantAuthController::class, 'confirm2fa']);
    Route::post('2fa/disable', [TenantAuthController::class, 'disable2fa']);
    Route::get('profile', [TenantAuthController::class, 'profile']);
    Route::match(['put', 'patch'], 'profile', [TenantAuthController::class, 'updateProfile']);
    Route::put('profile/password', [TenantAuthController::class, 'changePassword']);
    Route::get('profile/preferences', [TenantAuthController::class, 'preferences']);
    Route::put('profile/preferences', [TenantAuthController::class, 'updatePreferences']);
    Route::get('profile/sessions', [TenantAuthController::class, 'sessions']);
    Route::delete('profile/sessions/{session_id}', [TenantAuthController::class, 'revokeSession'])->whereNumber('session_id');

    Route::get('permissions/grouped', [TenantPermissionController::class, 'grouped'])->middleware('tenant.permission:permission.view');
    Route::get('permissions', [TenantPermissionController::class, 'index'])->middleware('tenant.permission:permission.view');
    Route::get('permissions/{permission_uuid}', [TenantPermissionController::class, 'show'])->middleware('tenant.permission:permission.view');
    
    Route::get('roles', [TenantRoleController::class, 'index'])->middleware('tenant.permission:role.view');
    Route::post('roles', [TenantRoleController::class, 'store'])->middleware('tenant.permission:role.create');
    Route::delete('roles/bulk', [TenantRoleController::class, 'bulkDestroy'])->middleware('tenant.permission:role.delete');
    Route::get('roles/{role_uuid}', [TenantRoleController::class, 'show'])->middleware('tenant.permission:role.view');
    Route::match(['put', 'patch'], 'roles/{role_uuid}', [TenantRoleController::class, 'update'])->middleware('tenant.permission:role.edit');
    Route::delete('roles/{role_uuid}', [TenantRoleController::class, 'destroy'])->middleware('tenant.permission:role.delete');
    Route::post('roles/{role_uuid}/clone', [TenantRoleController::class, 'clone'])->middleware('tenant.permission:role.create');
    Route::post('roles/{role_uuid}/activate', [TenantRoleController::class, 'activate'])->middleware('tenant.permission:role.edit');
    Route::post('roles/{role_uuid}/deactivate', [TenantRoleController::class, 'deactivate'])->middleware('tenant.permission:role.edit');
    Route::get('roles/{role_uuid}/permissions', [TenantRoleController::class, 'permissions'])->middleware('tenant.permission:role.view');
    Route::put('roles/{role_uuid}/permissions', [TenantRoleController::class, 'syncPermissions'])->middleware('tenant.permission:role.assign_permissions');
    Route::get('roles/{role_uuid}/users', [TenantRoleController::class, 'users'])->middleware('tenant.permission:role.view');
    Route::post('roles/{role_uuid}/users', [TenantRoleController::class, 'assignUsers'])->middleware('tenant.permission:role.edit');
    Route::put('roles/{role_uuid}/users', [TenantRoleController::class, 'replaceUsers'])->middleware('tenant.permission:role.edit');
    Route::delete('roles/{role_uuid}/users/{user_uuid}', [TenantRoleController::class, 'removeUser'])->middleware('tenant.permission:role.edit');

    Route::get('team-roles', [TenantTeamController::class, 'teamRoles'])->middleware('tenant.permission:team.view');
    Route::post('team-roles', [TenantTeamController::class, 'storeTeamRole'])->middleware('tenant.permission:team.create');
    Route::match(['put', 'patch'], 'team-roles/{team_role_uuid}', [TenantTeamController::class, 'updateTeamRole'])->middleware('tenant.permission:team.edit');
    Route::delete('team-roles/{team_role_uuid}', [TenantTeamController::class, 'deleteTeamRole'])->middleware('tenant.permission:team.delete');
    
    Route::post('teams/export', [TenantTeamController::class, 'export'])->middleware('tenant.permission:team.view');
    Route::get('teams', [TenantTeamController::class, 'index'])->middleware('tenant.permission:team.view');
    Route::post('teams', [TenantTeamController::class, 'store'])->middleware('tenant.permission:team.create');
    Route::delete('teams/bulk', [TenantTeamController::class, 'bulkDestroy'])->middleware('tenant.permission:team.delete');
    Route::get('teams/{team_uuid}', [TenantTeamController::class, 'show'])->middleware('tenant.permission:team.view');
    Route::match(['put', 'patch'], 'teams/{team_uuid}', [TenantTeamController::class, 'update'])->middleware('tenant.permission:team.edit');
    Route::delete('teams/{team_uuid}', [TenantTeamController::class, 'destroy'])->middleware('tenant.permission:team.delete');
    Route::get('teams/{team_uuid}/permissions', [TenantTeamController::class, 'permissions'])->middleware('tenant.permission:team.view');
    Route::put('teams/{team_uuid}/permissions', [TenantTeamController::class, 'syncPermissions'])->middleware('tenant.permission:team.edit');
    Route::get('teams/{team_uuid}/members', [TenantTeamController::class, 'members'])->middleware('tenant.permission:team.view');
    Route::post('teams/{team_uuid}/members', [TenantTeamController::class, 'addMembers'])->middleware('tenant.permission:team.edit');
    Route::patch('teams/{team_uuid}/members/{member_uuid}', [TenantTeamController::class, 'updateMember'])->middleware('tenant.permission:team.edit');
    Route::delete('teams/{team_uuid}/members/{member_uuid}', [TenantTeamController::class, 'removeMember'])->middleware('tenant.permission:team.edit');
    Route::get('teams/{team_uuid}/settings', [TenantTeamController::class, 'settings'])->middleware('tenant.permission:team.view');
    Route::put('teams/{team_uuid}/settings', [TenantTeamController::class, 'updateSettings'])->middleware('tenant.permission:team.edit');
    Route::get('teams/{team_uuid}/assignments', [TenantTeamController::class, 'assignments'])->middleware('tenant.permission:team.view');
    Route::post('teams/{team_uuid}/assignments', [TenantTeamController::class, 'createAssignment'])->middleware('tenant.permission:team.edit');
    Route::delete('teams/{team_uuid}/assignments/{assignment_id}', [TenantTeamController::class, 'releaseAssignment'])->whereNumber('assignment_id')->middleware('tenant.permission:team.edit');
    Route::get('teams/{team_uuid}/projects', [TenantTeamController::class, 'projects'])->middleware('tenant.permission:team.view');
    Route::get('teams/{team_uuid}/tasks', [TenantTeamController::class, 'tasks'])->middleware('tenant.permission:team.view');
    Route::get('teams/{team_uuid}/activity', [TenantTeamController::class, 'activity'])->middleware('tenant.permission:team.view');

    Route::get('users', [TenantStaffController::class, 'users'])->middleware('tenant.permission:staff.view');
    Route::post('users/invite', [TenantStaffController::class, 'invite'])->middleware('tenant.permission:staff.create');
    Route::get('users/{user_uuid}', [TenantStaffController::class, 'user'])->middleware('tenant.permission:staff.view');
    Route::match(['put', 'patch'], 'users/{user_uuid}', [TenantStaffController::class, 'updateUser'])->middleware('tenant.permission:staff.edit');
    Route::put('users/{user_uuid}/roles', [TenantStaffController::class, 'replaceUserRoles'])->middleware('tenant.permission:role.edit');
    Route::post('users/{user_uuid}/suspend', [TenantStaffController::class, 'suspendUser'])->middleware('tenant.permission:staff.edit');
    Route::post('users/{user_uuid}/activate', [TenantStaffController::class, 'activateUser'])->middleware('tenant.permission:staff.edit');
    Route::post('users/{user_uuid}/reset-password', [TenantStaffController::class, 'resetPassword'])->middleware('tenant.permission:staff.edit');
    Route::post('users/{user_uuid}/force-logout', [TenantStaffController::class, 'forceLogout'])->middleware('tenant.permission:staff.edit');
    Route::post('users/{user_uuid}/require-2fa', [TenantStaffController::class, 'requireTwoFactor'])->middleware('tenant.permission:staff.edit');
    
    Route::get('staff/dashboard', [TenantStaffController::class, 'dashboard'])->middleware('tenant.permission:staff.view');
    Route::get('staff/grid', [TenantStaffController::class, 'grid'])->middleware('tenant.permission:staff.view');
    Route::post('staff/import', [TenantStaffController::class, 'import'])->middleware('tenant.permission:staff.import');
    Route::post('staff/export', [TenantStaffController::class, 'export'])->middleware('tenant.permission:staff.export');
    Route::delete('staff/bulk', [TenantStaffController::class, 'bulkDestroy'])->middleware('tenant.permission:staff.delete');
    Route::get('staff', [TenantStaffController::class, 'index'])->middleware('tenant.permission:staff.view');
    Route::get('staff/form-options', [TenantStaffController::class, 'formOptions'])->middleware('tenant.permission:staff.view');
    Route::post('staff', [TenantStaffController::class, 'store'])->middleware('tenant.permission:staff.create');
    Route::get('staff/{staff_uuid}', [TenantStaffController::class, 'show'])->middleware('tenant.permission:staff.view');
    Route::match(['put', 'patch'], 'staff/{staff_uuid}', [TenantStaffController::class, 'update'])->middleware('tenant.permission:staff.edit');
    Route::delete('staff/{staff_uuid}', [TenantStaffController::class, 'destroy'])->middleware('tenant.permission:staff.delete');
    Route::post('staff/{staff_uuid}/restore', [TenantStaffController::class, 'restore'])->middleware('tenant.permission:staff.edit');
    Route::get('staff/{staff_uuid}/activity', [TenantStaffController::class, 'activity'])->middleware('tenant.permission:activity_log.view');
    Route::get('staff/{staff_uuid}/roles', [TenantStaffController::class, 'staffRoles'])->middleware('tenant.permission:staff.view');
    Route::put('staff/{staff_uuid}/roles', [TenantStaffController::class, 'replaceStaffRoles'])->middleware('tenant.permission:role.edit');
    Route::get('staff/{staff_uuid}/teams', [TenantStaffController::class, 'staffTeams'])->middleware('tenant.permission:staff.view');
    Route::put('staff/{staff_uuid}/teams', [TenantStaffController::class, 'replaceStaffTeams'])->middleware('tenant.permission:team.assign');
    Route::get('staff/{staff_uuid}/projects', [TenantStaffController::class, 'staffProjects'])->middleware('tenant.permission:staff.view');
    Route::put('staff/{staff_uuid}/projects', [TenantStaffController::class, 'replaceStaffProjects'])->middleware('tenant.permission:project.edit');
    Route::get('staff/{staff_uuid}/tasks', [TenantStaffController::class, 'staffTasks'])->middleware('tenant.permission:staff.view');
    Route::put('staff/{staff_uuid}/tasks', [TenantStaffController::class, 'replaceStaffTasks'])->middleware('tenant.permission:task.assign');
    Route::get('staff/{staff_uuid}/bank-accounts', [TenantStaffController::class, 'bankAccounts'])->middleware('tenant.permission:staff.manage_bank');
    Route::post('staff/{staff_uuid}/bank-accounts', [TenantStaffController::class, 'createBankAccount'])->middleware('tenant.permission:staff.manage_bank');
    Route::match(['put', 'patch'], 'staff/{staff_uuid}/bank-accounts/{id}', [TenantStaffController::class, 'updateBankAccount'])->whereNumber('id')->middleware('tenant.permission:staff.manage_bank');
    Route::delete('staff/{staff_uuid}/bank-accounts/{id}', [TenantStaffController::class, 'deleteBankAccount'])->whereNumber('id')->middleware('tenant.permission:staff.manage_bank');
    Route::get('staff/{staff_uuid}/salary-structures', [TenantStaffController::class, 'salaryStructures'])->middleware('tenant.permission:staff.manage_salary');
    Route::post('staff/{staff_uuid}/salary-structures', [TenantStaffController::class, 'createSalaryStructure'])->middleware('tenant.permission:staff.manage_salary');
    Route::match(['put', 'patch'], 'staff/{staff_uuid}/salary-structures/{id}', [TenantStaffController::class, 'updateSalaryStructure'])->whereNumber('id')->middleware('tenant.permission:staff.manage_salary');
    Route::get('staff/{staff_uuid}/tabs/{tab}', [TenantStaffController::class, 'tab'])->middleware('tenant.permission:staff.view');
    
    Route::get('todo-lists/dashboard', [TenantTodoController::class, 'dashboard'])->middleware('tenant.permission:todo.view');
    Route::get('todo-lists/kanban', [TenantTodoController::class, 'kanban'])->middleware('tenant.permission:todo.view');
    Route::get('todo-lists/calendar', [TenantTodoController::class, 'calendar'])->middleware('tenant.permission:todo.view');
    Route::post('todo-lists/export', [TenantTodoController::class, 'export'])->middleware('tenant.permission:todo.view');
    Route::get('todo-lists', [TenantTodoController::class, 'index'])->middleware('tenant.permission:todo.view');
    Route::post('todo-lists', [TenantTodoController::class, 'store'])->middleware('tenant.permission:todo.create');
    Route::get('todo-lists/{todo_list_uuid}', [TenantTodoController::class, 'show'])->middleware('tenant.permission:todo.view');
    Route::match(['put', 'patch'], 'todo-lists/{todo_list_uuid}', [TenantTodoController::class, 'update'])->middleware('tenant.permission:todo.edit');
    Route::delete('todo-lists/{todo_list_uuid}', [TenantTodoController::class, 'destroy'])->middleware('tenant.permission:todo.delete');
    Route::get('todo-lists/{todo_list_uuid}/tasks', [TenantTodoController::class, 'tasks'])->middleware('tenant.permission:todo.view');
    Route::get('todo-lists/{todo_list_uuid}/reminders', [TenantTodoController::class, 'reminders'])->middleware('tenant.permission:todo.view');
    Route::post('todo-lists/{todo_list_uuid}/reminders', [TenantTodoController::class, 'createReminder'])->middleware('tenant.permission:todo.edit');
    Route::match(['put', 'patch'], 'todo-lists/{todo_list_uuid}/reminders/{reminder_uuid}', [TenantTodoController::class, 'updateReminder'])->middleware('tenant.permission:todo.edit');
    Route::delete('todo-lists/{todo_list_uuid}/reminders/{reminder_uuid}', [TenantTodoController::class, 'deleteReminder'])->middleware('tenant.permission:todo.delete');
    
    Route::post('clients/import', [TenantCrmController::class, 'import'])->middleware('tenant.permission:client.import');
    Route::post('clients/export', [TenantCrmController::class, 'export'])->middleware('tenant.permission:client.export');
    Route::post('clients/merge', [TenantCrmController::class, 'merge'])->middleware('tenant.permission:client.merge');
    Route::get('clients', [TenantCrmController::class, 'clients'])->middleware('tenant.permission:client.view');
    Route::post('clients', [TenantCrmController::class, 'createClient'])->middleware('tenant.permission:client.create');
    Route::get('clients/{client_uuid}', [TenantCrmController::class, 'showClient'])->middleware('tenant.permission:client.view');
    Route::match(['put','patch'], 'clients/{client_uuid}', [TenantCrmController::class, 'updateClient'])->middleware('tenant.permission:client.edit');
    Route::delete('clients/{client_uuid}', [TenantCrmController::class, 'deleteClient'])->middleware('tenant.permission:client.delete');
    Route::post('clients/{client_uuid}/restore', [TenantCrmController::class, 'restoreClient'])->middleware('tenant.permission:client.edit');
    Route::get('clients/{client_uuid}/contacts', [TenantCrmController::class, 'clientContacts'])->middleware('tenant.permission:client.view');
    Route::post('clients/{client_uuid}/contacts', [TenantCrmController::class, 'createClientContact'])->middleware('tenant.permission:client.edit');
    Route::match(['put','patch'], 'clients/{client_uuid}/contacts/{contact_uuid}', [TenantCrmController::class, 'updateClientContact'])->middleware('tenant.permission:client.edit');
    Route::delete('clients/{client_uuid}/contacts/{contact_uuid}', [TenantCrmController::class, 'deleteClientContact'])->middleware('tenant.permission:client.edit');
    Route::get('clients/{client_uuid}/addresses', [TenantCrmController::class, 'clientAddresses'])->middleware('tenant.permission:client.view');
    Route::post('clients/{client_uuid}/addresses', [TenantCrmController::class, 'createClientAddress'])->middleware('tenant.permission:client.edit');
    Route::match(['put','patch'], 'clients/{client_uuid}/addresses/{address_id}', [TenantCrmController::class, 'updateClientAddress'])->whereNumber('address_id')->middleware('tenant.permission:client.edit');
    Route::delete('clients/{client_uuid}/addresses/{address_id}', [TenantCrmController::class, 'deleteClientAddress'])->whereNumber('address_id')->middleware('tenant.permission:client.edit');
    Route::get('clients/{client_uuid}/activity', [TenantCrmController::class, 'clientActivity'])->middleware('tenant.permission:activity_log.view');
    Route::get('clients/{client_uuid}/{resource}', [TenantCrmController::class, 'clientRelated'])->middleware('tenant.permission:client.view');
    
    Route::post('vendors/import', [TenantCrmController::class, 'import'])->middleware('tenant.permission:vendor.import');
    Route::post('vendors/export', [TenantCrmController::class, 'export'])->middleware('tenant.permission:vendor.export');
    Route::get('vendors', [TenantCrmController::class, 'vendors'])->middleware('tenant.permission:vendor.view');
    Route::post('vendors', [TenantCrmController::class, 'createVendor'])->middleware('tenant.permission:vendor.create');
    Route::get('vendors/{vendor_uuid}', [TenantCrmController::class, 'showVendor'])->middleware('tenant.permission:vendor.view');
    Route::match(['put','patch'], 'vendors/{vendor_uuid}', [TenantCrmController::class, 'updateVendor'])->middleware('tenant.permission:vendor.edit');
    Route::delete('vendors/{vendor_uuid}', [TenantCrmController::class, 'deleteVendor'])->middleware('tenant.permission:vendor.delete');
    Route::get('vendors/{vendor_uuid}/contacts', [TenantCrmController::class, 'vendorContacts'])->middleware('tenant.permission:vendor.view');
    Route::post('vendors/{vendor_uuid}/contacts', [TenantCrmController::class, 'createVendorContact'])->middleware('tenant.permission:vendor.edit');
    Route::match(['put','patch'], 'vendors/{vendor_uuid}/contacts/{contact_uuid}', [TenantCrmController::class, 'updateVendorContact'])->middleware('tenant.permission:vendor.edit');
    Route::delete('vendors/{vendor_uuid}/contacts/{contact_uuid}', [TenantCrmController::class, 'deleteVendorContact'])->middleware('tenant.permission:vendor.edit');
    Route::get('vendors/{vendor_uuid}/addresses', [TenantCrmController::class, 'vendorAddresses'])->middleware('tenant.permission:vendor.view');
    Route::post('vendors/{vendor_uuid}/addresses', [TenantCrmController::class, 'createVendorAddress'])->middleware('tenant.permission:vendor.edit');
    Route::match(['put','patch'], 'vendors/{vendor_uuid}/addresses/{address_id}', [TenantCrmController::class, 'updateVendorAddress'])->whereNumber('address_id')->middleware('tenant.permission:vendor.edit');
    Route::delete('vendors/{vendor_uuid}/addresses/{address_id}', [TenantCrmController::class, 'deleteVendorAddress'])->whereNumber('address_id')->middleware('tenant.permission:vendor.edit');
    Route::get('vendors/{vendor_uuid}/bank-accounts', [TenantCrmController::class, 'vendorBankAccounts'])->middleware('tenant.permission:finance.bank_account.view');
    Route::post('vendors/{vendor_uuid}/bank-accounts', [TenantCrmController::class, 'createVendorBankAccount'])->middleware('tenant.permission:finance.bank_account.create');
    Route::match(['put','patch'], 'vendors/{vendor_uuid}/bank-accounts/{account_id}', [TenantCrmController::class, 'updateVendorBankAccount'])->whereNumber('account_id')->middleware('tenant.permission:finance.bank_account.edit');
    Route::delete('vendors/{vendor_uuid}/bank-accounts/{account_id}', [TenantCrmController::class, 'deleteVendorBankAccount'])->whereNumber('account_id')->middleware('tenant.permission:finance.bank_account.delete');
    Route::get('vendors/{vendor_uuid}/activity', [TenantCrmController::class, 'vendorActivity'])->middleware('tenant.permission:activity_log.view');
    Route::get('vendors/{vendor_uuid}/{resource}', [TenantCrmController::class, 'vendorRelated'])->middleware('tenant.permission:vendor.view');
    
    Route::get('renewals', [TenantCrmController::class, 'renewals'])->middleware('tenant.permission:renewal.view');
    Route::post('renewals', [TenantCrmController::class, 'renewalStore'])->middleware('tenant.permission:renewal.create');
    Route::get('renewals/dashboard', [TenantCrmController::class, 'renewalDashboard'])->middleware('tenant.permission:renewal.view');
    Route::get('renewals/calendar', [TenantCrmController::class, 'renewalCalendar'])->middleware('tenant.permission:renewal.view');
    Route::get('client-renewals', [TenantCrmController::class, 'clientRenewals'])->middleware('tenant.permission:renewal.view');
    Route::get('vendor-renewals', [TenantCrmController::class, 'vendorRenewals'])->middleware('tenant.permission:renewal.view');
    Route::post('renewals/export', [TenantCrmController::class, 'export'])->middleware('tenant.permission:renewal.view');

    Route::get('renewals/{renewal_uuid}', [TenantCrmController::class, 'renewalShow'])->middleware('tenant.permission:renewal.view');
    Route::match(['put','patch'], 'renewals/{renewal_uuid}', [TenantCrmController::class, 'renewalUpdate'])->middleware('tenant.permission:renewal.edit');
    Route::delete('renewals/{renewal_uuid}', [TenantCrmController::class, 'renewalDelete'])->middleware('tenant.permission:renewal.delete');
    Route::post('renewals/{renewal_uuid}/renew', [TenantCrmController::class, 'renew'])->middleware('tenant.permission:renewal.renew');
    Route::post('renewals/{renewal_uuid}/cancel', [TenantCrmController::class, 'cancel'])->middleware('tenant.permission:renewal.edit');
    Route::post('renewals/{renewal_uuid}/send-reminder', [TenantCrmController::class, 'sendReminder'])->middleware('tenant.permission:renewal.edit');
    Route::get('renewals/{renewal_uuid}/history', [TenantCrmController::class, 'history'])->middleware('tenant.permission:renewal.view');
    Route::get('renewals/{renewal_uuid}/{kind}', [TenantCrmController::class, 'renewalChild'])->middleware('tenant.permission:renewal.view');
    Route::post('renewals/{renewal_uuid}/{kind}', [TenantCrmController::class, 'renewalChild'])->middleware('tenant.permission:renewal.edit');
    Route::match(['put','patch'], 'renewals/{renewal_uuid}/{kind}/{id}', [TenantCrmController::class, 'renewalChild'])->whereNumber('id')->middleware('tenant.permission:renewal.edit');
    Route::delete('renewals/{renewal_uuid}/{kind}/{id}', [TenantCrmController::class, 'renewalChild'])->whereNumber('id')->middleware('tenant.permission:renewal.edit');
    Route::match(['get','post','put','patch'], 'renewals/{renewal_uuid}/amc', [TenantCrmController::class, 'amc'])->middleware('tenant.permission:renewal.edit');
    Route::get('renewals/{renewal_uuid}/amc/visits', [TenantCrmController::class, 'amcVisits'])->middleware('tenant.permission:renewal.view');
    Route::match(['put','patch'], 'renewals/{renewal_uuid}/amc/visits/{id}', [TenantCrmController::class, 'amcVisit'])->whereNumber('id')->middleware('tenant.permission:renewal.edit');
    
    Route::get('projects/dashboard', [TenantWorkController::class, 'projectDashboard'])->middleware('tenant.permission:project.view');
    Route::get('projects/kanban', [TenantWorkController::class, 'projectKanban'])->middleware('tenant.permission:project.view');
    Route::get('projects/gantt', [TenantWorkController::class, 'projectGantt'])->middleware('tenant.permission:project.view');
    Route::get('projects/calendar', [TenantWorkController::class, 'projectCalendar'])->middleware('tenant.permission:project.view');
    Route::post('projects/export', [TenantWorkController::class, 'export'])->middleware('tenant.permission:project.view');
    Route::get('projects', [TenantWorkController::class, 'projects'])->middleware('tenant.permission:project.view');
    Route::post('projects', [TenantWorkController::class, 'projectStore'])->middleware('tenant.permission:project.create');
    Route::get('projects/{project_uuid}', [TenantWorkController::class, 'projectShow'])->middleware('tenant.permission:project.view');
    Route::match(['put','patch'], 'projects/{project_uuid}', [TenantWorkController::class, 'projectUpdate'])->middleware('tenant.permission:project.edit');
    Route::delete('projects/{project_uuid}', [TenantWorkController::class, 'projectDelete'])->middleware('tenant.permission:project.delete');
    Route::post('projects/{project_uuid}/archive', [TenantWorkController::class, 'projectArchive'])->middleware('tenant.permission:project.archive');
    Route::get('projects/{project_uuid}/tasks', [TenantWorkController::class, 'projectTasks'])->middleware('tenant.permission:task.view');
    Route::post('projects/{project_uuid}/tasks', [TenantWorkController::class, 'projectTaskStore'])->middleware('tenant.permission:task.create');
    Route::post('projects/{project_uuid}/milestones/{child_id}/complete', [TenantWorkController::class, 'completeMilestone'])->middleware('tenant.permission:project.edit');
    Route::get('projects/{project_uuid}/{resource}', [TenantWorkController::class, 'children'])->defaults('parent','projects')->middleware('tenant.permission:project.view');
    Route::post('projects/{project_uuid}/{resource}', [TenantWorkController::class, 'children'])->defaults('parent','projects')->middleware('tenant.permission:project.edit');
    Route::match(['put','patch'], 'projects/{project_uuid}/{resource}/{child_id}', [TenantWorkController::class, 'children'])->defaults('parent','projects')->middleware('tenant.permission:project.edit');
    Route::delete('projects/{project_uuid}/{resource}/{child_id}', [TenantWorkController::class, 'children'])->defaults('parent','projects')->middleware('tenant.permission:project.edit');

    Route::get('tasks/dashboard', [TenantWorkController::class, 'taskDashboard'])->middleware('tenant.permission:task.view');
    Route::get('tasks/kanban', [TenantWorkController::class, 'taskKanban'])->middleware('tenant.permission:task.view');
    Route::get('tasks/calendar', [TenantWorkController::class, 'taskCalendar'])->middleware('tenant.permission:task.view');
    Route::get('tasks/my', [TenantWorkController::class, 'taskMy'])->middleware('tenant.permission:task.view');
    Route::get('tasks/team', [TenantWorkController::class, 'taskTeam'])->middleware('tenant.permission:task.view');
    Route::post('tasks/export', [TenantWorkController::class, 'export'])->middleware('tenant.permission:task.view');
    Route::get('tasks', [TenantWorkController::class, 'tasks'])->middleware('tenant.permission:task.view');
    Route::post('tasks', [TenantWorkController::class, 'taskStore'])->middleware('tenant.permission:task.create');
    Route::get('tasks/{task_uuid}', [TenantWorkController::class, 'taskShow'])->middleware('tenant.permission:task.view');
    Route::match(['put','patch'], 'tasks/{task_uuid}', [TenantWorkController::class, 'taskUpdate'])->middleware('tenant.permission:task.edit');
    Route::delete('tasks/{task_uuid}', [TenantWorkController::class, 'taskDelete'])->middleware('tenant.permission:task.delete');
    Route::post('tasks/{task_uuid}/assign', [TenantWorkController::class, 'taskAssign'])->middleware('tenant.permission:task.assign');
    Route::post('tasks/{task_uuid}/status', [TenantWorkController::class, 'taskStatus'])->middleware('tenant.permission:task.edit');
    Route::post('tasks/{task_uuid}/complete', [TenantWorkController::class, 'taskComplete'])->middleware('tenant.permission:task.edit');
    Route::post('tasks/{task_uuid}/clone', [TenantWorkController::class, 'taskClone'])->middleware('tenant.permission:task.create');
    Route::get('tasks/{task_uuid}/{resource}', [TenantWorkController::class, 'children'])->defaults('parent','tasks')->middleware('tenant.permission:task.view');
    Route::post('tasks/{task_uuid}/{resource}', [TenantWorkController::class, 'children'])->defaults('parent','tasks')->middleware('tenant.permission:task.edit');

    Route::get('issues/dashboard', [TenantWorkController::class, 'issueDashboard'])->middleware('tenant.permission:issue.view');
    Route::get('issues/kanban', [TenantWorkController::class, 'issueKanban'])->middleware('tenant.permission:issue.view');
    Route::post('issues/export', [TenantWorkController::class, 'export'])->middleware('tenant.permission:issue.view');
    Route::get('issues', [TenantWorkController::class, 'issueList'])->middleware('tenant.permission:issue.view');
    Route::post('issues', [TenantWorkController::class, 'issueStore'])->middleware('tenant.permission:issue.create');
    Route::get('issues/{issue_uuid}', [TenantWorkController::class, 'issueShow'])->middleware('tenant.permission:issue.view');
    Route::match(['put','patch'], 'issues/{issue_uuid}', [TenantWorkController::class, 'issueUpdate'])->middleware('tenant.permission:issue.edit');
    Route::delete('issues/{issue_uuid}', [TenantWorkController::class, 'issueDelete'])->middleware('tenant.permission:issue.delete');
    Route::post('issues/{issue_uuid}/assign', [TenantWorkController::class, 'issueAssign'])->middleware('tenant.permission:issue.assign');
    Route::post('issues/{issue_uuid}/status', [TenantWorkController::class, 'issueState'])->defaults('state','status')->middleware('tenant.permission:issue.edit');
    Route::post('issues/{issue_uuid}/{state}', [TenantWorkController::class, 'issueState'])->whereIn('state',['resolve','close','reopen'])->middleware('tenant.permission:issue.close');
    
    Route::get('leads/dashboard', [TenantLeadController::class, 'dashboard'])->middleware('tenant.permission:lead.view');
    Route::get('leads/kanban', [TenantLeadController::class, 'kanban'])->middleware('tenant.permission:lead.view');
    Route::get('leads/form-options', [TenantLeadController::class, 'formOptions'])->middleware('tenant.permission:lead.view');
    Route::post('leads/import', [TenantLeadController::class, 'import'])->middleware('tenant.permission:lead.import');
    Route::post('leads/export', [TenantLeadController::class, 'export'])->middleware('tenant.permission:lead.export');
    Route::post('leads/merge', [TenantLeadController::class, 'merge'])->middleware('tenant.permission:lead.edit');
    Route::get('leads', [TenantLeadController::class, 'leads'])->middleware('tenant.permission:lead.view');
    Route::post('leads', [TenantLeadController::class, 'store'])->middleware('tenant.permission:lead.create');
    Route::get('leads/{lead_uuid}', [TenantLeadController::class, 'show'])->middleware('tenant.permission:lead.view');
    Route::match(['put','patch'], 'leads/{lead_uuid}', [TenantLeadController::class, 'update'])->middleware('tenant.permission:lead.edit');
    Route::delete('leads/{lead_uuid}', [TenantLeadController::class, 'delete'])->middleware('tenant.permission:lead.delete');
    Route::post('leads/{lead_uuid}/duplicate', [TenantLeadController::class, 'duplicate'])->middleware('tenant.permission:lead.create');
    Route::post('leads/{lead_uuid}/convert', [TenantLeadController::class, 'convert'])->middleware('tenant.permission:lead.convert');
    Route::post('leads/{lead_uuid}/mark-lost', [TenantLeadController::class, 'lost'])->middleware('tenant.permission:lead.edit');
    Route::get('leads/{lead_uuid}/contacts', [TenantLeadController::class, 'contacts'])->middleware('tenant.permission:lead.view');
    Route::post('leads/{lead_uuid}/contacts', [TenantLeadController::class, 'contacts'])->middleware('tenant.permission:lead.edit');
    Route::match(['put','patch'], 'leads/{lead_uuid}/contacts/{contact_uuid}', [TenantLeadController::class, 'contactChild'])->middleware('tenant.permission:lead.edit');
    Route::delete('leads/{lead_uuid}/contacts/{contact_uuid}', [TenantLeadController::class, 'contactChild'])->middleware('tenant.permission:lead.edit');
    Route::get('leads/{lead_uuid}/addresses', [TenantLeadController::class, 'addresses'])->middleware('tenant.permission:lead.view');
    Route::post('leads/{lead_uuid}/addresses', [TenantLeadController::class, 'addresses'])->middleware('tenant.permission:lead.edit');
    Route::match(['put','patch'], 'leads/{lead_uuid}/addresses/{address_id}', [TenantLeadController::class, 'addressChild'])->whereNumber('address_id')->middleware('tenant.permission:lead.edit');
    Route::delete('leads/{lead_uuid}/addresses/{address_id}', [TenantLeadController::class, 'addressChild'])->whereNumber('address_id')->middleware('tenant.permission:lead.edit');
    Route::get('leads/{lead_uuid}/activities', [TenantLeadController::class, 'activities'])->middleware('tenant.permission:lead.view');
    Route::post('leads/{lead_uuid}/activities', [TenantLeadController::class, 'activities'])->middleware('tenant.permission:lead.edit');
    Route::match(['put','patch'], 'leads/{lead_uuid}/activities/{activity_uuid}', [TenantLeadController::class, 'activityUpdate'])->middleware('tenant.permission:lead.edit');
    Route::get('leads/{lead_uuid}/activity', [TenantLeadController::class, 'activityLog'])->middleware('tenant.permission:activity_log.view');

    Route::get('finance/dashboard', [TenantFinanceController::class, 'dashboard'])->middleware('tenant.permission:finance.invoice.view');
    foreach (['invoices'=>'finance.invoice.view','payments'=>'finance.payment.view','expenses'=>'finance.expense.view'] as $financeModule=>$financeViewPermission) {
        Route::post($financeModule.'/export', [TenantFinanceController::class, 'export'])->defaults('module', $financeModule)->middleware('tenant.permission:'.$financeViewPermission);
    }
    Route::get('invoices', [TenantFinanceController::class, 'invoices'])->middleware('tenant.permission:finance.invoice.view');
    Route::post('invoices', [TenantFinanceController::class, 'invoiceStore'])->middleware('tenant.permission:finance.invoice.create');
    Route::get('invoices/{invoice_uuid}', [TenantFinanceController::class, 'invoiceShow'])->middleware('tenant.permission:finance.invoice.view');
    Route::match(['put','patch'], 'invoices/{invoice_uuid}', [TenantFinanceController::class, 'invoiceUpdate'])->middleware('tenant.permission:finance.invoice.edit');
    Route::post('invoices/{invoice_uuid}/items', [TenantFinanceController::class, 'item'])->middleware('tenant.permission:finance.invoice.edit');
    Route::match(['put','patch'], 'invoices/{invoice_uuid}/items/{item_id}', [TenantFinanceController::class, 'item'])->whereNumber('item_id')->middleware('tenant.permission:finance.invoice.edit');
    Route::delete('invoices/{invoice_uuid}/items/{item_id}', [TenantFinanceController::class, 'item'])->whereNumber('item_id')->middleware('tenant.permission:finance.invoice.edit');
    Route::post('invoices/{invoice_uuid}/send', [TenantFinanceController::class, 'invoiceSend'])->middleware('tenant.permission:finance.invoice.send');
    Route::post('invoices/{invoice_uuid}/cancel', [TenantFinanceController::class, 'invoiceCancel'])->middleware('tenant.permission:finance.invoice.edit');
    Route::get('invoices/{invoice_uuid}/pdf', [TenantFinanceController::class, 'invoicePdf'])->middleware('tenant.permission:finance.invoice.view');
    Route::get('payments', [TenantFinanceController::class, 'payments'])->middleware('tenant.permission:finance.payment.view');
    Route::post('payments', [TenantFinanceController::class, 'paymentStore'])->middleware('tenant.permission:finance.payment.create');
    Route::get('payments/{payment_uuid}', [TenantFinanceController::class, 'paymentShow'])->middleware('tenant.permission:finance.payment.view');
    Route::post('payments/{payment_uuid}/void', [TenantFinanceController::class, 'paymentVoid'])->middleware('tenant.permission:finance.payment.edit');
    Route::get('payments/{payment_uuid}/receipt', [TenantFinanceController::class, 'paymentReceipt'])->middleware('tenant.permission:finance.payment.view');
    Route::get('expenses', [TenantFinanceController::class, 'expenses'])->middleware('tenant.permission:finance.expense.view');
    Route::post('expenses', [TenantFinanceController::class, 'expenseStore'])->middleware('tenant.permission:finance.expense.create');
    Route::get('expenses/{expense_uuid}', [TenantFinanceController::class, 'expenseShow'])->middleware('tenant.permission:finance.expense.view');
    Route::match(['put','patch'], 'expenses/{expense_uuid}', [TenantFinanceController::class, 'expenseUpdate'])->middleware('tenant.permission:finance.expense.edit');
    Route::post('expenses/{expense_uuid}/approve', [TenantFinanceController::class, 'expenseState'])->defaults('state','approved')->middleware('tenant.permission:finance.expense.approve');
    Route::post('expenses/{expense_uuid}/reject', [TenantFinanceController::class, 'expenseState'])->defaults('state','rejected')->middleware('tenant.permission:finance.expense.approve');

    $settingsGroups = ['general','company','branding','localization','communication','security','storage','hr','crm','integrations'];
    Route::get('settings/{group}', [TenantSettingsController::class, 'group'])
        ->whereIn('group', $settingsGroups)
        ->middleware('tenant.permission:setting.view');
    Route::match(['put','patch'], 'settings/{group}', [TenantSettingsController::class, 'update'])
        ->whereIn('group', $settingsGroups)
        ->middleware('tenant.permission:setting.edit');
    Route::get('settings/lookups', [TenantSettingsController::class, 'lookups'])->middleware('tenant.permission:setting.view');
    Route::put('settings/lookups/reorder', [TenantSettingsController::class, 'reorder'])->middleware('tenant.permission:setting.edit');
    Route::delete('settings/lookups/{lookup_uuid}', [TenantSettingsController::class, 'deleteLookup'])->middleware('tenant.permission:setting.edit');
    Route::get('settings/notification-templates', [TenantSettingsController::class, 'templates'])->middleware('tenant.permission:setting.view');
    Route::post('settings/notification-templates', [TenantSettingsController::class, 'templateStore'])->middleware('tenant.permission:setting.edit');
    Route::match(['put','patch'], 'settings/notification-templates/{template_uuid}', [TenantSettingsController::class, 'templateUpdate'])->middleware('tenant.permission:setting.edit');
    Route::get('settings/backups/runs', [TenantSettingsController::class, 'backupRuns'])->middleware('tenant.permission:setting.view');
    Route::post('settings/backups/run', [TenantSettingsController::class, 'runBackup'])->middleware('tenant.permission:setting.edit');
    Route::post('settings/backups/restore', [TenantSettingsController::class, 'restoreBackup'])->middleware('tenant.permission:setting.edit');
    Route::get('reminders', [TenantEngagementController::class, 'reminders'])->middleware('tenant.permission:document.view');
    Route::post('reminders', [TenantEngagementController::class, 'createReminder'])->middleware('tenant.permission:document.upload');
    Route::match(['put','patch'], 'reminders/{reminder_uuid}', [TenantEngagementController::class, 'updateReminder'])->middleware('tenant.permission:document.upload');
    Route::delete('reminders/{reminder_uuid}', [TenantEngagementController::class, 'deleteReminder'])->middleware('tenant.permission:document.delete');
    
    Route::get('communication/logs', [TenantEngagementController::class, 'communicationLogs'])->middleware('tenant.permission:setting.view');
    Route::post('communication/email', [TenantEngagementController::class, 'sendEmail'])->middleware('tenant.permission:setting.edit');
    Route::post('communication/sms', [TenantEngagementController::class, 'sendSms'])->middleware('tenant.permission:setting.edit');
    Route::post('communication/whatsapp', [TenantEngagementController::class, 'sendWhatsApp'])->middleware('tenant.permission:setting.edit');
    Route::post('communication/push', [TenantEngagementController::class, 'sendPush'])->middleware('tenant.permission:setting.edit');
    Route::post('communication/logs/{log_uuid}/retry', [TenantEngagementController::class, 'retryCommunication'])->middleware('tenant.permission:setting.edit');
    
    Route::get('help/articles', [TenantEngagementController::class, 'helpArticles']);
    Route::get('help/articles/{slug}', [TenantEngagementController::class, 'helpArticle']);
    Route::get('help/faqs', [TenantEngagementController::class, 'faqs']);
    Route::get('help/release-notes', [TenantEngagementController::class, 'releaseNotes']);
    Route::get('help/system-status', [TenantEngagementController::class, 'systemStatus']);
    Route::post('help/contact-support', [TenantEngagementController::class, 'contactSupport']);
    
    Route::get('help/tickets', [TenantEngagementController::class, 'supportTickets']);
    Route::get('help/tickets/{ticket_uuid}', [TenantEngagementController::class, 'supportTicket']);
    Route::post('help/tickets/{ticket_uuid}/comments', [TenantEngagementController::class, 'supportComment']);
    
    Route::get('profile/api-tokens', [TenantEngagementController::class, 'tokens']);
    Route::post('profile/api-tokens', [TenantEngagementController::class, 'createToken']);
    Route::post('profile/api-tokens/{token_uuid}/rotate', [TenantEngagementController::class, 'rotateToken']);
    Route::post('profile/api-tokens/{token_uuid}/revoke', [TenantEngagementController::class, 'revokeToken']);
    
    Route::get('notifications', [TenantSettingsController::class, 'notifications'])->middleware('tenant.permission:notification.view');
    Route::get('notifications/unread-count', [TenantSettingsController::class, 'unreadCount'])->middleware('tenant.permission:notification.view');
    Route::post('notifications/bulk/read', [TenantSettingsController::class, 'bulkRead'])->middleware('tenant.permission:notification.manage');
    Route::post('notifications/{notification_id}/read', [TenantSettingsController::class, 'notificationRead'])->middleware('tenant.permission:notification.manage');
    Route::post('notifications/{notification_id}/unread', function (Request $request, string $notification_id) { return app(TenantSettingsController::class)->notificationRead($notification_id, true); })->middleware('tenant.permission:notification.manage');
    Route::get('notifications/{notification_id}', function (string $notification_id) { return app(TenantSettingsController::class)->notificationRead($notification_id, false); })->middleware('tenant.permission:notification.view');
    Route::delete('notifications/{notification_id}', [TenantSettingsController::class, 'notificationDelete'])->middleware('tenant.permission:notification.manage');

    Route::get('calendars', [TenantCalendarController::class, 'calendars'])->middleware('tenant.permission:calendar.view');
    Route::post('calendars', [TenantCalendarController::class, 'calendarStore'])->middleware('tenant.permission:calendar.create');
    Route::get('calendars/{calendar_uuid}', [TenantCalendarController::class, 'calendarShow'])->middleware('tenant.permission:calendar.view');
    Route::match(['put','patch'], 'calendars/{calendar_uuid}', [TenantCalendarController::class, 'calendarUpdate'])->middleware('tenant.permission:calendar.edit');
    Route::delete('calendars/{calendar_uuid}', [TenantCalendarController::class, 'calendarDelete'])->middleware('tenant.permission:calendar.delete');
    Route::get('calendar-events', [TenantCalendarController::class, 'events'])->middleware('tenant.permission:calendar.view');
    Route::post('calendar-events', [TenantCalendarController::class, 'eventStore'])->middleware('tenant.permission:calendar.create');
    Route::get('calendar-events/{event_uuid}', [TenantCalendarController::class, 'eventShow'])->middleware('tenant.permission:calendar.view');
    Route::match(['put','patch'], 'calendar-events/{event_uuid}', [TenantCalendarController::class, 'eventUpdate'])->middleware('tenant.permission:calendar.edit');
    Route::delete('calendar-events/{event_uuid}', [TenantCalendarController::class, 'eventDelete'])->middleware('tenant.permission:calendar.delete');
    Route::post('calendar-events/{event_uuid}/reschedule', [TenantCalendarController::class, 'reschedule'])->middleware('tenant.permission:calendar.edit');
    Route::post('calendar-events/{event_uuid}/video-meeting', [TenantCalendarController::class, 'video'])->middleware('tenant.permission:calendar.edit');
    Route::post('calendar-events/{event_uuid}/room-booking', [TenantCalendarController::class, 'room'])->middleware('tenant.permission:calendar.edit');
    Route::get('calendar-events/{event_uuid}/{kind}', [TenantCalendarController::class, 'child'])->middleware('tenant.permission:calendar.view');
    Route::post('calendar-events/{event_uuid}/{kind}', [TenantCalendarController::class, 'child'])->middleware('tenant.permission:calendar.edit');
    Route::get('meeting-rooms', [TenantCalendarController::class, 'rooms'])->middleware('tenant.permission:calendar.view');
    Route::post('meeting-rooms', [TenantCalendarController::class, 'roomStore'])->middleware('tenant.permission:calendar.manage_team');
    Route::match(['put','patch'], 'meeting-rooms/{room_id}', [TenantCalendarController::class, 'roomUpdate'])->whereNumber('room_id')->middleware('tenant.permission:calendar.manage_team');

    Route::get('integrations/providers', [TenantIntegrationAuditController::class, 'providers'])->middleware('tenant.permission:setting.view');
    Route::get('integrations', [TenantIntegrationAuditController::class, 'integrations'])->middleware('tenant.permission:setting.view');
    Route::post('integrations', [TenantIntegrationAuditController::class, 'store'])->middleware('tenant.permission:setting.edit');
    Route::get('integrations/webhooks', [TenantIntegrationAuditController::class, 'webhooks'])->middleware('tenant.permission:setting.view');
    Route::get('integrations/sync-jobs', [TenantIntegrationAuditController::class, 'syncJobs'])->middleware('tenant.permission:setting.view');
    Route::post('integrations/sync-jobs/{job_id}/retry', [TenantIntegrationAuditController::class, 'retry'])->whereNumber('job_id')->middleware('tenant.permission:setting.edit');
    Route::get('integrations/{integration_uuid}', [TenantIntegrationAuditController::class, 'show'])->middleware('tenant.permission:setting.view');
    Route::match(['put','patch'], 'integrations/{integration_uuid}', [TenantIntegrationAuditController::class, 'update'])->middleware('tenant.permission:setting.edit');
    Route::post('integrations/{integration_uuid}/credentials/rotate', [TenantIntegrationAuditController::class, 'rotate'])->middleware('tenant.permission:setting.edit');
    Route::post('integrations/{integration_uuid}/disconnect', [TenantIntegrationAuditController::class, 'disconnect'])->middleware('tenant.permission:setting.edit');
    Route::get('integrations/{integration_uuid}/field-mappings', [TenantIntegrationAuditController::class, 'mappings'])->middleware('tenant.permission:setting.view');
    Route::put('integrations/{integration_uuid}/field-mappings', [TenantIntegrationAuditController::class, 'saveMappings'])->middleware('tenant.permission:setting.edit');
    Route::get('integrations/{integration_uuid}/rate-limits', [TenantIntegrationAuditController::class, 'rateLimits'])->middleware('tenant.permission:setting.view');
    Route::get('audit/{type}', [TenantIntegrationAuditController::class, 'audit'])->middleware('tenant.permission:audit_log.view');
    Route::get('audit/activity-logs/{activity_id}/compare', [TenantIntegrationAuditController::class, 'compare'])->whereNumber('activity_id')->middleware('tenant.permission:audit_log.view');
    Route::post('audit/export', [TenantIntegrationAuditController::class, 'auditExport'])->middleware('tenant.permission:audit_log.view');
    Route::get('business/selectors', [TenantIntegrationAuditController::class, 'selectors']);

    Route::get('lookups', [TenantSharedPrimitiveController::class, 'lookups'])->middleware('tenant.permission:setting.view');
    Route::get('documents/dashboard', [TenantSharedPrimitiveController::class, 'folders'])->middleware('tenant.permission:document.view');
    Route::get('document-folders', [TenantSharedPrimitiveController::class, 'folders'])->middleware('tenant.permission:document.view');
    Route::post('document-folders', [TenantSharedPrimitiveController::class, 'createFolder'])->middleware('tenant.permission:document.upload');
    Route::post('document-folders/{folder_uuid}/files', [TenantSharedPrimitiveController::class, 'attachFolder'])->middleware('tenant.permission:document.upload');
    Route::get('files', [TenantSharedPrimitiveController::class, 'files'])->middleware('tenant.permission:document.view');
    Route::post('files', [TenantSharedPrimitiveController::class, 'upload'])->middleware('tenant.permission:document.upload');
    Route::get('files/{file_uuid}/download', [TenantSharedPrimitiveController::class, 'download'])->middleware('tenant.permission:document.view');
    Route::delete('files/{file_uuid}', [TenantSharedPrimitiveController::class, 'deleteFile'])->middleware('tenant.permission:document.delete');
    Route::get('attachments', [TenantSharedPrimitiveController::class, 'attachments'])->middleware('tenant.permission:document.view');
    Route::post('attachments', [TenantSharedPrimitiveController::class, 'attach'])->middleware('tenant.permission:document.upload');
    Route::delete('attachments/{attachment_id}', [TenantSharedPrimitiveController::class, 'detach'])->whereNumber('attachment_id')->middleware('tenant.permission:document.delete');
    Route::get('notes', [TenantSharedPrimitiveController::class, 'notes'])->middleware('tenant.permission:document.view');
    Route::post('notes', [TenantSharedPrimitiveController::class, 'noteStore'])->middleware('tenant.permission:document.upload');
    Route::match(['put','patch'], 'notes/{note_uuid}', [TenantSharedPrimitiveController::class, 'noteUpdate'])->middleware('tenant.permission:document.upload');
    Route::delete('notes/{note_uuid}', [TenantSharedPrimitiveController::class, 'noteDelete'])->middleware('tenant.permission:document.delete');
    Route::get('tags', [TenantSharedPrimitiveController::class, 'tags'])->middleware('tenant.permission:setting.view');
    Route::post('tags', [TenantSharedPrimitiveController::class, 'tagStore'])->middleware('tenant.permission:setting.edit');
    Route::match(['put','patch'], 'tags/{tag_uuid}', [TenantSharedPrimitiveController::class, 'tagUpdate'])->middleware('tenant.permission:setting.edit');
    Route::delete('tags/{tag_uuid}', [TenantSharedPrimitiveController::class, 'tagDelete'])->middleware('tenant.permission:setting.edit');
    Route::get('custom-fields', [TenantSharedPrimitiveController::class, 'customFields'])->middleware('tenant.permission:setting.view');
    Route::post('custom-fields', [TenantSharedPrimitiveController::class, 'customFieldStore'])->middleware('tenant.permission:setting.edit');

    Route::get('payroll/dashboard', [TenantHrmsController::class, 'payrollDashboard'])->middleware('tenant.permission:payroll.view');
    Route::get('payroll/cycles', [TenantHrmsController::class, 'payrollCycles'])->middleware('tenant.permission:payroll.view');
    Route::post('payroll/cycles', [TenantHrmsController::class, 'storePayrollCycle'])->middleware('tenant.permission:payroll.generate');
    Route::get('payroll/cycles/{cycle_uuid}', [TenantHrmsController::class, 'showPayrollCycle'])->middleware('tenant.permission:payroll.view');
    Route::match(['put','patch'], 'payroll/cycles/{cycle_uuid}', [TenantHrmsController::class, 'updatePayrollCycle'])->middleware('tenant.permission:payroll.generate');
    Route::post('payroll/cycles/{cycle_uuid}/generate-preview', [TenantHrmsController::class, 'payrollPreview'])->middleware('tenant.permission:payroll.generate');
    Route::post('payroll/cycles/{cycle_uuid}/generate', [TenantHrmsController::class, 'generatePayroll'])->middleware('tenant.permission:payroll.generate');
    Route::post('payroll/cycles/{cycle_uuid}/{action}', [TenantHrmsController::class, 'payrollCycleAction'])->whereIn('action',['submit','approve','lock','reopen'])->middleware('tenant.permission:payroll.approve');
    Route::get('payroll/payrolls', [TenantHrmsController::class, 'payrolls'])->middleware('tenant.permission:payroll.view');
    Route::get('payroll/payrolls/{payroll_uuid}', [TenantHrmsController::class, 'showPayroll'])->middleware('tenant.permission:payroll.view');
    Route::match(['put','patch'], 'payroll/payrolls/{payroll_uuid}', [TenantHrmsController::class, 'updatePayroll'])->middleware('tenant.permission:payroll.generate');
    Route::get('payroll/payrolls/{payroll_uuid}/items', [TenantHrmsController::class, 'payrollItems'])->middleware('tenant.permission:payroll.view');
    Route::get('payroll/payslips', [TenantHrmsController::class, 'payslips'])->middleware('tenant.permission:payroll.view');
    Route::post('payroll/payslips/generate', [TenantHrmsController::class, 'generatePayslips'])->middleware('tenant.permission:payroll.generate');
    Route::post('payroll/payslips/email', [TenantHrmsController::class, 'emailPayslips'])->middleware('tenant.permission:payroll.generate');
    Route::get('payroll/payslips/{payslip_id}/download', [TenantHrmsController::class, 'downloadPayslip'])->whereNumber('payslip_id')->middleware('tenant.permission:payroll.view');
    Route::get('payroll/component-types', [TenantHrmsController::class, 'componentTypes'])->middleware('tenant.permission:payroll.manage_settings');
    Route::post('payroll/component-types', [TenantHrmsController::class, 'storeComponentType'])->middleware('tenant.permission:payroll.manage_settings');
    Route::get('payroll/components', [TenantHrmsController::class, 'components'])->middleware('tenant.permission:payroll.manage_settings');
    Route::post('payroll/components', [TenantHrmsController::class, 'storeComponent'])->middleware('tenant.permission:payroll.manage_settings');
    Route::match(['put','patch'], 'payroll/components/{component_id}', [TenantHrmsController::class, 'updateComponent'])->whereNumber('component_id')->middleware('tenant.permission:payroll.manage_settings');
    Route::get('payroll/component-assignments', [TenantHrmsController::class, 'assignments'])->middleware('tenant.permission:payroll.manage_settings');
    Route::post('payroll/component-assignments', [TenantHrmsController::class, 'storeAssignment'])->middleware('tenant.permission:payroll.manage_settings');
    Route::get('payroll/loans', [TenantHrmsController::class, 'loans'])->middleware('tenant.permission:payroll.manage_settings');
    Route::post('payroll/loans', [TenantHrmsController::class, 'storeLoan'])->middleware('tenant.permission:payroll.manage_settings');
    Route::match(['put','patch'], 'payroll/loans/{loan_id}', [TenantHrmsController::class, 'updateLoan'])->whereNumber('loan_id')->middleware('tenant.permission:payroll.manage_settings');
    Route::get('payroll/reimbursements', [TenantHrmsController::class, 'reimbursements'])->middleware('tenant.permission:payroll.view');
    Route::post('payroll/reimbursements', [TenantHrmsController::class, 'storeReimbursement'])->middleware('tenant.permission:payroll.view');
    Route::post('payroll/reimbursements/{reimbursement_id}/approve', [TenantHrmsController::class, 'approveReimbursement'])->whereNumber('reimbursement_id')->middleware('tenant.permission:payroll.approve');
    Route::get('payroll/bank-transfers', [TenantHrmsController::class, 'bankTransfers'])->middleware('tenant.permission:payroll.view');
    Route::post('payroll/bank-transfers', [TenantHrmsController::class, 'storeBankTransfer'])->middleware('tenant.permission:payroll.view');
    Route::post('payroll/bank-transfers/{transfer_id}/mark-paid', [TenantHrmsController::class, 'markTransferPaid'])->whereNumber('transfer_id')->middleware('tenant.permission:payroll.generate');
    Route::get('payroll/tax-slabs', [TenantHrmsController::class, 'taxSlabs'])->middleware('tenant.permission:payroll.manage_settings');
    Route::post('payroll/tax-slabs', [TenantHrmsController::class, 'storeTaxSlab'])->middleware('tenant.permission:payroll.manage_settings');
    Route::get('payroll/pf-settings', [TenantHrmsController::class, 'pfSettings'])->middleware('tenant.permission:payroll.manage_settings');
    Route::put('payroll/pf-settings', [TenantHrmsController::class, 'updatePfSettings'])->middleware('tenant.permission:payroll.manage_settings');
    Route::get('payroll/esi-settings', [TenantHrmsController::class, 'esiSettings'])->middleware('tenant.permission:payroll.manage_settings');
    Route::put('payroll/esi-settings', [TenantHrmsController::class, 'updateEsiSettings'])->middleware('tenant.permission:payroll.manage_settings');
    Route::post('payroll/export', [TenantHrmsController::class, 'payrollExport'])->middleware('tenant.permission:payroll.export');
    

    Route::get('holidays', [TenantHrmsController::class, 'holidays'])->middleware('tenant.permission:holiday.view');
    Route::post('holidays', [TenantHrmsController::class, 'storeHoliday'])->middleware('tenant.permission:holiday.create');
    Route::get('holidays/{holiday_uuid}', [TenantHrmsController::class, 'showHoliday'])->middleware('tenant.permission:holiday.view');
    Route::match(['put','patch'], 'holidays/{holiday_uuid}', [TenantHrmsController::class, 'updateHoliday'])->middleware('tenant.permission:holiday.edit');
    Route::delete('holidays/{holiday_uuid}', [TenantHrmsController::class, 'deleteHoliday'])->middleware('tenant.permission:holiday.delete');
    Route::post('holidays/{holiday_uuid}/duplicate-next-year', [TenantHrmsController::class, 'duplicateHoliday'])->middleware('tenant.permission:holiday.create');
    Route::post('holidays/import', [TenantHrmsController::class, 'importHolidays'])->middleware('tenant.permission:holiday.create');
    Route::post('holidays/export', [TenantHrmsController::class, 'exportHolidays'])->middleware('tenant.permission:holiday.view');
    Route::get('holiday-calendars', [TenantHrmsController::class, 'holidayCalendars'])->middleware('tenant.permission:holiday.view');
    Route::post('holiday-calendars', [TenantHrmsController::class, 'storeHolidayCalendar'])->middleware('tenant.permission:holiday.view');
    Route::get('holiday-calendars/{calendar_uuid}', [TenantHrmsController::class, 'showHolidayCalendar'])->middleware('tenant.permission:holiday.view');
    Route::match(['put','patch'], 'holiday-calendars/{calendar_uuid}', [TenantHrmsController::class, 'updateHolidayCalendar'])->middleware('tenant.permission:holiday.edit');
    Route::delete('holiday-calendars/{calendar_uuid}', [TenantHrmsController::class, 'deleteHolidayCalendar'])->middleware('tenant.permission:holiday.delete');
    Route::get('holiday-groups', [TenantHrmsController::class, 'holidayGroups'])->middleware('tenant.permission:holiday.view');
    Route::post('holiday-groups', [TenantHrmsController::class, 'storeHolidayGroup'])->middleware('tenant.permission:holiday.view');
    Route::match(['put','patch'], 'holiday-groups/{group_uuid}', [TenantHrmsController::class, 'updateHolidayGroup'])->middleware('tenant.permission:holiday.edit');
    Route::get('holiday-groups/{group_uuid}/members', [TenantHrmsController::class, 'groupMembers'])->middleware('tenant.permission:holiday.view');
    Route::post('holiday-groups/{group_uuid}/members', [TenantHrmsController::class, 'addGroupMembers'])->middleware('tenant.permission:holiday.view');
    Route::delete('holiday-groups/{group_uuid}/members/{staff_uuid}', [TenantHrmsController::class, 'removeGroupMember'])->middleware('tenant.permission:holiday.edit');
    Route::get('navigation/sidebar', [TenantDashboardController::class, 'navigation']);
    Route::get('dashboard/summary', [TenantDashboardController::class, 'summary'])->middleware('tenant.permission:dashboard.view');
    Route::get('dashboard/charts/{chart}', [TenantDashboardController::class, 'chart'])->middleware('tenant.permission:dashboard.view');
    Route::get('dashboard/recent-activities', [TenantDashboardController::class, 'recentActivities'])->middleware('tenant.permission:activity_log.view');
    Route::get('dashboard/widgets', [TenantDashboardController::class, 'widgets'])->middleware('tenant.permission:dashboard.view');
    Route::put('dashboard/widgets', [TenantDashboardController::class, 'updateWidgets'])->middleware('tenant.permission:dashboard.customize');
    Route::post('dashboard/export', [TenantDashboardController::class, 'exportDashboard'])->middleware('tenant.permission:dashboard.view');
    Route::get('dashboard/{widget}', [TenantDashboardController::class, 'widget'])->middleware('tenant.permission:dashboard.view');
    Route::get('reports/dashboard', [TenantDashboardController::class, 'reportsDashboard'])->middleware('tenant.permission:report.view');
    Route::get('reports/custom', [TenantDashboardController::class, 'customReports'])->middleware('tenant.permission:report.view');
    Route::post('reports/custom', [TenantDashboardController::class, 'createCustomReport'])->middleware('tenant.permission:report.edit');
    Route::post('reports/custom/{report_uuid}/run', [TenantDashboardController::class, 'runCustomReport'])->middleware('tenant.permission:report.view');
    Route::get('reports/{report_code}', [TenantDashboardController::class, 'report'])->middleware('tenant.permission:report.view');
    Route::post('reports/{report_code}/export', [TenantDashboardController::class, 'exportReport'])->middleware('tenant.permission:report.export');    Route::get('leave/dashboard', [TenantHrmsController::class, 'leaveDashboard'])->middleware('tenant.permission:leave.view');
    Route::get('leave/requests', [TenantHrmsController::class, 'leaveRequests'])->middleware('tenant.permission:leave.view');
    Route::post('leave/requests', [TenantHrmsController::class, 'storeLeaveRequest']);
    Route::get('leave/requests/{request_id}', [TenantHrmsController::class, 'leaveRequestShow'])->whereNumber('request_id')->middleware('tenant.permission:leave.view');
    Route::post('leave/requests/{request_id}/approve', [TenantHrmsController::class, 'reviewLeave'])->defaults('status', 'approved')->whereNumber('request_id')->middleware('tenant.permission:leave.approve');
    Route::post('leave/requests/{request_id}/reject', [TenantHrmsController::class, 'reviewLeave'])->defaults('status', 'rejected')->whereNumber('request_id')->middleware('tenant.permission:leave.approve');
    Route::post('leave/requests/{request_id}/cancel', [TenantHrmsController::class, 'cancelLeave'])->whereNumber('request_id');
    Route::get('leave/balances', [TenantHrmsController::class, 'leaveBalances'])->middleware('tenant.permission:leave.view');
    Route::post('leave/balances/adjust', [TenantHrmsController::class, 'adjustLeaveBalance'])->middleware('tenant.permission:leave.approve');
    Route::get('leave/calendar', [TenantHrmsController::class, 'leaveCalendar'])->middleware('tenant.permission:leave.view');
    Route::get('leave/types', [TenantHrmsController::class, 'leaveTypes'])->middleware('tenant.permission:setting.view');
    Route::post('leave/types', [TenantHrmsController::class, 'storeLeaveType'])->middleware('tenant.permission:setting.edit');
    
    Route::get('attendance/dashboard', [TenantHrmsController::class, 'dashboard'])->middleware('tenant.permission:attendance.view');
    Route::get('attendance/daily', [TenantHrmsController::class, 'daily'])->middleware('tenant.permission:attendance.view');
    Route::get('attendance/monthly', [TenantHrmsController::class, 'monthly'])->middleware('tenant.permission:attendance.view');
    Route::post('attendance/check-in', [TenantHrmsController::class, 'checkIn']);
    Route::post('attendance/check-out', [TenantHrmsController::class, 'checkOut']);
    Route::post('attendance/records', [TenantHrmsController::class, 'storeRecord'])->middleware('tenant.permission:attendance.create');
    Route::get('attendance/records/{record_id}', [TenantHrmsController::class, 'showRecord'])->whereNumber('record_id')->middleware('tenant.permission:attendance.view');
    Route::match(['put', 'patch'], 'attendance/records/{record_id}', [TenantHrmsController::class, 'updateRecord'])->whereNumber('record_id')->middleware('tenant.permission:attendance.edit');
    Route::post('attendance/import', [TenantHrmsController::class, 'import'])->middleware('tenant.permission:attendance.edit');
    Route::post('attendance/export', [TenantHrmsController::class, 'export'])->middleware('tenant.permission:attendance.export');
    Route::get('attendance/requests', [TenantHrmsController::class, 'requests'])->middleware('tenant.permission:attendance.view');
    Route::post('attendance/requests', [TenantHrmsController::class, 'storeRequest']);
    Route::get('attendance/requests/{request_uuid}', [TenantHrmsController::class, 'requestShow'])->middleware('tenant.permission:attendance.view');
    Route::post('attendance/requests/{request_uuid}/approve', [TenantHrmsController::class, 'review'])->defaults('status', 'approved')->middleware('tenant.permission:attendance.approve');
    Route::post('attendance/requests/{request_uuid}/reject', [TenantHrmsController::class, 'review'])->defaults('status', 'rejected')->middleware('tenant.permission:attendance.approve');
    
    
});
