<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('departments', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('parent_id')->nullable()->constrained('departments')->nullOnDelete(); $table->string('name',150); $table->string('code',80); $table->unsignedBigInteger('manager_user_id')->nullable()->index(); $table->string('status',50)->default('active'); $table->timestamps(); $table->unique(['tenant_id','code']); });
        Schema::create('designations', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('department_id')->nullable()->constrained('departments')->nullOnDelete(); $table->string('name',150); $table->string('code',80); $table->string('status',50)->default('active'); $table->timestamps(); $table->unique(['tenant_id','code']); });
        Schema::create('teams', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('parent_team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->foreignId('department_id')->nullable()->constrained('departments')->nullOnDelete(); $table->foreignId('office_id')->nullable()->constrained('tenant_offices')->nullOnDelete(); $table->foreignId('team_type_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->string('name',150); $table->string('code',80); $table->text('description')->nullable(); $table->foreignId('lead_user_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('assistant_lead_user_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('email',150)->nullable(); $table->string('phone',20)->nullable(); $table->string('color',30)->nullable(); $table->string('icon',80)->nullable(); $table->string('visibility',50)->default('tenant'); $table->boolean('is_default')->default(false); $table->string('status',50)->default('active'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','code']); $table->index(['tenant_id','department_id','status']); });
        Schema::create('team_roles', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name',150); $table->string('code',80); $table->text('description')->nullable(); $table->json('permissions')->nullable(); $table->integer('sort_order')->default(0); $table->boolean('is_system')->default(false); $table->string('status',50)->default('active'); $table->timestamps(); $table->unique(['tenant_id','code']); });
        Schema::create('staff', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('employee_code',80); $table->string('first_name',100); $table->string('last_name',100)->nullable(); $table->string('display_name',200); $table->string('personal_email',150)->nullable(); $table->string('work_email',150)->nullable(); $table->string('mobile',20)->nullable(); $table->string('gender',30)->nullable(); $table->date('date_of_birth')->nullable(); $table->date('joining_date')->nullable(); $table->date('exit_date')->nullable(); $table->foreignId('department_id')->nullable()->constrained('departments')->nullOnDelete(); $table->foreignId('designation_id')->nullable()->constrained('designations')->nullOnDelete(); $table->foreignId('office_id')->nullable()->constrained('tenant_offices')->nullOnDelete(); $table->foreignId('primary_team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->foreignId('reporting_manager_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('employment_type',50)->nullable(); $table->string('employment_status',50)->default('active'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','employee_code']); $table->index(['tenant_id','department_id','employment_status']); $table->index(['tenant_id','primary_team_id']); });
        Schema::create('team_members', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('team_id')->constrained('teams')->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained('users')->cascadeOnDelete(); $table->foreignId('staff_id')->nullable()->constrained('staff')->cascadeOnDelete(); $table->foreignId('team_role_id')->nullable()->constrained('team_roles')->nullOnDelete(); $table->string('member_type',50)->default('member'); $table->decimal('allocation_percent',5,2)->default(100); $table->boolean('is_primary')->default(false); $table->date('effective_from')->nullable(); $table->date('effective_to')->nullable(); $table->dateTime('joined_at')->nullable(); $table->dateTime('left_at')->nullable(); $table->string('status',50)->default('active'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->unique(['tenant_id','team_id','user_id','effective_from']); });
        Schema::create('team_permissions', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('team_id')->constrained('teams')->cascadeOnDelete(); $table->foreignId('permission_id')->constrained('permissions')->cascadeOnDelete(); $table->foreignId('granted_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('granted_at')->nullable(); $table->unique(['tenant_id','team_id','permission_id']); });
        Schema::create('team_settings', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('team_id')->constrained('teams')->cascadeOnDelete(); $table->string('group',100); $table->string('key',150); $table->json('value')->nullable(); $table->string('value_type',50)->default('json'); $table->timestamps(); $table->unique(['tenant_id','team_id','group','key']); });
        Schema::create('team_assignments', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('team_id')->constrained('teams')->cascadeOnDelete(); $table->string('assignable_type',120); $table->unsignedBigInteger('assignable_id'); $table->string('assignment_role',80)->nullable(); $table->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('assigned_at')->nullable(); $table->dateTime('released_at')->nullable(); $table->string('status',50)->default('active'); $table->index(['tenant_id','assignable_type','assignable_id'], 'team_assignable_idx'); });
        Schema::create('staff_employment_history', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->foreignId('department_id')->nullable()->constrained('departments')->nullOnDelete(); $table->foreignId('designation_id')->nullable()->constrained('designations')->nullOnDelete(); $table->foreignId('office_id')->nullable()->constrained('tenant_offices')->nullOnDelete(); $table->date('effective_from'); $table->date('effective_to')->nullable(); });
        Schema::create('staff_bank_accounts', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->string('account_holder_name'); $table->string('bank_name'); $table->text('account_number_encrypted'); $table->string('ifsc_code',30)->nullable(); $table->boolean('is_primary')->default(false); $table->timestamps(); });
        Schema::create('staff_salary_structures', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->restrictOnDelete(); $table->date('effective_from'); $table->date('effective_to')->nullable(); $table->decimal('annual_ctc',18,2)->default(0); $table->decimal('monthly_gross',18,2)->default(0); $table->char('currency',3)->default('INR'); });
        Schema::create('staff_documents', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->foreignId('document_type_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('file_id')->constrained('files')->restrictOnDelete(); $table->string('document_number')->nullable(); $table->date('expiry_date')->nullable(); });
        Schema::create('staff_emergency_contacts', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->string('name'); $table->string('relation',80); $table->string('mobile',20); $table->string('email')->nullable(); $table->text('address')->nullable(); });
        Schema::create('staff_assets', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->string('asset_name'); $table->string('asset_code',80); $table->date('issued_at')->nullable(); $table->date('returned_at')->nullable(); $table->string('status',50)->default('issued'); $table->unique(['tenant_id','asset_code']); });
        Schema::create('staff_certifications', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->string('name'); $table->string('provider')->nullable(); $table->date('issued_on')->nullable(); $table->date('expires_on')->nullable(); $table->foreignId('file_id')->nullable()->constrained('files')->nullOnDelete(); });
        Schema::create('staff_appraisals', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->restrictOnDelete(); $table->string('review_period',80); $table->decimal('rating',4,2)->nullable(); $table->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('reviewed_at')->nullable(); });
        Schema::create('staff_training', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->string('training_name'); $table->string('provider')->nullable(); $table->date('started_on')->nullable(); $table->date('completed_on')->nullable(); $table->string('status',50)->default('planned'); });
        Schema::create('shifts', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name'); $table->time('start_time'); $table->time('end_time'); $table->unsignedInteger('break_minutes')->default(0); $table->string('status',50)->default('active'); $table->timestamps(); });
        Schema::create('staff_shift_assignments', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->foreignId('shift_id')->constrained('shifts')->restrictOnDelete(); $table->date('effective_from'); $table->date('effective_to')->nullable(); });
        Schema::create('attendance_records', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->restrictOnDelete(); $table->date('attendance_date'); $table->dateTime('check_in_at')->nullable(); $table->dateTime('check_out_at')->nullable(); $table->unsignedInteger('total_minutes')->default(0); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->timestamps(); $table->unique(['tenant_id','staff_id','attendance_date']); });
        Schema::create('attendance_requests', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->restrictOnDelete(); $table->date('request_date'); $table->string('request_type',80); $table->text('reason')->nullable(); $table->string('status',50)->default('pending'); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('approved_at')->nullable(); $table->timestamps(); $table->index(['tenant_id','staff_id','status']); });
        Schema::create('leave_types', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name'); $table->string('code',80); $table->boolean('paid')->default(true); $table->boolean('carry_forward')->default(false); $table->string('status',50)->default('active'); $table->unique(['tenant_id','code']); });
        Schema::create('leave_requests', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignId('leave_type_id')->constrained('leave_types')->restrictOnDelete(); $table->date('start_date'); $table->date('end_date'); $table->decimal('total_days',8,2); $table->text('reason')->nullable(); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('approved_at')->nullable(); $table->timestamps(); $table->index(['tenant_id','staff_id','start_date']); });
        Schema::create('leave_balances', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->restrictOnDelete(); $table->foreignId('leave_type_id')->constrained('leave_types')->restrictOnDelete(); $table->unsignedSmallInteger('year'); foreach (['opening_balance','accrued','used','remaining'] as $column) { $table->decimal($column,8,2)->default(0); } $table->unique(['tenant_id','staff_id','leave_type_id','year']); });
    }
    public function down(): void { foreach (['leave_balances','leave_requests','leave_types','attendance_requests','attendance_records','staff_shift_assignments','shifts','staff_training','staff_appraisals','staff_certifications','staff_assets','staff_emergency_contacts','staff_documents','staff_salary_structures','staff_bank_accounts','staff_employment_history','team_assignments','team_settings','team_permissions','team_members','staff','team_roles','teams','designations','departments'] as $table) { Schema::dropIfExists($table); } }
};