<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('projects', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('project_number',80); $table->string('name'); $table->text('description')->nullable(); $table->foreignId('client_party_id')->nullable()->constrained('parties')->nullOnDelete(); $table->foreignId('project_manager_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('category_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('type_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('priority_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->date('start_date')->nullable(); $table->date('due_date')->nullable(); $table->dateTime('completed_at')->nullable(); $table->decimal('budget_amount',18,2)->default(0); $table->string('billing_type',50)->nullable(); $table->unsignedTinyInteger('progress')->default(0); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','project_number']); $table->index(['tenant_id','status_id','due_date']); });
        Schema::create('project_members', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('project_id')->constrained('projects')->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained('users')->cascadeOnDelete(); $table->foreignId('team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->foreignId('role_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->decimal('billing_rate',18,2)->nullable(); $table->decimal('allocation_percent',5,2)->default(100); $table->dateTime('joined_at')->nullable(); $table->dateTime('left_at')->nullable(); $table->index(['tenant_id','project_id']); });
        Schema::create('project_phases', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('project_id')->constrained('projects')->cascadeOnDelete(); $table->string('name'); $table->date('start_date')->nullable(); $table->date('due_date')->nullable(); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->integer('sort_order')->default(0); });
        Schema::create('project_milestones', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('project_id')->constrained('projects')->cascadeOnDelete(); $table->foreignId('phase_id')->nullable()->constrained('project_phases')->cascadeOnDelete(); $table->string('name'); $table->date('due_date')->nullable(); $table->dateTime('completed_at')->nullable(); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); });
        Schema::create('tasks', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('task_number',80); $table->foreignId('parent_task_id')->nullable()->constrained('tasks')->nullOnDelete(); $table->foreignId('project_id')->nullable()->constrained('projects')->cascadeOnDelete(); $table->string('related_type',120)->nullable(); $table->unsignedBigInteger('related_id')->nullable(); $table->string('title'); $table->text('description')->nullable(); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('priority_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('category_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('assigned_team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('start_at')->nullable(); $table->dateTime('due_at')->nullable(); $table->dateTime('completed_at')->nullable(); $table->unsignedInteger('estimated_minutes')->default(0); $table->unsignedInteger('actual_minutes')->default(0); $table->unsignedTinyInteger('progress')->default(0); $table->boolean('is_recurring')->default(false); $table->json('recurrence_rule')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','task_number']); $table->index(['tenant_id','assigned_to','due_at']); $table->index(['tenant_id','assigned_team_id','due_at']); $table->index(['tenant_id','related_type','related_id']); });
        Schema::create('project_time_logs', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('project_id')->constrained('projects')->cascadeOnDelete(); $table->foreignId('task_id')->nullable()->constrained('tasks')->cascadeOnDelete(); $table->foreignId('user_id')->constrained('users')->restrictOnDelete(); $table->dateTime('started_at'); $table->dateTime('ended_at')->nullable(); $table->unsignedInteger('minutes')->default(0); $table->boolean('billable')->default(false); });
        Schema::create('project_expenses', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('project_id')->constrained('projects')->restrictOnDelete(); $table->foreignId('vendor_party_id')->nullable()->constrained('parties')->restrictOnDelete(); $table->decimal('amount',18,2); $table->char('currency',3)->default('INR'); $table->date('expense_date'); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); });
        Schema::create('task_checklists', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('task_id')->constrained('tasks')->cascadeOnDelete(); $table->string('title'); $table->integer('sort_order')->default(0); });
        Schema::create('task_checklist_items', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('checklist_id')->constrained('task_checklists')->cascadeOnDelete(); $table->string('title'); $table->boolean('is_completed')->default(false); $table->foreignId('completed_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('completed_at')->nullable(); $table->integer('sort_order')->default(0); });
        Schema::create('task_comments', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('task_id')->constrained('tasks')->cascadeOnDelete(); $table->foreignId('parent_id')->nullable()->constrained('task_comments')->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->text('comment'); $table->dateTime('created_at')->nullable(); });
        Schema::create('task_dependencies', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('task_id')->constrained('tasks')->cascadeOnDelete(); $table->foreignId('depends_on_task_id')->constrained('tasks')->cascadeOnDelete(); $table->string('dependency_type',50)->default('finish_to_start'); $table->unique(['tenant_id','task_id','depends_on_task_id'], 'task_dependencies_uq'); });
        Schema::create('task_watchers', function (Blueprint $table) { $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('task_id')->constrained('tasks')->cascadeOnDelete(); $table->foreignId('user_id')->constrained('users')->cascadeOnDelete(); $table->primary(['tenant_id','task_id','user_id']); });
        Schema::create('task_assignments', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('task_id')->constrained('tasks')->cascadeOnDelete(); $table->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('assigned_team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('assigned_at')->nullable(); $table->string('remarks')->nullable(); });
        Schema::create('task_time_logs', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('task_id')->constrained('tasks')->cascadeOnDelete(); $table->foreignId('user_id')->constrained('users')->restrictOnDelete(); $table->dateTime('started_at'); $table->dateTime('ended_at')->nullable(); $table->unsignedInteger('minutes')->default(0); $table->text('notes')->nullable(); });
        Schema::create('todo_lists', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name'); $table->text('description')->nullable(); $table->foreignId('owner_user_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->string('visibility',50)->default('private'); $table->string('color',30)->nullable(); $table->string('icon',80)->nullable(); $table->boolean('is_default')->default(false); $table->string('status',50)->default('active'); $table->timestamps(); $table->softDeletes(); });
        Schema::create('client_issues', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('issue_number',80); $table->foreignId('client_party_id')->constrained('parties')->restrictOnDelete(); $table->foreignId('contact_id')->nullable()->constrained('party_contacts')->nullOnDelete(); $table->foreignId('project_id')->nullable()->constrained('projects')->nullOnDelete(); $table->string('title'); $table->text('description')->nullable(); $table->foreignId('type_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('category_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('priority_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('assigned_team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->dateTime('due_at')->nullable(); $table->dateTime('resolved_at')->nullable(); $table->dateTime('closed_at')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','issue_number']); $table->index(['tenant_id','assigned_to','due_at']); $table->index(['tenant_id','assigned_team_id','due_at']); });
        Schema::create('renewals', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('renewal_number',80); $table->foreignId('party_id')->nullable()->constrained('parties')->restrictOnDelete(); $table->string('renewal_type',80); $table->string('title'); $table->text('description')->nullable(); $table->date('start_date')->nullable(); $table->date('end_date')->nullable(); $table->date('renewal_date'); $table->decimal('amount',18,2)->default(0); $table->char('currency',3)->default('INR'); $table->unsignedInteger('reminder_days_before')->default(0); $table->boolean('auto_renew')->default(false); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('owner_user_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','renewal_number']); });
        Schema::create('renewal_items', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('renewal_id')->constrained('renewals')->cascadeOnDelete(); $table->string('name'); $table->decimal('quantity',18,2)->default(1); $table->decimal('unit_price',18,2)->default(0); $table->decimal('amount',18,2)->default(0); });
        Schema::create('renewal_history', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('renewal_id')->constrained('renewals')->cascadeOnDelete(); $table->date('old_end_date')->nullable(); $table->date('new_end_date')->nullable(); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->string('remarks')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('created_at')->nullable(); });
        Schema::create('renewal_reminders', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('renewal_id')->constrained('renewals')->cascadeOnDelete(); $table->dateTime('remind_at'); $table->string('channel',50); $table->dateTime('sent_at')->nullable(); $table->string('status',50)->default('pending'); });
        Schema::create('calendars', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('owner_user_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->string('name'); $table->string('calendar_type',80); $table->string('color',30)->nullable(); $table->string('timezone',100)->default('UTC'); $table->string('visibility',50)->default('private'); $table->string('status',50)->default('active'); $table->timestamps(); });
        Schema::create('calendar_events', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('calendar_id')->constrained('calendars')->cascadeOnDelete(); $table->string('related_type',120)->nullable(); $table->unsignedBigInteger('related_id')->nullable(); $table->string('title'); $table->text('description')->nullable(); $table->string('location')->nullable(); $table->dateTime('starts_at'); $table->dateTime('ends_at')->nullable(); $table->string('timezone',100)->default('UTC'); $table->boolean('all_day')->default(false); $table->json('recurrence_rule')->nullable(); $table->string('status',50)->default('scheduled'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->index(['tenant_id','starts_at','status']); $table->index(['tenant_id','related_type','related_id']); });
        Schema::create('calendar_event_attendees', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('event_id')->constrained('calendar_events')->cascadeOnDelete(); $table->string('attendee_type',50); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('team_id')->nullable()->constrained('teams')->nullOnDelete(); $table->foreignId('contact_id')->nullable()->constrained('party_contacts')->nullOnDelete(); $table->string('email')->nullable(); $table->string('response_status',50)->default('pending'); });
        Schema::create('calendar_event_reminders', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('event_id')->constrained('calendar_events')->cascadeOnDelete(); $table->string('channel',50); $table->dateTime('remind_at'); $table->dateTime('sent_at')->nullable(); $table->string('status',50)->default('pending'); });
        Schema::create('meeting_rooms', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name'); $table->foreignId('office_id')->nullable()->constrained('tenant_offices')->nullOnDelete(); $table->string('location')->nullable(); $table->unsignedInteger('capacity')->nullable(); $table->string('status',50)->default('active'); });
        Schema::create('meeting_room_bookings', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('room_id')->constrained('meeting_rooms')->restrictOnDelete(); $table->foreignId('event_id')->constrained('calendar_events')->cascadeOnDelete(); $table->foreignId('booked_by')->nullable()->constrained('users')->nullOnDelete(); $table->string('status',50)->default('booked'); });
        Schema::create('video_meetings', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('event_id')->constrained('calendar_events')->cascadeOnDelete(); $table->string('provider',80); $table->string('meeting_id')->nullable(); $table->text('meeting_url')->nullable(); $table->text('passcode')->nullable(); });
        Schema::create('calendar_sync_logs', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('calendar_id')->constrained('calendars')->cascadeOnDelete(); $table->string('provider',80); $table->string('external_event_id')->nullable(); $table->string('sync_status',50); $table->dateTime('synced_at')->nullable(); });
        Schema::create('reminders', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('remindable_type',120); $table->unsignedBigInteger('remindable_id'); $table->foreignId('user_id')->constrained('users')->cascadeOnDelete(); $table->string('channel',50); $table->dateTime('remind_at'); $table->dateTime('sent_at')->nullable(); $table->string('status',50)->default('pending'); $table->json('metadata')->nullable(); $table->timestamps(); $table->index(['tenant_id','remindable_type','remindable_id']); $table->index(['tenant_id','user_id','remind_at']); });
    }
    public function down(): void { foreach (['reminders','calendar_sync_logs','video_meetings','meeting_room_bookings','meeting_rooms','calendar_event_reminders','calendar_event_attendees','calendar_events','calendars','renewal_reminders','renewal_history','renewal_items','renewals','client_issues','todo_lists','task_time_logs','task_assignments','task_watchers','task_dependencies','task_comments','task_checklist_items','task_checklists','project_expenses','project_time_logs','tasks','project_milestones','project_phases','project_members','projects'] as $table) { Schema::dropIfExists($table); } }
};