<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('tenant_invoices', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->string('invoice_number',80); $table->foreignId('client_party_id')->constrained('parties')->restrictOnDelete(); $table->foreignId('project_id')->nullable()->constrained('projects')->restrictOnDelete(); $table->date('invoice_date'); $table->date('due_date')->nullable(); foreach (['subtotal','discount_amount','taxable_amount','tax_amount','total_amount','paid_amount','balance_amount'] as $column) { $table->decimal($column,18,2)->default(0); } $table->char('currency',3)->default('INR'); $table->string('status',50)->default('draft'); $table->foreignId('pdf_file_id')->nullable()->constrained('files')->nullOnDelete(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','invoice_number']); $table->index(['tenant_id','status','invoice_date']); });
        Schema::create('tenant_invoice_items', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->foreignId('invoice_id')->constrained('tenant_invoices')->restrictOnDelete(); $table->string('item_name'); $table->text('description')->nullable(); $table->decimal('quantity',18,2)->default(1); $table->decimal('unit_price',18,2)->default(0); $table->decimal('tax_rate',8,2)->default(0); $table->decimal('amount',18,2)->default(0); });
        Schema::create('tenant_payments', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->foreignId('invoice_id')->nullable()->constrained('tenant_invoices')->restrictOnDelete(); $table->foreignId('client_party_id')->nullable()->constrained('parties')->restrictOnDelete(); $table->string('payment_number',80); $table->decimal('amount',18,2); $table->char('currency',3)->default('INR'); $table->string('method',80)->nullable(); $table->string('reference')->nullable(); $table->string('status',50)->default('pending'); $table->dateTime('paid_at')->nullable(); $table->timestamps(); $table->unique(['tenant_id','payment_number']); $table->index(['tenant_id','status','paid_at']); });
        Schema::create('tenant_expenses', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->foreignId('vendor_party_id')->nullable()->constrained('parties')->restrictOnDelete(); $table->foreignId('project_id')->nullable()->constrained('projects')->restrictOnDelete(); $table->string('expense_number',80); $table->foreignId('category_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->decimal('amount',18,2); $table->char('currency',3)->default('INR'); $table->date('expense_date'); $table->foreignId('status_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->unique(['tenant_id','expense_number']); $table->index(['tenant_id','expense_date','status_id']); });
        Schema::create('tenant_expense_items', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->foreignId('expense_id')->constrained('tenant_expenses')->restrictOnDelete(); $table->string('description'); $table->decimal('quantity',18,2)->default(1); $table->decimal('unit_price',18,2)->default(0); $table->decimal('tax_amount',18,2)->default(0); $table->decimal('amount',18,2)->default(0); });
        Schema::create('bank_accounts', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->string('owner_type',120); $table->unsignedBigInteger('owner_id'); $table->string('bank_name'); $table->text('account_number_encrypted'); $table->text('routing_number_encrypted')->nullable(); $table->string('ifsc_code',30)->nullable(); $table->boolean('is_primary')->default(false); $table->timestamps(); $table->index(['tenant_id','owner_type','owner_id']); });
    }
    public function down(): void { foreach (['bank_accounts','tenant_expense_items','tenant_expenses','tenant_payments','tenant_invoice_items','tenant_invoices'] as $table) { Schema::dropIfExists($table); } }
};