<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('monitoring_services', function (Blueprint $table) { $table->id(); $table->string('name'); $table->string('code',80)->unique(); $table->string('service_type',80); $table->string('status',50)->default('active'); $table->unsignedInteger('check_interval_seconds')->default(60); $table->timestamps(); });
        Schema::create('monitoring_service_logs', function (Blueprint $table) { $table->id(); $table->foreignId('service_id')->constrained('monitoring_services')->cascadeOnDelete(); $table->string('status',50); $table->unsignedInteger('response_time_ms')->nullable(); $table->text('message')->nullable(); $table->dateTime('checked_at')->index(); });
        Schema::create('tenant_usage_snapshots', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->date('period_start'); $table->date('period_end'); $table->unsignedInteger('users_count')->default(0); $table->unsignedBigInteger('storage_bytes')->default(0); $table->unsignedBigInteger('api_requests')->default(0); $table->unsignedInteger('projects_count')->default(0); $table->unsignedInteger('invoices_count')->default(0); $table->unique(['tenant_id','period_start','period_end'], 'tenant_usage_period_uq'); });
        Schema::create('api_request_logs', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->nullable()->constrained('tenants')->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('method',10); $table->string('path'); $table->unsignedSmallInteger('status_code')->nullable(); $table->unsignedInteger('duration_ms')->nullable(); $table->string('ip_address',45)->nullable(); $table->dateTime('created_at')->nullable(); $table->index(['tenant_id','path','created_at']); });
        Schema::create('queue_job_logs', function (Blueprint $table) { $table->id(); $table->string('queue',100); $table->string('job_name'); $table->string('status',50); $table->unsignedInteger('attempts')->default(0); $table->longText('exception')->nullable(); $table->dateTime('started_at')->nullable(); $table->dateTime('finished_at')->nullable(); });
        Schema::create('scheduler_logs', function (Blueprint $table) { $table->id(); $table->string('command'); $table->string('status',50); $table->longText('output')->nullable(); $table->dateTime('started_at')->nullable(); $table->dateTime('finished_at')->nullable(); });
        Schema::create('security_events', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->nullable()->constrained('tenants')->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('event',120); $table->string('severity',50); $table->string('ip_address',45)->nullable(); $table->json('metadata')->nullable(); $table->dateTime('created_at')->nullable(); $table->index(['tenant_id','event','created_at']); });
        Schema::create('system_incidents', function (Blueprint $table) { $table->id(); $table->string('title'); $table->string('severity',50); $table->string('status',50); $table->dateTime('started_at')->nullable(); $table->dateTime('resolved_at')->nullable(); $table->text('summary')->nullable(); $table->timestamps(); });
        Schema::create('monitoring_alerts', function (Blueprint $table) { $table->id(); $table->string('alertable_type',120); $table->unsignedBigInteger('alertable_id'); $table->string('severity',50); $table->text('message'); $table->string('status',50)->default('open'); $table->dateTime('triggered_at')->nullable(); $table->dateTime('resolved_at')->nullable(); $table->index(['alertable_type','alertable_id']); });
        Schema::create('integration_providers', function (Blueprint $table) { $table->id(); $table->string('name'); $table->string('code',80)->unique(); $table->string('category',80); $table->string('auth_type',80); $table->string('status',50)->default('active'); $table->json('metadata')->nullable(); $table->timestamps(); });
        Schema::create('tenant_integrations', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('provider_id')->constrained('integration_providers')->restrictOnDelete(); $table->string('name'); $table->string('status',50)->default('active'); $table->foreignId('connected_by')->nullable()->constrained('users')->nullOnDelete(); $table->dateTime('connected_at')->nullable(); $table->timestamps(); $table->index(['tenant_id','provider_id','status']); });
        Schema::create('integration_credentials', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_integration_id')->constrained('tenant_integrations')->cascadeOnDelete(); $table->string('key',120); $table->text('encrypted_value'); $table->dateTime('expires_at')->nullable(); $table->unique(['tenant_integration_id','key']); });
        Schema::create('integration_webhooks', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_integration_id')->constrained('tenant_integrations')->cascadeOnDelete(); $table->string('event',120); $table->string('secret_hash')->nullable(); $table->string('status',50)->default('active'); $table->unique(['tenant_integration_id','event']); });
        Schema::create('integration_webhook_logs', function (Blueprint $table) { $table->id(); $table->foreignId('webhook_id')->constrained('integration_webhooks')->cascadeOnDelete(); $table->string('event',120); $table->json('payload')->nullable(); $table->string('status',50); $table->unsignedSmallInteger('response_code')->nullable(); $table->dateTime('received_at')->nullable(); });
        Schema::create('integration_sync_jobs', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_integration_id')->constrained('tenant_integrations')->cascadeOnDelete(); $table->string('sync_type',80); $table->string('direction',50); $table->string('status',50); $table->dateTime('started_at')->nullable(); $table->dateTime('finished_at')->nullable(); });
        Schema::create('integration_field_mappings', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_integration_id')->constrained('tenant_integrations')->cascadeOnDelete(); $table->string('entity_type',100); $table->string('local_field'); $table->string('external_field'); $table->json('transform_rule')->nullable(); });
        Schema::create('integration_rate_limits', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_integration_id')->constrained('tenant_integrations')->cascadeOnDelete(); $table->dateTime('window_start'); $table->dateTime('window_end'); $table->unsignedInteger('limit_count'); $table->unsignedInteger('used_count')->default(0); });
        Schema::create('notifications', function (Blueprint $table) { $table->uuid('id')->primary(); $table->foreignId('tenant_id')->nullable()->constrained('tenants')->cascadeOnDelete(); $table->string('type'); $table->string('notifiable_type'); $table->unsignedBigInteger('notifiable_id'); $table->text('data'); $table->dateTime('read_at')->nullable(); $table->timestamps(); $table->index(['tenant_id','notifiable_type','notifiable_id']); });
        Schema::create('communication_logs', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->nullable()->constrained('tenants')->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('party_id')->nullable()->constrained('parties')->nullOnDelete(); $table->string('channel',50); $table->string('direction',50); $table->string('subject')->nullable(); $table->longText('body')->nullable(); $table->string('provider',80)->nullable(); $table->string('provider_message_id')->nullable(); $table->string('status',50); $table->dateTime('sent_at')->nullable(); $table->dateTime('delivered_at')->nullable(); $table->text('failed_reason')->nullable(); $table->json('metadata')->nullable(); $table->dateTime('created_at')->nullable(); $table->index(['tenant_id','channel','status','created_at']); });
        Schema::create('notification_templates', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->nullable()->constrained('tenants')->cascadeOnDelete(); $table->string('code',120); $table->string('channel',50); $table->string('subject')->nullable(); $table->longText('body'); $table->json('variables')->nullable(); $table->string('status',50)->default('active'); $table->timestamps(); $table->unique(['tenant_id','code','channel']); });
        Schema::create('backup_runs', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->string('backup_type',80); $table->string('status',50); $table->foreignId('file_id')->nullable()->constrained('files')->nullOnDelete(); $table->dateTime('started_at')->nullable(); $table->dateTime('finished_at')->nullable(); $table->longText('error_message')->nullable(); });
        Schema::create('tenant_backup_runs', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('backup_type',80); $table->string('status',50); $table->foreignId('file_id')->nullable()->constrained('files')->nullOnDelete(); $table->dateTime('started_at')->nullable(); $table->dateTime('finished_at')->nullable(); $table->longText('error_message')->nullable(); });
        Schema::create('tenant_restore_requests', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->foreignId('tenant_backup_run_id')->nullable()->constrained('tenant_backup_runs')->restrictOnDelete(); $table->string('status',50)->default('pending'); $table->foreignId('requested_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('approved_by')->nullable()->constrained('platform_users')->nullOnDelete(); $table->dateTime('requested_at')->nullable(); $table->dateTime('approved_at')->nullable(); $table->dateTime('restored_at')->nullable(); $table->text('remarks')->nullable(); });
        Schema::create('platform_tickets', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->string('ticket_number',80)->unique(); $table->foreignId('tenant_id')->nullable()->constrained('tenants')->nullOnDelete(); $table->string('subject'); $table->text('description')->nullable(); $table->string('priority',50)->default('medium'); $table->string('status',50)->default('open'); $table->foreignId('assigned_to')->nullable()->constrained('platform_users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->index(['tenant_id','status','priority']); });
        Schema::create('platform_ticket_comments', function (Blueprint $table) { $table->id(); $table->foreignId('platform_ticket_id')->constrained('platform_tickets')->cascadeOnDelete(); $table->foreignId('platform_user_id')->nullable()->constrained('platform_users')->nullOnDelete(); $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $table->longText('comment'); $table->boolean('is_internal')->default(false); $table->timestamps(); });
        Schema::create('knowledge_base_categories', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('parent_id')->nullable()->constrained('knowledge_base_categories')->nullOnDelete(); $table->string('name'); $table->string('slug')->unique(); $table->string('audience',50)->default('all'); $table->string('status',50)->default('active'); $table->timestamps(); });
        Schema::create('knowledge_base_articles', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('category_id')->nullable()->constrained('knowledge_base_categories')->nullOnDelete(); $table->string('title'); $table->string('slug')->unique(); $table->longText('body'); $table->string('audience',50)->default('all'); $table->string('status',50)->default('draft'); $table->foreignId('created_by')->nullable()->constrained('platform_users')->nullOnDelete(); $table->dateTime('published_at')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('remote_login_sessions', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->restrictOnDelete(); $table->foreignId('platform_user_id')->constrained('platform_users')->restrictOnDelete(); $table->foreignId('impersonated_user_id')->nullable()->constrained('users')->restrictOnDelete(); $table->string('reason'); $table->string('status',50)->default('active'); $table->dateTime('started_at')->nullable(); $table->dateTime('ended_at')->nullable(); $table->string('ip_address',45)->nullable(); });
        Schema::create('tenant_api_tokens', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name'); $table->string('token_hash',128)->unique(); $table->text('encrypted_token_preview')->nullable(); $table->json('abilities')->nullable(); $table->dateTime('last_used_at')->nullable(); $table->dateTime('expires_at')->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->index(['tenant_id','expires_at']); });
    }
    public function down(): void { foreach (['tenant_api_tokens','remote_login_sessions','knowledge_base_articles','knowledge_base_categories','platform_ticket_comments','platform_tickets','tenant_restore_requests','tenant_backup_runs','backup_runs','notification_templates','communication_logs','notifications','integration_rate_limits','integration_field_mappings','integration_sync_jobs','integration_webhook_logs','integration_webhooks','integration_credentials','tenant_integrations','integration_providers','monitoring_alerts','system_incidents','security_events','scheduler_logs','queue_job_logs','api_request_logs','tenant_usage_snapshots','monitoring_service_logs','monitoring_services'] as $table) { Schema::dropIfExists($table); } }
};