<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('holiday_calendars', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name'); $table->text('description')->nullable(); $table->foreignId('country_id')->nullable()->constrained('countries')->nullOnDelete(); $table->foreignId('state_id')->nullable()->constrained('states')->nullOnDelete(); $table->boolean('is_default')->default(false); $table->string('status',50)->default('active'); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->index(['tenant_id','status']); });
        Schema::create('holidays', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('holiday_calendar_id')->constrained('holiday_calendars')->cascadeOnDelete(); $table->string('name'); $table->foreignId('type_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->foreignId('category_id')->nullable()->constrained('tenant_lookups')->nullOnDelete(); $table->date('holiday_date'); $table->date('start_date')->nullable(); $table->date('end_date')->nullable(); $table->decimal('total_days',8,2)->default(1); $table->boolean('is_half_day')->default(false); $table->string('half_day_session',50)->nullable(); $table->boolean('recurring_yearly')->default(false); $table->boolean('optional_holiday')->default(false); $table->boolean('applicable_to_all')->default(true); $table->text('description')->nullable(); $table->string('color',30)->nullable(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->softDeletes(); $table->index(['tenant_id','holiday_date']); });
        Schema::create('holiday_applicabilities', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('holiday_id')->constrained('holidays')->cascadeOnDelete(); $table->enum('applicable_type', ['country','state','city','office','department','team','staff','group']); $table->unsignedBigInteger('applicable_id'); $table->dateTime('created_at')->nullable(); $table->index(['tenant_id','applicable_type','applicable_id'], 'holiday_applicable_idx'); });
        Schema::create('holiday_groups', function (Blueprint $table) { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->string('name'); $table->text('description')->nullable(); $table->string('status',50)->default('active'); $table->timestamps(); $table->unique(['tenant_id','name']); });
        Schema::create('holiday_group_members', function (Blueprint $table) { $table->id(); $table->foreignId('tenant_id')->constrained('tenants')->cascadeOnDelete(); $table->foreignId('holiday_group_id')->constrained('holiday_groups')->cascadeOnDelete(); $table->foreignId('staff_id')->constrained('staff')->cascadeOnDelete(); $table->dateTime('assigned_at')->nullable(); $table->unique(['tenant_id','holiday_group_id','staff_id'], 'holiday_group_staff_unique'); });
    }
    public function down(): void { foreach (['holiday_group_members','holiday_groups','holiday_applicabilities','holidays','holiday_calendars'] as $table) { Schema::dropIfExists($table); } }
};