<?php
namespace App\Http\Controllers;

use App\Support\ApiResponse;
use App\Models\ReportExportJob;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class PlatformDashboardController extends Controller
{
    private function dates(Request $r): array { $d=$r->validate(['date_from'=>'nullable|date','date_to'=>'nullable|date|after_or_equal:date_from']); return [$d['date_from']??null,$d['date_to']??null]; }
    private function range($q,string $column,?string $from,?string $to): void { if($from)$q->whereDate($column,'>=',$from); if($to)$q->whereDate($column,'<=',$to); }
    private function success(mixed $data,string $message='OK'): mixed { return ApiResponse::success($data,$message); }
    private function chartRows(string $code,?string $from,?string $to): array
    {
        if($code==='tenant-growth'){$q=DB::table('tenants')->whereNull('deleted_at')->selectRaw('DATE(created_at) as date, COUNT(*) as count')->groupByRaw('DATE(created_at)');$this->range($q,'created_at',$from,$to);return $q->orderBy('date')->limit(30)->get()->all();}
        if($code==='revenue'||$code==='payment-success-failure-trend'){$q=DB::table('platform_payments')->selectRaw("DATE(paid_at) as date, SUM(CASE WHEN payment_status IN ('success','paid') THEN amount ELSE 0 END) as success, SUM(CASE WHEN payment_status NOT IN ('success','paid') THEN amount ELSE 0 END) as failed, SUM(CASE WHEN payment_status IN ('success','paid') THEN amount ELSE 0 END) as revenue")->whereNotNull('paid_at')->groupByRaw('DATE(paid_at)');$this->range($q,'paid_at',$from,$to);return $q->orderBy('date')->limit(30)->get()->all();}
        if(in_array($code,['usage','api-usage-trend','storage-usage-trend'],true)){$q=DB::table('tenant_usage_snapshots')->selectRaw('period_end as date, SUM(api_requests) as api_requests, SUM(storage_bytes) as storage_bytes')->groupBy('period_end');$this->range($q,'period_end',$from,$to);return $q->orderBy('date')->limit(30)->get()->all();}
        if($code==='plan-distribution')return DB::table('subscriptions as s')->leftJoin('plans as p','p.id','=','s.plan_id')->select('p.name as plan_name',DB::raw('COUNT(*) as count'),DB::raw('SUM(s.payable_amount) as revenue'))->groupBy('p.id','p.name')->get()->all();
        if($code==='subscription-status')return DB::table('subscriptions')->select('status',DB::raw('COUNT(*) as count'))->groupBy('status')->get()->all();
        return [];
    }
    public function summary(Request $r): mixed
    {
        [$from,$to]=$this->dates($r);$tenant=DB::table('tenants')->whereNull('deleted_at');$this->range($tenant,'created_at',$from,$to);$mrr=DB::table('subscriptions')->whereIn('status',['active','trial'])->sum('payable_amount');$over=DB::table('platform_invoices')->whereNull('deleted_at')->where('balance_amount','>',0)->whereDate('due_date','<',today());
        return $this->success(['tenants'=>['total'=>$tenant->count(),'active'=>(clone $tenant)->where('status','active')->count(),'trial'=>(clone $tenant)->where('status','trial')->count(),'suspended'=>(clone $tenant)->where('status','suspended')->count(),'expired'=>(clone $tenant)->where('status','expired')->count(),'new_today'=>DB::table('tenants')->whereNull('deleted_at')->whereDate('created_at',today())->count(),'new_this_week'=>DB::table('tenants')->whereNull('deleted_at')->whereBetween('created_at',[now()->startOfWeek(),now()->endOfWeek()])->count(),'new_this_month'=>DB::table('tenants')->whereNull('deleted_at')->whereBetween('created_at',[now()->startOfMonth(),now()->endOfMonth()])->count()],'revenue'=>['mrr'=>$mrr,'arr'=>$mrr*12,'collected_today'=>DB::table('platform_payments')->whereIn('payment_status',['success','paid'])->whereDate('paid_at',today())->sum('amount'),'collected_this_month'=>DB::table('platform_payments')->whereIn('payment_status',['success','paid'])->whereBetween('paid_at',[now()->startOfMonth(),now()->endOfMonth()])->sum('amount'),'currency'=>DB::table('subscriptions')->whereIn('status',['active','trial'])->value('currency')??'INR'],'billing'=>['overdue_invoice_count'=>$over->count(),'overdue_balance'=>$over->sum('balance_amount'),'failed_payment_count'=>DB::table('platform_payments')->whereNotIn('payment_status',['success','paid'])->count()],'operations'=>['open_incidents'=>DB::table('monitoring_alerts')->where('status','open')->count(),'critical_security_events'=>DB::table('security_events')->whereIn('severity',['critical','high'])->count(),'failed_queue_jobs'=>DB::table('tenant_import_export_jobs')->where('status','failed')->count(),'failed_scheduler_runs'=>0]],'Platform summary fetched.');
    }
    public function charts(Request $r): mixed { [$from,$to]=$this->dates($r);return $this->success(['tenant_growth'=>$this->chartRows('tenant-growth',$from,$to),'revenue'=>$this->chartRows('revenue',$from,$to),'plan_distribution'=>$this->chartRows('plan-distribution',$from,$to),'subscription_status'=>$this->chartRows('subscription-status',$from,$to),'tenant_status'=>$this->chartRows('subscription-status',$from,$to),'usage'=>$this->chartRows('usage',$from,$to)],'Dashboard charts fetched.'); }
    public function chart(Request $r,string $chart): mixed { [$from,$to]=$this->dates($r);$allowed=['tenant-growth','revenue','api-usage-trend','storage-usage-trend','usage','payment-success-failure-trend','plan-distribution','subscription-status'];if(!in_array($chart,$allowed,true))return ApiResponse::businessError('Dashboard chart not found.','DASHBOARD_CHART_NOT_FOUND',404);return $this->success($this->chartRows($chart,$from,$to),'Dashboard chart fetched.'); }
    private function recentTenants(): mixed { return DB::table('tenants as t')->leftJoin('users as u',function($j){$j->on('u.tenant_id','=','t.id')->where('u.account_type','owner');})->leftJoin('subscriptions as s','s.tenant_id','=','t.id')->leftJoin('plans as p','p.id','=','s.plan_id')->whereNull('t.deleted_at')->select('t.uuid','t.organization_name','t.slug','u.display_name as owner_name','u.email as owner_email','p.name as plan_name','s.status as subscription_status','t.status','t.created_at')->latest('t.id')->limit(5)->get(); }
    private function recentPayments(): mixed { return DB::table('platform_payments as p')->join('tenants as t','t.id','=','p.tenant_id')->select('p.uuid','p.payment_number','t.organization_name','t.organization_name as tenant_name','p.amount','p.currency','p.gateway','p.payment_status','p.paid_at')->latest('p.id')->limit(5)->get(); }
    private function overdueInvoices(): mixed { return DB::table('platform_invoices as i')->join('tenants as t','t.id','=','i.tenant_id')->whereNull('i.deleted_at')->where('i.balance_amount','>',0)->whereDate('i.due_date','<',today())->select('i.uuid','i.invoice_number','t.organization_name','t.organization_name as tenant_name','i.balance_amount','i.currency','i.due_date','i.status')->latest('i.id')->limit(5)->get(); }
    public function recent(): mixed { return $this->success(['recent_tenants'=>$this->recentTenants(),'recent_payments'=>$this->recentPayments(),'overdue_invoices'=>$this->overdueInvoices()],'Recent dashboard data fetched.'); }
    public function recentTenantsEndpoint(): mixed { return $this->success($this->recentTenants(),'Recent tenants fetched.'); }
    public function recentPaymentsEndpoint(): mixed { return $this->success($this->recentPayments(),'Recent payments fetched.'); }
    public function overdueInvoicesEndpoint(): mixed { return $this->success($this->overdueInvoices(),'Overdue invoices fetched.'); }
    public function alerts(): mixed { $alerts=DB::table('monitoring_alerts')->where('status','open')->latest('id')->limit(5)->get();$events=DB::table('security_events as e')->leftJoin('tenants as t','t.id','=','e.tenant_id')->leftJoin('users as u','u.id','=','e.user_id')->select('e.*','t.organization_name as tenant_name','u.display_name as actor')->latest('e.created_at')->limit(5)->get();return $this->success(['alerts'=>$alerts,'active_alerts'=>$alerts,'security_events'=>$events],'Dashboard alerts fetched.'); }
    public function activeAlerts(): mixed { return $this->success(DB::table('monitoring_alerts')->where('status','open')->latest('id')->limit(5)->get(),'Active alerts fetched.'); }
    public function securityEvents(Request $r): mixed { $q=DB::table('security_events as e')->leftJoin('tenants as t','t.id','=','e.tenant_id')->leftJoin('users as u','u.id','=','e.user_id')->select('e.id','e.event','e.severity','e.ip_address','e.created_at','t.organization_name as tenant_name','u.display_name as actor');if($r->filled('severity'))$q->where('e.severity',$r->input('severity'));if($r->filled('event'))$q->where('e.event',$r->input('event'));return $this->success($q->latest('e.created_at')->limit(5)->get(),'Security events fetched.'); }
    public function export(Request $r): mixed { $r->validate(['format'=>'nullable|in:csv,xlsx,json','sections'=>'nullable|array','date_from'=>'nullable|date','date_to'=>'nullable|date|after_or_equal:date_from']);$job=ReportExportJob::create(['uuid'=>(string)Str::uuid(),'report_code'=>'dashboard','format'=>$r->input('format','csv'),'filters'=>$r->all(),'status'=>'queued','created_by'=>$r->user()?->id]);return $this->success(['export'=>$job],'Dashboard export queued.',201); }
}
