<?php
namespace App\Http\Controllers;
use App\Models\PlatformTicket;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class PlatformSupportTicketController extends Controller
{
 private function find(string $uuid):PlatformTicket{$x=PlatformTicket::withTrashed()->where('uuid',$uuid)->first();if(!$x)abort(404);return $x;}
 private function payload(PlatformTicket $t,bool $detail=false):array{$a=$t->load(['tenant','assignedTo'])->toArray();$a['tenant_summary']=$t->tenant?->only(['uuid','name','display_name','slug']);$a['assigned_to_summary']=$t->assignedTo?->only(['uuid','display_name','email']);if($detail){$a['comments']=$t->comments()->with(['platformUser','user'])->latest()->get()->map(fn($c)=>['id'=>$c->id,'comment'=>$c->comment,'is_internal'=>(bool)$c->is_internal,'platform_user'=>$c->platformUser?->only(['uuid','display_name','email']),'user'=>$c->user?->only(['uuid','display_name','email']),'created_at'=>$c->created_at]);$a['attachments']=$t->attachments()->with('file')->get();$a['audit']=DB::table('activity_logs')->where('subject_type',PlatformTicket::class)->where('subject_id',$t->id)->latest()->limit(50)->get();}return $a;}
 public function index(Request $r){$q=PlatformTicket::with(['tenant','assignedTo'])->whereNull('deleted_at');foreach(['status','priority','category'] as $f)if($r->filled($f))$q->where($f,$r->input($f));if($r->filled('tenant_uuid'))$q->whereHas('tenant',fn($x)=>$x->where('uuid',$r->input('tenant_uuid')));if($r->filled('assigned_to_uuid'))$q->whereHas('assignedTo',fn($x)=>$x->where('uuid',$r->input('assigned_to_uuid')));$p=$q->latest()->paginate(min(max((int)$r->input('per_page',25),1),100))->withQueryString();$rows=collect($p->items())->map(fn($x)=>$this->payload($x))->all();return ApiResponse::success($rows,'Support tickets fetched.',200,['current_page'=>$p->currentPage(),'per_page'=>$p->perPage(),'total'=>$p->total(),'last_page'=>$p->lastPage()]);}
 public function show(string $uuid){return ApiResponse::success(['ticket'=>$this->payload($this->find($uuid),true)],'Support ticket fetched.');}
 public function store(Request $r){$d=$r->validate(['tenant_uuid'=>'nullable|uuid','subject'=>'required|string|max:255','description'=>'nullable|string','priority'=>'sometimes|in:low,medium,high,urgent','category'=>'nullable|string|max:100','source'=>'nullable|string|max:80','assigned_to_uuid'=>'nullable|uuid']);$tenant=$d['tenant_uuid']??null?DB::table('tenants')->where('uuid',$d['tenant_uuid'])->first():null;if(isset($d['tenant_uuid'])&&!$tenant)abort(404);$assignee=$d['assigned_to_uuid']??null?DB::table('platform_users')->where('uuid',$d['assigned_to_uuid'])->first():null;if(isset($d['assigned_to_uuid'])&&!$assignee)abort(404);$t=PlatformTicket::create(['uuid'=>(string)Str::uuid(),'ticket_number'=>'SUP-'.now()->format('YmdHis').'-'.Str::upper(Str::random(4)),'tenant_id'=>$tenant?->id,'subject'=>$d['subject'],'description'=>$d['description']??null,'priority'=>$d['priority']??'medium','status'=>'open','assigned_to'=>$assignee?->id,'category'=>$d['category']??null,'source'=>$d['source']??'platform','opened_at'=>now()]);return ApiResponse::success(['ticket'=>$this->payload($t,true)],'Support ticket created.',201);}
 public function update(Request $r,string $uuid){$t=$this->find($uuid);$d=$r->validate(['subject'=>'sometimes|string|max:255','description'=>'nullable|string','priority'=>'sometimes|in:low,medium,high,urgent','category'=>'nullable|string|max:100','status'=>'sometimes|in:open,in_progress,pending,resolved,closed,reopened']);$t->update($d);return $this->show($uuid);}
 public function assign(Request $r,string $uuid){$t=$this->find($uuid);$d=$r->validate(['assigned_to_uuid'=>'nullable|uuid','audit_reason'=>'nullable|string']);$id=null;if($d['assigned_to_uuid']??null){$id=DB::table('platform_users')->where('uuid',$d['assigned_to_uuid'])->value('id');if(!$id)abort(404);} $t->update(['assigned_to'=>$id]);return $this->show($uuid);}
 public function comment(Request $r,string $uuid){$t=$this->find($uuid);$d=$r->validate(['comment'=>'required|string','is_internal'=>'sometimes|boolean']);$id=DB::table('platform_ticket_comments')->insertGetId(['platform_ticket_id'=>$t->id,'platform_user_id'=>auth()->id(),'comment'=>$d['comment'],'is_internal'=>$d['is_internal']??false,'created_at'=>now(),'updated_at'=>now()]);return ApiResponse::success(['comment'=>DB::table('platform_ticket_comments')->where('id',$id)->first()],'Comment added.',201);}
 public function attach(Request $r,string $uuid){$t=$this->find($uuid);$d=$r->validate(['file_uuid'=>'required|uuid']);$file=DB::table('files')->where('uuid',$d['file_uuid'])->first();if(!$file)abort(404);DB::table('platform_ticket_attachments')->updateOrInsert(['platform_ticket_id'=>$t->id,'file_id'=>$file->id],['created_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);return $this->show($uuid);}
 public function close(Request $r,string $uuid){$t=$this->find($uuid);$r->validate(['notes'=>'nullable|string']);$t->update(['status'=>'closed','closed_at'=>now()]);return $this->show($uuid);}
 public function reopen(string $uuid){$t=$this->find($uuid);$t->update(['status'=>'open','closed_at'=>null]);return $this->show($uuid);}
 public function export(Request $r){return ApiResponse::success(['status'=>'queued','filters'=>$r->all()],'Support ticket export queued.',202);}
}
