<?php

namespace App\Http\Controllers;

use App\Models\AddonPlan;
use App\Models\Coupon;
use App\Models\CouponRedemption;
use App\Models\Plan;
use App\Models\PlatformInvoice;
use App\Models\Subscription;
use App\Models\SubscriptionAddon;
use App\Models\SubscriptionRenewal;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class PlatformSubscriptionController extends Controller
{
    public function index(Request $request): mixed
    {
        $query = Subscription::query()->with(['tenant', 'plan', 'addonAssignments.addonPlan'])
            ->when($request->filled('search'), fn ($q) => $q->where('subscription_number', 'like', '%'.$request->string('search').'%')->orWhereHas('tenant', fn ($tenant) => $tenant->where('organization_name', 'like', '%'.$request->string('search').'%')))
            ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))->latest('created_at');
        $paginator = $query->paginate($request->integer('per_page', 10))->withQueryString();
        return ApiResponse::success($paginator->items(), 'Platform subscriptions fetched.', 200, ['current_page' => $paginator->currentPage(), 'per_page' => $paginator->perPage(), 'total' => $paginator->total(), 'last_page' => $paginator->lastPage()]);
    }

    public function store(Request $request): mixed
    {
        $data = $request->validate(['tenant_uuid' => ['required', 'uuid', 'exists:tenants,uuid'], 'plan_uuid' => ['required', 'uuid', 'exists:plans,uuid'], 'billing_cycle' => ['nullable', 'string', 'max:50'], 'renewal_type' => ['nullable', 'string', 'max:50'], 'starts_at' => ['nullable', 'date'], 'trial_ends_at' => ['nullable', 'date'], 'auto_renew' => ['nullable', 'boolean'], 'addon_uuids' => ['nullable', 'array'], 'addon_uuids.*' => ['uuid']]);
        return DB::transaction(function () use ($request, $data) {
            $tenant = \App\Models\Tenant::where('uuid', $data['tenant_uuid'])->firstOrFail(); $plan = Plan::where('uuid', $data['plan_uuid'])->firstOrFail(); $starts = isset($data['starts_at']) ? now()->parse($data['starts_at']) : now(); $trialEnds = isset($data['trial_ends_at']) ? now()->parse($data['trial_ends_at']) : ($plan->trial_days ? $starts->copy()->addDays($plan->trial_days) : null);
            $subscription = Subscription::create(['uuid' => (string) Str::uuid(), 'subscription_number' => 'SUB-'.strtoupper(Str::random(10)), 'tenant_id' => $tenant->id, 'plan_id' => $plan->id, 'billing_cycle' => $data['billing_cycle'] ?? $plan->billing_cycle, 'renewal_type' => $data['renewal_type'] ?? 'manual', 'status' => $trialEnds ? 'trial' : 'active', 'starts_at' => $starts, 'trial_starts_at' => $trialEnds ? $starts : null, 'trial_ends_at' => $trialEnds, 'next_billing_at' => $trialEnds ?? $starts, 'base_amount' => $plan->base_price, 'payable_amount' => $plan->base_price, 'currency' => $plan->currency, 'auto_renew' => $data['auto_renew'] ?? false, 'created_by' => $request->user()->id, 'updated_by' => $request->user()->id]);
            $this->syncAddons($subscription, $data['addon_uuids'] ?? []); return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Platform subscription created successfully.', 201);
        });
    }
    public function show(string $uuid): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); return ApiResponse::success(['subscription' => $this->present($subscription)], 'Platform subscription fetched.'); }
    public function update(Request $request, string $uuid): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); $subscription->update($request->validate(['billing_cycle' => ['sometimes', 'string', 'max:50'], 'renewal_type' => ['sometimes', 'string', 'max:50'], 'auto_renew' => ['sometimes', 'boolean'], 'notes' => ['nullable', 'string']])); return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Platform subscription updated successfully.'); }
    public function export(): mixed { return ApiResponse::success(['export' => ['job_id' => (string) Str::uuid(), 'status' => 'queued', 'format' => 'csv']], 'Subscription export queued.', 202); }

    public function lifecycle(Request $request, string $uuid, string $action): mixed
    {
        $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND');
        return DB::transaction(function () use ($request, $subscription, $action) {
            $data = $request->validate(['plan_uuid' => ['nullable', 'uuid'], 'reason' => ['nullable', 'string', 'max:1000'], 'immediate' => ['nullable', 'boolean'], 'billing_cycle' => ['nullable', 'string', 'max:50']]);
            if (in_array($action, ['upgrade', 'downgrade'], true)) { $plan = Plan::where('uuid', $data['plan_uuid'] ?? '')->first(); if (! $plan) return ApiResponse::error('Target plan not found.', 404, null, 'PLAN_NOT_FOUND'); $subscription->update(['plan_id' => $plan->id, 'base_amount' => $plan->base_price, 'payable_amount' => $plan->base_price, 'currency' => $plan->currency, 'current_version' => $subscription->current_version + 1]); }
            elseif ($action === 'renew') { $old = $subscription->expires_at; $new = ($old && $old->isFuture() ? $old : now())->addMonths($this->cycleMonths($data['billing_cycle'] ?? $subscription->billing_cycle)); $subscription->update(['status' => 'active', 'expires_at' => $new, 'next_billing_at' => $new, 'last_renewed_at' => now()]); SubscriptionRenewal::create(['subscription_id' => $subscription->id, 'old_expires_at' => $old, 'new_expires_at' => $new, 'amount' => $subscription->payable_amount, 'status' => 'completed', 'renewed_at' => now()]); }
            elseif ($action === 'pause') $subscription->update(['status' => 'paused', 'paused_at' => now()]); elseif ($action === 'resume') $subscription->update(['status' => 'active', 'resumed_at' => now()]); elseif ($action === 'cancel') $subscription->update(['status' => 'cancelled', 'cancelled_at' => now(), 'cancellation_reason' => $data['reason'] ?? null, 'expires_at' => ($data['immediate'] ?? false) ? now() : $subscription->expires_at]);
            return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Subscription '.$action.' completed.');
        });
    }

    public function addAddon(Request $request, string $uuid): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); $data = $request->validate(['addon_id' => ['required'], 'quantity' => ['nullable', 'integer', 'min:1']]); $addon = AddonPlan::where('uuid', $data['addon_id'])->orWhere('id', $data['addon_id'])->first(); if (! $addon) return ApiResponse::error('Add-on not found.', 404, null, 'ADDON_NOT_FOUND'); SubscriptionAddon::updateOrCreate(['subscription_id' => $subscription->id, 'addon_plan_id' => $addon->id], ['quantity' => $data['quantity'] ?? 1, 'unit_price' => $addon->price, 'starts_at' => now(), 'status' => 'active']); $this->recalculate($subscription->fresh()); return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Subscription add-on added.'); }
    public function updateAddon(Request $request, string $uuid, string $addonId): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); $assignment = $subscription->addonAssignments()->where('id', $addonId)->first(); if (! $assignment) return ApiResponse::error('Subscription add-on not found.', 404, null, 'ADDON_NOT_FOUND'); $assignment->update($request->validate(['quantity' => ['sometimes', 'integer', 'min:1'], 'status' => ['sometimes', 'string', 'max:50'], 'ends_at' => ['nullable', 'date']])); $this->recalculate($subscription->fresh()); return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Subscription add-on updated.'); }
    public function removeAddon(string $uuid, string $addonId): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); $assignment = $subscription->addonAssignments()->where('id', $addonId)->first(); if (! $assignment) return ApiResponse::error('Subscription add-on not found.', 404, null, 'ADDON_NOT_FOUND'); $assignment->delete(); $this->recalculate($subscription->fresh()); return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Subscription add-on removed.'); }
    public function applyCoupon(Request $request, string $uuid): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); $data = $request->validate(['code' => ['required', 'string', 'max:80']]); $coupon = Coupon::where('code', strtoupper($data['code']))->where('status', 'active')->first(); if (! $coupon) return ApiResponse::error('Coupon is not available.', 422, null, 'COUPON_INVALID'); if ($subscription->redemptions()->where('coupon_id', $coupon->id)->exists()) return ApiResponse::error('Coupon is already applied.', 422, null, 'COUPON_ALREADY_APPLIED'); $amount = in_array($coupon->discount_type, ['percent', 'percentage'], true) ? (float) $subscription->base_amount * (float) $coupon->discount_value / 100 : (float) $coupon->discount_value; CouponRedemption::create(['coupon_id' => $coupon->id, 'tenant_id' => $subscription->tenant_id, 'subscription_id' => $subscription->id, 'discount_amount' => min($amount, (float) $subscription->base_amount), 'redeemed_at' => now()]); $this->recalculate($subscription->fresh()); return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Coupon applied to subscription.'); }
    public function removeCoupon(string $uuid, string $couponUuid): mixed { $subscription = $this->find($uuid); $coupon = Coupon::where('uuid', $couponUuid)->first(); if (! $subscription || ! $coupon) return ApiResponse::error('Subscription or coupon not found.', 404, null, 'RESOURCE_NOT_FOUND'); if (! $subscription->redemptions()->where('coupon_id', $coupon->id)->delete()) return ApiResponse::error('Applied coupon not found.', 404, null, 'COUPON_NOT_FOUND'); $this->recalculate($subscription->fresh()); return ApiResponse::success(['subscription' => $this->present($subscription->fresh())], 'Coupon removed from subscription.'); }
    public function usage(string $uuid): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); return ApiResponse::success(['usage' => $subscription->usage()->with('feature')->latest('period_start')->get()], 'Subscription usage fetched.'); }
    public function history(string $uuid): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); return ApiResponse::success(['versions' => $subscription->versions()->with('plan')->latest('created_at')->get(), 'renewals' => $subscription->renewals()->latest('renewed_at')->get()], 'Subscription history fetched.'); }
    public function invoice(string $uuid): mixed { $subscription = $this->find($uuid); if (! $subscription) return ApiResponse::error('Platform subscription not found.', 404, null, 'SUBSCRIPTION_NOT_FOUND'); $invoice = $subscription->platformInvoices()->latest('id')->first(); if (! $invoice) $invoice = PlatformInvoice::create(['uuid' => (string) Str::uuid(), 'invoice_number' => 'INV-'.strtoupper(Str::random(10)), 'tenant_id' => $subscription->tenant_id, 'subscription_id' => $subscription->id, 'invoice_date' => now()->toDateString(), 'due_date' => now()->toDateString(), 'subtotal' => $subscription->base_amount, 'discount_amount' => $subscription->discount_amount, 'taxable_amount' => $subscription->taxable_amount, 'tax_amount' => $subscription->tax_amount, 'total_amount' => $subscription->payable_amount, 'currency' => $subscription->currency, 'status' => 'draft']); return ApiResponse::success(['invoice' => $invoice->load(['tenant', 'subscription', 'items', 'payments'])], 'Subscription invoice fetched.'); }
    private function find(string $uuid): ?Subscription { return Subscription::where('uuid', $uuid)->first(); }
    private function present(Subscription $subscription): Subscription { return $subscription->load(['tenant', 'plan.features', 'addonAssignments.addonPlan', 'platformInvoices.items', 'platformPayments', 'redemptions.coupon', 'usage.feature', 'versions.plan', 'renewals']); }
    private function syncAddons(Subscription $subscription, array $uuids): void { foreach (AddonPlan::whereIn('uuid', $uuids)->get() as $addon) SubscriptionAddon::create(['subscription_id' => $subscription->id, 'addon_plan_id' => $addon->id, 'quantity' => 1, 'unit_price' => $addon->price, 'starts_at' => now(), 'status' => 'active']); $this->recalculate($subscription); }
    private function recalculate(Subscription $subscription): void { $addonAmount = $subscription->addonAssignments()->where('status', 'active')->get()->sum(fn ($a) => (float) $a->unit_price * $a->quantity); $discount = $subscription->redemptions()->sum('discount_amount'); $subscription->update(['addon_amount' => $addonAmount, 'discount_amount' => $discount, 'taxable_amount' => max(0, (float) $subscription->base_amount + $addonAmount - $discount), 'payable_amount' => max(0, (float) $subscription->base_amount + $addonAmount - $discount)]); }
    private function cycleMonths(string $cycle): int { return match ($cycle) { 'quarterly' => 3, 'half-yearly' => 6, 'yearly' => 12, default => 1 }; }
}
