<?php

namespace App\Http\Controllers;

use App\Models\PlatformInvoice;
use App\Models\PlatformInvoiceItem;
use App\Models\PlatformPayment;
use App\Models\Subscription;
use App\Models\Tenant;
use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class PlatformInvoiceController extends Controller
{
    public function index(Request $request): mixed
    {
        $query = PlatformInvoice::query()->with(['tenant', 'subscription.plan', 'payments'])
            ->when($request->filled('search'), fn ($q) => $q->where('invoice_number', 'like', '%'.$request->string('search').'%')->orWhereHas('tenant', fn ($tenant) => $tenant->where('organization_name', 'like', '%'.$request->string('search').'%')))
            ->when($request->filled('status'), fn ($q) => $q->where('status', $request->string('status')))
            ->when($request->filled('tenant_uuid'), fn ($q) => $q->whereHas('tenant', fn ($tenant) => $tenant->where('uuid', $request->string('tenant_uuid'))))
            ->latest('invoice_date');
        $paginator = $query->paginate($request->integer('per_page', 10))->withQueryString();
        return ApiResponse::success($paginator->items(), 'Platform invoices fetched.', 200, ['current_page' => $paginator->currentPage(), 'per_page' => $paginator->perPage(), 'total' => $paginator->total(), 'last_page' => $paginator->lastPage()]);
    }

    public function store(Request $request): mixed
    {
        $data = $request->validate(['tenant_uuid' => ['required', 'uuid', 'exists:tenants,uuid'], 'subscription_uuid' => ['nullable', 'uuid', 'exists:subscriptions,uuid'], 'invoice_date' => ['required', 'date'], 'due_date' => ['nullable', 'date'], 'currency' => ['nullable', 'string', 'size:3'], 'discount_amount' => ['nullable', 'numeric', 'min:0'], 'tax_amount' => ['nullable', 'numeric', 'min:0'], 'status' => ['nullable', 'string', 'max:50'], 'items' => ['required', 'array', 'min:1'], 'items.*.item_type' => ['required', 'string', 'max:80'], 'items.*.description' => ['required', 'string', 'max:255'], 'items.*.quantity' => ['required', 'numeric', 'min:0.01'], 'items.*.unit_price' => ['required', 'numeric', 'min:0'], 'items.*.metadata' => ['nullable', 'array']]);
        return DB::transaction(function () use ($data) {
            $tenant = Tenant::where('uuid', $data['tenant_uuid'])->firstOrFail(); $subscription = ! empty($data['subscription_uuid']) ? Subscription::where('uuid', $data['subscription_uuid'])->firstOrFail() : null;
            $subtotal = collect($data['items'])->sum(fn ($item) => (float) $item['quantity'] * (float) $item['unit_price']); $discount = (float) ($data['discount_amount'] ?? 0); $tax = (float) ($data['tax_amount'] ?? 0); $total = max(0, $subtotal - $discount + $tax);
            $invoice = PlatformInvoice::create(['uuid' => (string) Str::uuid(), 'invoice_number' => 'INV-'.strtoupper(Str::random(10)), 'tenant_id' => $tenant->id, 'subscription_id' => $subscription?->id, 'invoice_date' => $data['invoice_date'], 'due_date' => $data['due_date'] ?? null, 'subtotal' => $subtotal, 'discount_amount' => $discount, 'taxable_amount' => max(0, $subtotal - $discount), 'tax_amount' => $tax, 'total_amount' => $total, 'paid_amount' => 0, 'balance_amount' => $total, 'currency' => strtoupper($data['currency'] ?? 'INR'), 'status' => $data['status'] ?? 'draft']);
            foreach ($data['items'] as $item) PlatformInvoiceItem::create(['platform_invoice_id' => $invoice->id, 'item_type' => $item['item_type'], 'description' => $item['description'], 'quantity' => $item['quantity'], 'unit_price' => $item['unit_price'], 'amount' => (float) $item['quantity'] * (float) $item['unit_price'], 'metadata' => $item['metadata'] ?? null]);
            return ApiResponse::success(['invoice' => $this->present($invoice->fresh())], 'Platform invoice created successfully.', 201);
        });
    }

    public function show(string $uuid): mixed { $invoice = $this->find($uuid); if (! $invoice) return ApiResponse::error('Platform invoice not found.', 404, null, 'INVOICE_NOT_FOUND'); return ApiResponse::success(['invoice' => $this->present($invoice)], 'Platform invoice fetched.'); }
    public function update(Request $request, string $uuid): mixed { $invoice = $this->find($uuid); if (! $invoice) return ApiResponse::error('Platform invoice not found.', 404, null, 'INVOICE_NOT_FOUND'); if (in_array($invoice->status, ['paid', 'voided', 'cancelled'], true)) return ApiResponse::error('Finalized invoices cannot be edited.', 422, null, 'INVOICE_FINALIZED'); $data = $request->validate(['invoice_date' => ['sometimes', 'date'], 'due_date' => ['nullable', 'date'], 'discount_amount' => ['sometimes', 'numeric', 'min:0'], 'tax_amount' => ['sometimes', 'numeric', 'min:0'], 'status' => ['sometimes', 'string', 'max:50'], 'items' => ['sometimes', 'array'], 'items.*.item_type' => ['required_with:items', 'string', 'max:80'], 'items.*.description' => ['required_with:items', 'string', 'max:255'], 'items.*.quantity' => ['required_with:items', 'numeric', 'min:0.01'], 'items.*.unit_price' => ['required_with:items', 'numeric', 'min:0']]); return DB::transaction(function () use ($invoice, $data) { if (isset($data['items'])) { $invoice->items()->delete(); foreach ($data['items'] as $item) PlatformInvoiceItem::create(['platform_invoice_id' => $invoice->id, 'item_type' => $item['item_type'], 'description' => $item['description'], 'quantity' => $item['quantity'], 'unit_price' => $item['unit_price'], 'amount' => (float) $item['quantity'] * (float) $item['unit_price']]); $data['subtotal'] = collect($data['items'])->sum(fn ($item) => (float) $item['quantity'] * (float) $item['unit_price']); } $discount = (float) ($data['discount_amount'] ?? $invoice->discount_amount); $tax = (float) ($data['tax_amount'] ?? $invoice->tax_amount); if (array_key_exists('items', $data) || array_key_exists('discount_amount', $data) || array_key_exists('tax_amount', $data)) { $data['taxable_amount'] = max(0, (float) ($data['subtotal'] ?? $invoice->subtotal) - $discount); $data['total_amount'] = max(0, $data['taxable_amount'] + $tax); $data['balance_amount'] = max(0, $data['total_amount'] - (float) $invoice->paid_amount); } $invoice->update(collect($data)->except('items')->all()); return ApiResponse::success(['invoice' => $this->present($invoice->fresh())], 'Platform invoice updated successfully.'); }); }
    public function destroy(string $uuid): mixed { $invoice = $this->find($uuid); if (! $invoice) return ApiResponse::error('Platform invoice not found.', 404, null, 'INVOICE_NOT_FOUND'); if ($invoice->payments()->exists() || in_array($invoice->status, ['paid', 'voided'], true)) return ApiResponse::error('Finalized or paid invoices cannot be deleted.', 422, null, 'INVOICE_NOT_DELETABLE'); $invoice->delete(); return ApiResponse::success(['deleted' => true], 'Platform invoice deleted successfully.'); }
    public function export(): mixed { return ApiResponse::success(['export' => ['job_id' => (string) Str::uuid(), 'status' => 'queued', 'format' => 'csv']], 'Invoice export queued.', 202); }
    public function send(Request $request, string $uuid): mixed { $invoice = $this->find($uuid); if (! $invoice) return ApiResponse::error('Platform invoice not found.', 404, null, 'INVOICE_NOT_FOUND'); if ($invoice->status === 'cancelled') return ApiResponse::error('Cancelled invoices cannot be sent.', 422, null, 'INVOICE_NOT_SENDABLE'); $invoice->update(['status' => $invoice->status === 'draft' ? 'sent' : $invoice->status]); return ApiResponse::success(['invoice' => $this->present($invoice->fresh()), 'delivery' => ['status' => 'sent', 'recipient' => $request->input('to') ?: $invoice->tenant?->owner?->email]], 'Invoice sent successfully.'); }
    public function pdf(string $uuid): mixed { $invoice = $this->find($uuid); if (! $invoice) return ApiResponse::error('Platform invoice not found.', 404, null, 'INVOICE_NOT_FOUND'); $invoice = $this->present($invoice); return response()->streamDownload(function () use ($invoice) { echo "Invoice {$invoice->invoice_number}\nTenant: ".($invoice->tenant?->organization_name ?? '')."\nTotal: {$invoice->total_amount} {$invoice->currency}\nStatus: {$invoice->status}\n"; }, $invoice->invoice_number.'.pdf', ['Content-Type' => 'application/pdf']); }
    public function payment(Request $request, string $uuid): mixed { $invoice = $this->find($uuid); if (! $invoice) return ApiResponse::error('Platform invoice not found.', 404, null, 'INVOICE_NOT_FOUND'); if (in_array($invoice->status, ['cancelled', 'voided'], true)) return ApiResponse::error('Invoice is not payable.', 422, null, 'INVOICE_NOT_PAYABLE'); $data = $request->validate(['amount' => ['required', 'numeric', 'min:0.01'], 'currency' => ['nullable', 'string', 'size:3'], 'gateway' => ['nullable', 'string', 'max:80'], 'gateway_payment_id' => ['nullable', 'string', 'max:255'], 'payment_method' => ['nullable', 'string', 'max:80'], 'payment_status' => ['required', 'string', 'max:50'], 'paid_at' => ['nullable', 'date'], 'raw_response' => ['nullable', 'array']]); if ((float) $data['amount'] > (float) $invoice->balance_amount) return ApiResponse::error('Payment exceeds the invoice balance.', 422, null, 'OVERPAYMENT'); if (! empty($data['gateway_payment_id']) && PlatformPayment::where('gateway_payment_id', $data['gateway_payment_id'])->exists()) return ApiResponse::error('Payment reference has already been recorded.', 422, null, 'PAYMENT_DUPLICATE'); $payment = PlatformPayment::create(['uuid' => (string) Str::uuid(), 'payment_number' => 'PAY-'.strtoupper(Str::random(10)), 'tenant_id' => $invoice->tenant_id, 'platform_invoice_id' => $invoice->id, 'subscription_id' => $invoice->subscription_id, 'gateway' => $data['gateway'] ?? null, 'gateway_payment_id' => $data['gateway_payment_id'] ?? null, 'payment_method' => $data['payment_method'] ?? null, 'amount' => $data['amount'], 'currency' => $data['currency'] ?? $invoice->currency, 'payment_status' => $data['payment_status'], 'paid_at' => $data['paid_at'] ?? now(), 'raw_response' => $data['raw_response'] ?? null]); if ($data['payment_status'] === 'success') { $paid = (float) $invoice->paid_amount + (float) $data['amount']; $invoice->update(['paid_amount' => $paid, 'balance_amount' => max(0, (float) $invoice->total_amount - $paid), 'status' => $paid >= (float) $invoice->total_amount ? 'paid' : 'partially_paid']); } return ApiResponse::success(['payment' => $payment->load(['tenant', 'invoice', 'subscription']), 'invoice' => $this->present($invoice->fresh())], 'Invoice payment recorded.'); }
    private function find(string $uuid): ?PlatformInvoice { return PlatformInvoice::where('uuid', $uuid)->first(); }
    private function present(PlatformInvoice $invoice): PlatformInvoice { return $invoice->load(['tenant.owner', 'subscription.plan', 'items', 'payments.tenant', 'payments.subscription', 'pdfFile']); }
}
