<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Shared\BaseApiController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class TenantCalendarController extends BaseApiController
{
 private function tid():int{return (int)request()->attributes->get('tenant_id');}
 private function row(string $table,string $uuid){return DB::table($table)->where('tenant_id',$this->tid())->where('uuid',$uuid)->firstOrFail();}
 private function id(string $table,$uuid):?int{return $uuid?DB::table($table)->where('tenant_id',$this->tid())->where('uuid',$uuid)->value('id'):null;}
 private function cp($c):array{$d=(array)$c;$d['owner']=$c->owner_user_id?DB::table('users')->where('tenant_id',$this->tid())->where('id',$c->owner_user_id)->first(['uuid','display_name','email']):null;$d['team']=$c->team_id?DB::table('teams')->where('tenant_id',$this->tid())->where('id',$c->team_id)->first(['uuid','name']):null;$d['events']=DB::table('calendar_events')->where('tenant_id',$this->tid())->where('calendar_id',$c->id)->whereNull('deleted_at')->get();return $d;}
 private function ep($e):array{$d=(array)$e;$d['calendar']=$this->row('calendars',DB::table('calendars')->where('id',$e->calendar_id)->value('uuid'));$d['attendees']=DB::table('calendar_event_attendees')->where('tenant_id',$this->tid())->where('event_id',$e->id)->get();$d['reminders']=DB::table('calendar_event_reminders')->where('tenant_id',$this->tid())->where('event_id',$e->id)->get();$d['room_booking']=DB::table('meeting_room_bookings')->where('tenant_id',$this->tid())->where('event_id',$e->id)->first();$d['video_meeting']=DB::table('video_meetings')->where('tenant_id',$this->tid())->where('event_id',$e->id)->first();return $d;}
 public function calendars(Request $r){$q=DB::table('calendars')->where('tenant_id',$this->tid());if($r->filled('search'))$q->where('name','like','%'.$r->search.'%');$p=$q->orderBy('name')->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->map(fn($x)=>$this->cp($x))->all(),$p,'Calendars fetched.');}
 public function calendarShow(string $uuid){return $this->success(['calendar'=>$this->cp($this->row('calendars',$uuid))]);}
 public function calendarStore(Request $r){$d=$r->validate(['name'=>'required|string','calendar_type'=>'required|string','owner_user_id'=>'nullable|string','team_id'=>'nullable|string','color'=>'nullable|string','timezone'=>'nullable|string','visibility'=>'nullable|string','status'=>'nullable|string']);foreach(['owner_user_id'=>'users','team_id'=>'teams'] as $f=>$t)if(isset($d[$f])){if(!$d[$f]=$this->id($t,$d[$f]))abort(422,'Invalid calendar relationship UUID.');}$id=DB::table('calendars')->insertGetId($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['calendar'=>$this->cp(DB::table('calendars')->where('id',$id)->first())],'Calendar created.',201);}
 public function calendarUpdate(Request $r,string $uuid){$c=$this->row('calendars',$uuid);$d=$r->except(['id','uuid','tenant_id']);foreach(['owner_user_id'=>'users','team_id'=>'teams'] as $f=>$t)if(array_key_exists($f,$d)&&$d[$f]!==null){if(!$d[$f]=$this->id($t,$d[$f]))abort(422,'Invalid calendar relationship UUID.');}DB::table('calendars')->where('id',$c->id)->update($d+['updated_at'=>now()]);return $this->calendarShow($uuid);}
 public function calendarDelete(string $uuid){$c=$this->row('calendars',$uuid);DB::table('calendars')->where('id',$c->id)->delete();return $this->success(null,'Calendar deleted.');}
 public function events(Request $r){$q=DB::table('calendar_events')->where('tenant_id',$this->tid())->whereNull('deleted_at');if($r->filled('calendar'))if($id=$this->id('calendars',$r->calendar))$q->where('calendar_id',$id);if($r->filled('search'))$q->where('title','like','%'.$r->search.'%');return $this->success(['events'=>$q->orderBy('starts_at')->get()->map(fn($x)=>$this->ep($x))]);}
 public function eventShow(string $uuid){return $this->success(['event'=>$this->ep($this->row('calendar_events',$uuid))]);}
 public function eventStore(Request $r){$d=$r->validate(['calendar_id'=>'required|string','title'=>'required|string','description'=>'nullable|string','location'=>'nullable|string','starts_at'=>'required|date','ends_at'=>'nullable|date','timezone'=>'nullable|string','all_day'=>'nullable|boolean','recurrence_rule'=>'nullable|array','status'=>'nullable|string','related_type'=>'nullable|string','related_id'=>'nullable|integer']);if(!$d['calendar_id']=$this->id('calendars',$d['calendar_id']))abort(422,'Invalid calendar UUID.');$id=DB::table('calendar_events')->insertGetId($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'created_by'=>auth()->id(),'updated_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['event'=>$this->ep(DB::table('calendar_events')->where('id',$id)->first())],'Event created.',201);}
 public function eventUpdate(Request $r,string $uuid){$e=$this->row('calendar_events',$uuid);$d=$r->except(['id','uuid','tenant_id','created_by']);if(isset($d['calendar_id'])){if(!$d['calendar_id']=$this->id('calendars',$d['calendar_id']))abort(422,'Invalid calendar UUID.');}DB::table('calendar_events')->where('id',$e->id)->update($d+['updated_by'=>auth()->id(),'updated_at'=>now()]);return $this->eventShow($uuid);}
 public function eventDelete(string $uuid){$e=$this->row('calendar_events',$uuid);DB::table('calendar_events')->where('id',$e->id)->update(['deleted_at'=>now(),'status'=>'cancelled']);return $this->success(null,'Event cancelled.');}
 public function reschedule(Request $r,string $uuid){$e=$this->row('calendar_events',$uuid);$d=$r->validate(['starts_at'=>'required|date','ends_at'=>'nullable|date']);DB::table('calendar_events')->where('id',$e->id)->update($d+['updated_by'=>auth()->id(),'updated_at'=>now()]);return $this->eventShow($uuid);}
 public function child(Request $r,string $uuid,string $kind){$e=$this->row('calendar_events',$uuid);$map=['attendees'=>'calendar_event_attendees','reminders'=>'calendar_event_reminders'];if(!isset($map[$kind]))abort(404);$q=DB::table($map[$kind])->where('tenant_id',$this->tid())->where('event_id',$e->id);if($r->isMethod('get'))return $this->success([$kind=>$q->get()]);$d=$r->except(['id','tenant_id','event_id']);$id=DB::table($map[$kind])->insertGetId($d+['tenant_id'=>$this->tid(),'event_id'=>$e->id]);return $this->success([$kind=>DB::table($map[$kind])->where('id',$id)->first()],'Child created.',201);}
 public function video(Request $r,string $uuid){$e=$this->row('calendar_events',$uuid);$d=$r->validate(['provider'=>'required|string','meeting_id'=>'nullable|string','meeting_url'=>'nullable|string','passcode'=>'nullable|string']);DB::table('video_meetings')->updateOrInsert(['tenant_id'=>$this->tid(),'event_id'=>$e->id],$d);return $this->success(['video_meeting'=>DB::table('video_meetings')->where('tenant_id',$this->tid())->where('event_id',$e->id)->first()]);}
 public function room(Request $r,string $uuid){$e=$this->row('calendar_events',$uuid);$d=$r->validate(['room_id'=>'required']);$room=DB::table('meeting_rooms')->where('tenant_id',$this->tid())->where(fn($q)=>$q->where('id',$d['room_id'])->orWhere('uuid',$d['room_id']))->firstOrFail();$conflict=DB::table('meeting_room_bookings')->join('calendar_events','calendar_events.id','=','meeting_room_bookings.event_id')->where('meeting_room_bookings.tenant_id',$this->tid())->where('meeting_room_bookings.room_id',$room->id)->where('meeting_room_bookings.status','booked')->where('calendar_events.status','!=','cancelled')->whereNull('calendar_events.deleted_at')->where('calendar_events.starts_at','<',$e->ends_at??$e->starts_at)->where(function($q)use($e){$q->whereNull('calendar_events.ends_at')->orWhere('calendar_events.ends_at','>',$e->starts_at);})->exists();if($conflict)return $this->businessError('Room is already booked.','ROOM_BOOKING_CONFLICT');DB::table('meeting_room_bookings')->updateOrInsert(['tenant_id'=>$this->tid(),'event_id'=>$e->id],['room_id'=>$room->id,'booked_by'=>auth()->id(),'status'=>'booked']);return $this->success(['room_booking'=>DB::table('meeting_room_bookings')->where('tenant_id',$this->tid())->where('event_id',$e->id)->first()]);}
 public function rooms(){return $this->success(['meeting_rooms'=>DB::table('meeting_rooms')->where('tenant_id',$this->tid())->orderBy('name')->get()]);}
 public function roomStore(Request $r){$d=$r->validate(['name'=>'required|string','office_id'=>'nullable|string','location'=>'nullable|string','capacity'=>'nullable|integer','status'=>'nullable|string']);if(isset($d['office_id'])){if(!$d['office_id']=$this->id('tenant_offices',$d['office_id']))abort(422,'Invalid office UUID.');}DB::table('meeting_rooms')->insert($d+['tenant_id'=>$this->tid()]);return $this->rooms();}
 public function roomUpdate(Request $r,int $id){$d=$r->except(['id','tenant_id']);DB::table('meeting_rooms')->where('tenant_id',$this->tid())->where('id',$id)->update($d);return $this->rooms();}
}
