<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Shared\BaseApiController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

final class TenantSharedPrimitiveController extends BaseApiController
{
 private function tid():int{return (int)request()->attributes->get('tenant_id');}
 private function entity(string $type,$uuid){$map=['party'=>'parties','client'=>'parties','vendor'=>'parties','lead'=>'parties','project'=>'projects','task'=>'tasks','client_issue'=>'client_issues','calendar_event'=>'calendar_events','staff'=>'staff'];$table=$map[$type]??null;if(!$table)abort(422,'Unsupported entity type.');$q=DB::table($table)->where('tenant_id',$this->tid())->where('uuid',$uuid);if(in_array($type,['client','vendor','lead'],true))$q->where('party_type',$type);return [$type,$q->firstOrFail()];}
 public function lookups(Request $r){$q=DB::table('tenant_lookups')->where(fn($x)=>$x->where('tenant_id',$this->tid())->orWhereNull('tenant_id'))->where('status','active');if($r->filled('group'))$q->where('group',$r->group);if($r->filled('groups'))$q->whereIn('group',explode(',',$r->groups));if($r->filled('search'))$q->where('name','like','%'.$r->search.'%');return $this->success(['lookups'=>$q->orderBy('group')->orderBy('sort_order')->get()]);}
 public function files(Request $r){$q=DB::table('files')->where('tenant_id',$this->tid())->whereNull('deleted_at');if($r->filled('search'))$q->where('original_name','like','%'.$r->search.'%');if($r->filled('mime_type'))$q->where('mime_type',$r->mime_type);$p=$q->latest()->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->all(),$p,'Files fetched.');}
 public function upload(Request $r){$r->validate(['file'=>'required|file|max:51200','visibility'=>'nullable|in:private,public,tenant','disk'=>'nullable|string']);$f=$r->file('file');$disk=$r->input('disk','local');$path=$f->store('tenant/'.$this->tid().'/files',$disk);$id=DB::table('files')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'uploaded_by'=>auth()->id(),'disk'=>$disk,'path'=>$path,'original_name'=>$f->getClientOriginalName(),'mime_type'=>$f->getMimeType(),'extension'=>$f->getClientOriginalExtension(),'size_bytes'=>$f->getSize(),'visibility'=>$r->input('visibility','private'),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['file'=>DB::table('files')->where('id',$id)->first()],'File uploaded.',201);}
 public function download(string $uuid){$f=DB::table('files')->where('tenant_id',$this->tid())->where('uuid',$uuid)->whereNull('deleted_at')->firstOrFail();$url=Storage::disk($f->disk)->temporaryUrl($f->path,now()->addMinutes(10));return $this->success(['url'=>$url,'expires_at'=>now()->addMinutes(10)]);}
 public function deleteFile(string $uuid){$f=DB::table('files')->where('tenant_id',$this->tid())->where('uuid',$uuid)->whereNull('deleted_at')->firstOrFail();if(DB::table('attachments')->where('tenant_id',$this->tid())->where('file_id',$f->id)->exists())return $this->businessError('File is still attached.','FILE_IN_USE');Storage::disk($f->disk)->delete($f->path);DB::table('files')->where('id',$f->id)->update(['deleted_at'=>now()]);return $this->success(null,'File deleted.');}
 public function folders(){return $this->success(['folders'=>DB::table('document_folders')->where('tenant_id',$this->tid())->whereNull('deleted_at')->orderBy('name')->get()]);}
 public function createFolder(Request $r){$d=$r->validate(['name'=>'required|string','parent_uuid'=>'nullable|string','folder_type'=>'nullable|string']);$parent=$d['parent_uuid']?$this->entityFolder($d['parent_uuid']):null;$id=DB::table('document_folders')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'parent_id'=>$parent,'name'=>$d['name'],'slug'=>Str::slug($d['name']),'folder_type'=>$d['folder_type']??'general','created_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['folder'=>DB::table('document_folders')->where('id',$id)->first()],'Folder created.',201);}
 private function entityFolder($uuid){return DB::table('document_folders')->where('tenant_id',$this->tid())->where('uuid',$uuid)->value('id')??abort(422,'Invalid parent folder.');}
 public function attachFolder(Request $r,string $uuid){$folder=DB::table('document_folders')->where('tenant_id',$this->tid())->where('uuid',$uuid)->firstOrFail();$d=$r->validate(['file_uuid'=>'required|string']);$file=DB::table('files')->where('tenant_id',$this->tid())->where('uuid',$d['file_uuid'])->firstOrFail();DB::table('document_folder_files')->insertOrIgnore(['tenant_id'=>$this->tid(),'document_folder_id'=>$folder->id,'file_id'=>$file->id,'created_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['status'=>'attached']);}
 public function attachments(Request $r){$q=DB::table('attachments')->where('tenant_id',$this->tid());if($r->filled('attachable_type')&&$r->filled('attachable_uuid')){[, $e]=$this->entity($r->attachable_type,$r->attachable_uuid);$q->where('attachable_type',$r->attachable_type)->where('attachable_id',$e->id);}return $this->success(['attachments'=>$q->get()->map(fn($a)=>[...(array)$a,'file'=>DB::table('files')->where('id',$a->file_id)->first()])]);}
 public function attach(Request $r){$d=$r->validate(['file_uuid'=>'required|string','attachable_type'=>'required|string','attachable_uuid'=>'required|string','label'=>'nullable|string']);$file=DB::table('files')->where('tenant_id',$this->tid())->where('uuid',$d['file_uuid'])->firstOrFail();[$type,$e]=$this->entity($d['attachable_type'],$d['attachable_uuid']);$id=DB::table('attachments')->insertGetId(['tenant_id'=>$this->tid(),'file_id'=>$file->id,'attachable_type'=>$type,'attachable_id'=>$e->id,'label'=>$d['label']??null,'created_by'=>auth()->id(),'created_at'=>now()]);return $this->success(['attachment'=>DB::table('attachments')->where('id',$id)->first()],'Attachment created.',201);}
 public function detach(int $id){$q=DB::table('attachments')->where('tenant_id',$this->tid())->where('id',$id);if(!$q->exists())abort(404);$q->delete();return $this->success(null,'Attachment removed.');}
 public function notes(Request $r){$q=DB::table('notes')->where('tenant_id',$this->tid())->whereNull('deleted_at');if($r->filled('notable_type')&&$r->filled('notable_uuid')){[$type,$e]=$this->entity($r->notable_type,$r->notable_uuid);$q->where('notable_type',$type)->where('notable_id',$e->id);}return $this->success(['notes'=>$q->latest()->get()]);}
 public function noteStore(Request $r){$d=$r->validate(['notable_type'=>'required|string','notable_uuid'=>'required|string','note'=>'required|string','visibility'=>'nullable|in:private,team,tenant,client']);[$type,$e]=$this->entity($d['notable_type'],$d['notable_uuid']);$id=DB::table('notes')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'notable_type'=>$type,'notable_id'=>$e->id,'note'=>$d['note'],'visibility'=>$d['visibility']??'tenant','created_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['note'=>DB::table('notes')->where('id',$id)->first()],'Note created.',201);}
 public function noteUpdate(Request $r,string $uuid){$d=$r->validate(['note'=>'sometimes|string','visibility'=>'sometimes|in:private,team,tenant,client']);$q=DB::table('notes')->where('tenant_id',$this->tid())->where('uuid',$uuid);if(!$q->exists())abort(404);$q->update($d+['updated_by'=>auth()->id(),'updated_at'=>now()]);return $this->success(['note'=>$q->first()]);}
 public function noteDelete(string $uuid){$q=DB::table('notes')->where('tenant_id',$this->tid())->where('uuid',$uuid);if(!$q->exists())abort(404);$q->update(['deleted_at'=>now()]);return $this->success(null,'Note deleted.');}
 public function tags(){return $this->success(['tags'=>DB::table('tags')->where('tenant_id',$this->tid())->orderBy('name')->get()]);}
 public function tagStore(Request $r){$d=$r->validate(['name'=>'required|string','slug'=>'nullable|string','color'=>'nullable|string','icon'=>'nullable|string']);$d['slug']=$d['slug']??Str::slug($d['name']);$id=DB::table('tags')->insertGetId($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['tag'=>DB::table('tags')->where('id',$id)->first()],'Tag created.',201);}
 public function tagUpdate(Request $r,string $uuid){$q=DB::table('tags')->where('tenant_id',$this->tid())->where('uuid',$uuid);if(!$q->exists())abort(404);$q->update($r->except(['id','uuid','tenant_id'])+['updated_at'=>now()]);return $this->success(['tag'=>$q->first()]);}
 public function tagDelete(string $uuid){$x=DB::table('tags')->where('tenant_id',$this->tid())->where('uuid',$uuid)->firstOrFail();if(DB::table('taggables')->where('tenant_id',$this->tid())->where('tag_id',$x->id)->exists())return $this->businessError('Tag is in use.','TAG_IN_USE');DB::table('tags')->where('id',$x->id)->delete();return $this->success(null,'Tag deleted.');}
 public function customFields(Request $r){$q=DB::table('custom_fields')->where('tenant_id',$this->tid());if($r->filled('entity_type'))$q->where('entity_type',$r->entity_type);return $this->success(['custom_fields'=>$q->orderBy('sort_order')->get()]);}
 public function customFieldStore(Request $r){$d=$r->validate(['entity_type'=>'required|string','name'=>'required|string','code'=>'required|string','field_type'=>'required|string','options'=>'nullable|array','validation_rules'=>'nullable|array','is_required'=>'nullable|boolean']);$id=DB::table('custom_fields')->insertGetId($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'options'=>json_encode($d['options']??[]),'validation_rules'=>json_encode($d['validation_rules']??[]),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['custom_field'=>DB::table('custom_fields')->where('id',$id)->first()],'Custom field created.',201);}
}
