<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Shared\BaseApiController;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class TenantSettingsController extends BaseApiController
{
 private function tid():int{return (int)request()->attributes->get('tenant_id');}
 public function group(Request $r,string $group){$rows=DB::table('tenant_settings')->where('tenant_id',$this->tid())->where('group',$group)->get()->map(fn($x)=>[...(array)$x,'value'=>$x->is_encrypted?null:json_decode((string)$x->value,true),'is_secret'=>(bool)$x->is_encrypted]);return $this->success(['group'=>$group,'settings'=>$rows,'values'=>$rows->mapWithKeys(fn($x)=>[$x['key']=>$x['value']])]);}
 public function update(Request $r,string $group){$values=$r->input('settings',$r->except(['_token']));if(!is_array($values))abort(422,'Settings must be an object.');foreach($values as $key=>$value){$encrypted=in_array(strtolower((string)$key),['password','smtp_password','secret','client_secret','access_token','encryption_key'],true);DB::table('tenant_settings')->updateOrInsert(['tenant_id'=>$this->tid(),'group'=>$group,'key'=>(string)$key],['value'=>json_encode($value),'value_type'=>is_bool($value)?'boolean':(is_numeric($value)?'number':'json'),'is_encrypted'=>$encrypted,'updated_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);}return $this->group($r,$group);}
 public function lookups(){return $this->success(['lookups'=>DB::table('tenant_lookups')->where('tenant_id',$this->tid())->orderBy('group')->orderBy('sort_order')->get()]);}
 public function reorder(Request $r){$d=$r->validate(['lookups'=>'required|array']);foreach($d['lookups'] as $index=>$uuid){DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('uuid',$uuid)->update(['sort_order'=>$index]);}return $this->lookups();}
 public function deleteLookup(Request $r,string $uuid){$d=$r->validate(['reason'=>'required|string']);$x=DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('uuid',$uuid)->firstOrFail();foreach(['parties','projects','tasks','client_issues','renewals'] as $table){if(DB::getSchemaBuilder()->hasColumn($table,'status_id')&&DB::table($table)->where('status_id',$x->id)->exists())return $this->businessError('Lookup is in use.','LOOKUP_IN_USE');}DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('id',$x->id)->delete();return $this->success(null,'Lookup deleted.');}
 public function notifications(Request $r){$q=DB::table('notifications')->join('users','users.id','=','notifications.notifiable_id')->where('notifications.notifiable_type',User::class)->where('users.tenant_id',$this->tid())->where('users.id',auth()->id())->select('notifications.*');if($r->boolean('unread'))$q->whereNull('read_at');if($r->filled('search'))$q->where('notifications.data','like','%'.$r->search.'%');$p=$q->latest()->paginate((int)$r->integer('per_page',25));$rows=$p->getCollection()->map(fn($x)=>$this->notification($x))->all();return $this->list($rows,$p,'Notifications fetched.');}
 private function notification($x){$data=json_decode((string)$x->data,true)?:[];return [...(array)$x,'payload'=>$data,'title'=>$data['title']??$data['subject']??'Notification','message'=>$data['message']??$data['body']??'','is_read'=>(bool)$x->read_at];}
 public function unreadCount(){return $this->success(['unread_count'=>DB::table('notifications')->join('users','users.id','=','notifications.notifiable_id')->where('notifications.notifiable_type',User::class)->where('users.tenant_id',$this->tid())->where('users.id',auth()->id())->whereNull('read_at')->count()]);}
 public function notificationRead(string $id,bool $unread=false){$q=DB::table('notifications')->join('users','users.id','=','notifications.notifiable_id')->where('notifications.id',$id)->where('notifications.notifiable_type',User::class)->where('users.tenant_id',$this->tid())->where('users.id',auth()->id());if(!$q->exists())abort(404);DB::table('notifications')->where('id',$id)->update(['read_at'=>$unread?now():null]);return $this->success(['notification'=>$this->notification(DB::table('notifications')->where('id',$id)->first())]);}
 public function bulkRead(Request $r){$ids=$r->input('ids',[]);if(!is_array($ids))abort(422);$q=DB::table('notifications')->join('users','users.id','=','notifications.notifiable_id')->where('notifications.notifiable_type',User::class)->where('users.tenant_id',$this->tid())->where('users.id',auth()->id())->whereNull('read_at');if($ids)$q->whereIn('notifications.id',$ids);$valid=$q->pluck('notifications.id');DB::table('notifications')->whereIn('id',$valid)->update(['read_at'=>now()]);return $this->success(['updated'=>$valid->count()]);}
 public function notificationDelete(string $id){$q=DB::table('notifications')->join('users','users.id','=','notifications.notifiable_id')->where('notifications.id',$id)->where('notifications.notifiable_type',User::class)->where('users.tenant_id',$this->tid())->where('users.id',auth()->id());if(!$q->exists())abort(404);DB::table('notifications')->where('id',$id)->delete();return $this->success(null,'Notification deleted.');}
 public function templates(Request $r){$q=DB::table('notification_templates')->where(fn($x)=>$x->where('tenant_id',$this->tid())->orWhereNull('tenant_id'));$p=$q->latest()->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->all(),$p,'Notification templates fetched.');} public function templateStore(Request $r){$d=$r->validate(['code'=>'required|string|max:120','channel'=>'required|string|max:30','subject'=>'nullable|string','body'=>'required|string','variables'=>'nullable|array']);$id=DB::table('notification_templates')->insertGetId($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'variables'=>json_encode($d['variables']??[]),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['template'=>DB::table('notification_templates')->where('id',$id)->first()],'Template created.',201);} public function templateUpdate(Request $r,string $uuid){$d=$r->except(['id','uuid','tenant_id']);if(isset($d['variables']))$d['variables']=json_encode($d['variables']);$q=DB::table('notification_templates')->where('tenant_id',$this->tid())->where('uuid',$uuid);if(!$q->exists())abort(404);$q->update($d+['updated_at'=>now()]);return $this->success(['template'=>$q->first()]);} public function backupRuns(Request $r){$p=DB::table('tenant_backup_runs')->where('tenant_id',$this->tid())->latest()->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->all(),$p,'Backup runs fetched.');} public function runBackup(Request $r){$d=$r->validate(['backup_type'=>'nullable|string|max:80']);$id=DB::table('tenant_backup_runs')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'backup_type'=>$d['backup_type']??'full','status'=>'queued']);return $this->success(['run'=>DB::table('tenant_backup_runs')->where('id',$id)->first()],'Backup queued.',202);} public function restoreBackup(Request $r){$d=$r->validate(['backup_uuid'=>'required|string','reason'=>'required|string']);$run=DB::table('tenant_backup_runs')->where('tenant_id',$this->tid())->where('uuid',$d['backup_uuid'])->firstOrFail();$id=DB::table('tenant_restore_requests')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'tenant_backup_run_id'=>$run->id,'status'=>'pending','requested_by'=>auth()->id(),'requested_at'=>now()]);return $this->success(['restore_request'=>DB::table('tenant_restore_requests')->where('id',$id)->first()],'Restore request queued.',202);}
}
