<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Shared\BaseApiController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class TenantIntegrationAuditController extends BaseApiController
{
 private function tid():int{return (int)request()->attributes->get('tenant_id');}
 private function integration(string $uuid){return DB::table('tenant_integrations')->where('tenant_id',$this->tid())->where('uuid',$uuid)->firstOrFail();}
 private function payload($x):array{$d=(array)$x;$d['provider']=DB::table('integration_providers')->where('id',$x->provider_id)->first(['id','code','name','category','auth_type','credential_fields']);$d['credentials']=DB::table('integration_credentials')->where('tenant_integration_id',$x->id)->get(['key','expires_at']);$d['webhooks']=DB::table('integration_webhooks')->where('tenant_integration_id',$x->id)->get();$d['sync_jobs']=DB::table('integration_sync_jobs')->where('tenant_integration_id',$x->id)->latest('id')->limit(20)->get();$d['field_mappings']=DB::table('integration_field_mappings')->where('tenant_integration_id',$x->id)->get();$d['rate_limits']=DB::table('integration_rate_limits')->where('tenant_integration_id',$x->id)->latest('window_end')->limit(20)->get();return $d;}
 public function providers(){return $this->success(['providers'=>DB::table('integration_providers')->where('status','active')->orderBy('name')->get()]);}
 public function integrations(Request $r){$q=DB::table('tenant_integrations')->where('tenant_id',$this->tid());$p=$q->latest()->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->map(fn($x)=>$this->payload($x))->all(),$p,'Integrations fetched.');}
 public function show(string $uuid){return $this->success(['integration'=>$this->payload($this->integration($uuid))]);}
 public function store(Request $r){$d=$r->validate(['provider_id'=>'nullable','provider_code'=>'nullable|string','name'=>'required|string|max:150','credentials'=>'nullable|array']);$provider=DB::table('integration_providers')->where('status','active')->where(fn($q)=>$q->where('id',$d['provider_id']??0)->orWhere('code',$d['provider_code']??''))->first();if(!$provider)abort(422,'Invalid integration provider.');$id=DB::table('tenant_integrations')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'provider_id'=>$provider->id,'name'=>$d['name'],'status'=>'active','connected_by'=>auth()->id(),'connected_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);foreach(($d['credentials']??[]) as $key=>$value)DB::table('integration_credentials')->updateOrInsert(['tenant_integration_id'=>$id,'key'=>$key],['encrypted_value'=>encrypt($value),'updated_at'=>now()]);return $this->show(DB::table('tenant_integrations')->where('id',$id)->value('uuid'));}
 public function update(Request $r,string $uuid){$x=$this->integration($uuid);$d=$r->validate(['name'=>'sometimes|string|max:150','status'=>'sometimes|in:active,inactive,disconnected']);DB::table('tenant_integrations')->where('id',$x->id)->update($d+['updated_at'=>now()]);return $this->show($uuid);}
 public function rotate(Request $r,string $uuid){$x=$this->integration($uuid);$d=$r->validate(['credentials'=>'required|array']);foreach($d['credentials'] as $key=>$value)DB::table('integration_credentials')->updateOrInsert(['tenant_integration_id'=>$x->id,'key'=>$key],['encrypted_value'=>encrypt($value),'updated_at'=>now()]);return $this->show($uuid);}
 public function disconnect(Request $r,string $uuid){$x=$this->integration($uuid);$r->validate(['reason'=>'required|string']);DB::table('tenant_integrations')->where('id',$x->id)->update(['status'=>'disconnected','updated_at'=>now()]);return $this->show($uuid);}
 public function webhooks(){return $this->success(['webhooks'=>DB::table('integration_webhooks')->join('tenant_integrations','tenant_integrations.id','=','integration_webhooks.tenant_integration_id')->where('tenant_integrations.tenant_id',$this->tid())->get(['integration_webhooks.*','tenant_integrations.uuid as integration_uuid','tenant_integrations.name as integration_name'])]);}
 public function syncJobs(){return $this->success(['sync_jobs'=>DB::table('integration_sync_jobs')->join('tenant_integrations','tenant_integrations.id','=','integration_sync_jobs.tenant_integration_id')->where('tenant_integrations.tenant_id',$this->tid())->latest('integration_sync_jobs.id')->get(['integration_sync_jobs.*','tenant_integrations.uuid as integration_uuid'])]);}
 public function retry(Request $r,int $id){$q=DB::table('integration_sync_jobs')->join('tenant_integrations','tenant_integrations.id','=','integration_sync_jobs.tenant_integration_id')->where('tenant_integrations.tenant_id',$this->tid())->where('integration_sync_jobs.id',$id);if(!$q->exists())abort(404);DB::table('integration_sync_jobs')->where('id',$id)->update(['status'=>'retry_queued']);return $this->success(['status'=>'retry_queued']);}
 public function mappings(string $uuid){$x=$this->integration($uuid);return $this->success(['mappings'=>DB::table('integration_field_mappings')->where('tenant_integration_id',$x->id)->get()]);}
 public function saveMappings(Request $r,string $uuid){$x=$this->integration($uuid);$d=$r->validate(['mappings'=>'required|array']);DB::transaction(function()use($x,$d){DB::table('integration_field_mappings')->where('tenant_integration_id',$x->id)->delete();foreach($d['mappings'] as $m)DB::table('integration_field_mappings')->insert(['tenant_integration_id'=>$x->id,'entity_type'=>$m['entity_type'],'local_field'=>$m['local_field'],'external_field'=>$m['external_field'],'transform_rule'=>isset($m['transform_rule'])?json_encode($m['transform_rule']):null]);});return $this->mappings($uuid);}
 public function rateLimits(string $uuid){$x=$this->integration($uuid);return $this->success(['rate_limits'=>DB::table('integration_rate_limits')->where('tenant_integration_id',$x->id)->latest('window_end')->get()]);}
 public function audit(Request $r,string $type){$map=['activity-logs'=>['activity_logs',null],'login-history'=>['security_events','event like \'%login%\''],'system-api-logs'=>['api_request_logs',null],'data-changes'=>['activity_logs','(old_values is not null or new_values is not null)']];if(!isset($map[$type]))abort(404);[$table,$extra]=$map[$type];$q=DB::table($table)->where('tenant_id',$this->tid());if($extra)$q->whereRaw($extra);if($r->filled('search'))$q->where(function($x)use($r){$x->where('event','like','%'.$r->search.'%')->orWhere('description','like','%'.$r->search.'%');});$p=$q->latest('created_at')->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->all(),$p,'Audit records fetched.');}
 public function compare(string $id){$x=DB::table('activity_logs')->where('tenant_id',$this->tid())->where('id',$id)->firstOrFail();$old=json_decode((string)$x->old_values,true)?:[];$new=json_decode((string)$x->new_values,true)?:[];$keys=array_values(array_unique(array_merge(array_keys($old),array_keys($new))));return $this->success(['old_values'=>$old,'new_values'=>$new,'changed_fields'=>array_values(array_filter($keys,fn($k)=>($old[$k]??null)!==($new[$k]??null)))]);}
 public function auditExport(){return $this->success(['status'=>'queued','job_id'=>(string)Str::uuid()],'Audit export queued.',202);}
 public function selectors(){return $this->success(['users'=>DB::table('users')->where('tenant_id',$this->tid())->get(['uuid','display_name','email']),'teams'=>DB::table('teams')->where('tenant_id',$this->tid())->get(['uuid','name']),'clients'=>DB::table('parties')->where('tenant_id',$this->tid())->where('party_type','client')->get(['uuid','display_name','email']),'vendors'=>DB::table('parties')->where('tenant_id',$this->tid())->where('party_type','vendor')->get(['uuid','display_name','email']),'projects'=>DB::table('projects')->where('tenant_id',$this->tid())->get(['uuid','project_number','name']),'staff'=>DB::table('staff')->where('tenant_id',$this->tid())->get(['uuid','display_name','employee_code']),'providers'=>DB::table('integration_providers')->where('status','active')->get(),'lookups'=>DB::table('tenant_lookups')->where('tenant_id',$this->tid())->orderBy('group')->orderBy('sort_order')->get()]);}
}
