<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Shared\BaseApiController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class TenantFinanceController extends BaseApiController
{
 private function tid():int{return (int)request()->attributes->get('tenant_id');}
 private function party(?string $uuid,bool $required=false):?object{if(!$uuid)return $required?abort(422,'Client or vendor relationship is required.'):null;$x=DB::table('parties')->where('tenant_id',$this->tid())->where('uuid',$uuid)->first();return $x?:abort(404,'Party not found in this tenant.');}
 private function project(?string $uuid):?object{if(!$uuid)return null;$x=DB::table('projects')->where('tenant_id',$this->tid())->where('uuid',$uuid)->first();return $x?:abort(404,'Project not found in this tenant.');}
 private function invoice(string $uuid):object{$x=DB::table('tenant_invoices')->where('tenant_id',$this->tid())->where('uuid',$uuid)->whereNull('deleted_at')->first();return $x?:abort(404,'Invoice not found.');}
 private function payment(string $uuid):object{$x=DB::table('tenant_payments')->where('tenant_id',$this->tid())->where('uuid',$uuid)->first();return $x?:abort(404,'Payment not found.');}
 private function expense(string $uuid):object{$x=DB::table('tenant_expenses')->where('tenant_id',$this->tid())->where('uuid',$uuid)->whereNull('deleted_at')->first();return $x?:abort(404,'Expense not found.');}
 private function partySummary(?int $id):?array{if(!$id)return null;$x=DB::table('parties')->where('tenant_id',$this->tid())->where('id',$id)->first();return $x?['uuid'=>$x->uuid,'display_name'=>$x->display_name,'email'=>$x->email,'phone'=>$x->phone]:null;}
 private function projectSummary(?int $id):?array{if(!$id)return null;$x=DB::table('projects')->where('tenant_id',$this->tid())->where('id',$id)->first();return $x?['uuid'=>$x->uuid,'name'=>$x->name,'project_number'=>$x->project_number,'status'=>$x->status]:null;}
 private function invPayload(object $x,bool $detail=false):array{$a=(array)$x;$a['client']=$this->partySummary($x->client_party_id);$a['project']=$this->projectSummary($x->project_id);$a['client_name']=$a['client']['display_name']??null;$a['project_name']=$a['project']['name']??null;unset($a['client_party_id'],$a['project_id']);if($detail){$a['items']=DB::table('tenant_invoice_items')->where('tenant_id',$this->tid())->where('invoice_id',$x->id)->get();$a['payments']=DB::table('tenant_payments')->where('tenant_id',$this->tid())->where('invoice_id',$x->id)->get()->map(fn($p)=>$this->payPayload($p))->all();}return $a;}
 private function payPayload(object $x):array{$a=(array)$x;$a['client']=$this->partySummary($x->client_party_id);$a['invoice']=$x->invoice_id?DB::table('tenant_invoices')->where('tenant_id',$this->tid())->where('id',$x->invoice_id)->first(['uuid','invoice_number','status','balance_amount']):null;$a['client_name']=$a['client']['display_name']??null;$a['invoice_number']=$a['invoice']->invoice_number??null;unset($a['client_party_id'],$a['invoice_id']);return $a;}
 private function expPayload(object $x,bool $detail=false):array{$a=(array)$x;$a['vendor']=$this->partySummary($x->vendor_party_id);$a['project']=$this->projectSummary($x->project_id);$a['vendor_name']=$a['vendor']['display_name']??null;$a['project_name']=$a['project']['name']??null;if($detail)$a['items']=DB::table('tenant_expense_items')->where('tenant_id',$this->tid())->where('expense_id',$x->id)->get();unset($a['vendor_party_id'],$a['project_id']);return $a;}
 private function recalc(int $id):void{$i=DB::table('tenant_invoices')->where('tenant_id',$this->tid())->where('id',$id)->first();$sub=(float)DB::table('tenant_invoice_items')->where('tenant_id',$this->tid())->where('invoice_id',$id)->sum('amount');$tax=(float)DB::table('tenant_invoice_items')->where('tenant_id',$this->tid())->where('invoice_id',$id)->sum(DB::raw('amount * tax_rate / 100'));$taxable=max(0,$sub-(float)$i->discount_amount);$total=max(0,$taxable+$tax);$paid=(float)DB::table('tenant_payments')->where('tenant_id',$this->tid())->where('invoice_id',$id)->whereNotIn('status',['void','cancelled'])->sum('amount');DB::table('tenant_invoices')->where('id',$id)->update(['subtotal'=>$sub,'tax_amount'=>$tax,'taxable_amount'=>$taxable,'total_amount'=>$total,'paid_amount'=>$paid,'balance_amount'=>max(0,$total-$paid),'updated_at'=>now()]);}
 public function dashboard(){return $this->success(['draft_invoices'=>DB::table('tenant_invoices')->where('tenant_id',$this->tid())->whereNull('deleted_at')->where('status','draft')->count(),'sent_invoices'=>DB::table('tenant_invoices')->where('tenant_id',$this->tid())->whereNull('deleted_at')->where('status','sent')->count(),'open_balance'=>(float)DB::table('tenant_invoices')->where('tenant_id',$this->tid())->whereNull('deleted_at')->whereIn('status',['sent','overdue'])->sum('balance_amount'),'month_payments'=>(float)DB::table('tenant_payments')->where('tenant_id',$this->tid())->where('status','paid')->whereBetween('paid_at',[now()->startOfMonth(),now()->endOfMonth()])->sum('amount'),'month_expenses'=>(float)DB::table('tenant_expenses')->where('tenant_id',$this->tid())->whereNull('deleted_at')->whereBetween('expense_date',[now()->startOfMonth()->toDateString(),now()->endOfMonth()->toDateString()])->sum('amount'),'recent_invoices'=>DB::table('tenant_invoices')->where('tenant_id',$this->tid())->whereNull('deleted_at')->latest()->limit(5)->get()->map(fn($x)=>$this->invPayload($x)),'recent_payments'=>DB::table('tenant_payments')->where('tenant_id',$this->tid())->latest()->limit(5)->get()->map(fn($x)=>$this->payPayload($x)),'recent_expenses'=>DB::table('tenant_expenses')->where('tenant_id',$this->tid())->whereNull('deleted_at')->latest()->limit(5)->get()->map(fn($x)=>$this->expPayload($x))],'Finance dashboard fetched.');}
 public function invoices(Request $r){$q=DB::table('tenant_invoices as i')->leftJoin('parties as p','p.id','=','i.client_party_id')->where('i.tenant_id',$this->tid())->whereNull('i.deleted_at')->select('i.*');if($r->filled('status'))$q->where('i.status',$r->input('status'));if($r->filled('search'))$q->where(fn($x)=>$x->where('i.invoice_number','like','%'.$r->input('search').'%')->orWhere('p.display_name','like','%'.$r->input('search').'%'));$page=$q->latest('i.id')->paginate(min(max((int)$r->input('per_page',25),1),100))->withQueryString();return $this->list(collect($page->items())->map(fn($x)=>$this->invPayload($x))->all(),$page,'Invoices fetched.');}
 public function invoiceStore(Request $r){$d=$r->validate(['invoice_number'=>'nullable|string|max:80','client_party_uuid'=>'required|uuid','project_uuid'=>'nullable|uuid','invoice_date'=>'required|date','due_date'=>'nullable|date','currency'=>'sometimes|string|size:3','discount_amount'=>'sometimes|numeric|min:0','status'=>'sometimes|in:draft,sent','items'=>'nullable|array','items.*.item_name'=>'required_with:items|string|max:255','items.*.description'=>'nullable|string','items.*.quantity'=>'required_with:items|numeric|min:0.01','items.*.unit_price'=>'required_with:items|numeric|min:0','items.*.tax_rate'=>'nullable|numeric|min:0|max:100']);$c=$this->party($d['client_party_uuid'],true);$p=$this->project($d['project_uuid']??null);return DB::transaction(function()use($d,$c,$p){$id=DB::table('tenant_invoices')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'invoice_number'=>$d['invoice_number']??'INV-'.now()->format('Ymd').'-'.Str::upper(Str::random(5)),'client_party_id'=>$c->id,'project_id'=>$p?->id,'invoice_date'=>$d['invoice_date'],'due_date'=>$d['due_date']??null,'discount_amount'=>$d['discount_amount']??0,'currency'=>strtoupper($d['currency']??'INR'),'status'=>$d['status']??'draft','created_by'=>auth()->id(),'updated_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);foreach($d['items']??[] as $v)DB::table('tenant_invoice_items')->insert(['tenant_id'=>$this->tid(),'invoice_id'=>$id,'item_name'=>$v['item_name'],'description'=>$v['description']??null,'quantity'=>$v['quantity'],'unit_price'=>$v['unit_price'],'tax_rate'=>$v['tax_rate']??0,'amount'=>(float)$v['quantity']*(float)$v['unit_price']]);$this->recalc($id);return $this->success(['invoice'=>$this->invPayload(DB::table('tenant_invoices')->where('id',$id)->first(),true)],'Invoice created.',201);});}
 public function invoiceShow(string $uuid){return $this->success(['invoice'=>$this->invPayload($this->invoice($uuid),true)]);}
 public function invoiceUpdate(Request $r,string $uuid){$i=$this->invoice($uuid);if(in_array($i->status,['cancelled','paid'],true))abort(422,'Finalized invoices cannot be edited.');$d=$r->validate(['invoice_date'=>'sometimes|date','due_date'=>'nullable|date','discount_amount'=>'sometimes|numeric|min:0']);DB::table('tenant_invoices')->where('id',$i->id)->update($d+['updated_by'=>auth()->id(),'updated_at'=>now()]);$this->recalc($i->id);return $this->invoiceShow($uuid);}
 public function item(Request $r,string $uuid,?int $itemId=null){$i=$this->invoice($uuid);if($r->isMethod('delete')){DB::table('tenant_invoice_items')->where('tenant_id',$this->tid())->where('invoice_id',$i->id)->where('id',$itemId)->delete();$this->recalc($i->id);return $this->invoiceShow($uuid);}$d=$r->validate(['item_name'=>'required|string|max:255','description'=>'nullable|string','quantity'=>'required|numeric|min:0.01','unit_price'=>'required|numeric|min:0','tax_rate'=>'nullable|numeric|min:0|max:100']);$d['amount']=(float)$d['quantity']*(float)$d['unit_price'];$d+=['tenant_id'=>$this->tid(),'invoice_id'=>$i->id];if($itemId)DB::table('tenant_invoice_items')->where('tenant_id',$this->tid())->where('invoice_id',$i->id)->where('id',$itemId)->update($d);else DB::table('tenant_invoice_items')->insert($d);$this->recalc($i->id);return $this->invoiceShow($uuid);}
 public function invoiceSend(string $uuid){$i=$this->invoice($uuid);if($i->status==='cancelled')abort(422,'Cancelled invoices cannot be sent.');DB::table('tenant_invoices')->where('id',$i->id)->update(['status'=>'sent','updated_by'=>auth()->id(),'updated_at'=>now()]);return $this->invoiceShow($uuid);}
 public function invoiceCancel(Request $r,string $uuid){$r->validate(['reason'=>'required|string']);$i=$this->invoice($uuid);if($i->status==='paid')abort(422,'Paid invoices cannot be cancelled.');DB::table('tenant_invoices')->where('id',$i->id)->update(['status'=>'cancelled','updated_by'=>auth()->id(),'updated_at'=>now()]);return $this->invoiceShow($uuid);}
 public function invoicePdf(string $uuid){return $this->success(['invoice'=>$this->invPayload($this->invoice($uuid),true),'pdf'=>['status'=>'pending']],'Invoice PDF requested.',202);}
 public function payments(Request $r){$q=DB::table('tenant_payments')->where('tenant_id',$this->tid());if($r->filled('status'))$q->where('status',$r->input('status'));if($r->filled('search'))$q->where(fn($x)=>$x->where('payment_number','like','%'.$r->input('search').'%')->orWhere('reference','like','%'.$r->input('search').'%'));$page=$q->latest()->paginate(min(max((int)$r->input('per_page',25),1),100))->withQueryString();return $this->list(collect($page->items())->map(fn($x)=>$this->payPayload($x))->all(),$page,'Payments fetched.');}
 public function paymentStore(Request $r){$d=$r->validate(['payment_number'=>'nullable|string|max:80','invoice_uuid'=>'nullable|uuid','client_party_uuid'=>'nullable|uuid','amount'=>'required|numeric|gt:0','currency'=>'sometimes|string|size:3','method'=>'nullable|string|max:80','reference'=>'nullable|string|max:255','paid_at'=>'nullable|date']);$i=!empty($d['invoice_uuid'])?$this->invoice($d['invoice_uuid']):null;$c=$this->party($d['client_party_uuid']??null);if($i&&$c&&$i->client_party_id!==$c->id)abort(422,'Payment client does not match invoice client.');if($i&&(float)$d['amount']>(float)$i->balance_amount)abort(422,'Payment exceeds remaining invoice balance.');$id=DB::table('tenant_payments')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'invoice_id'=>$i?->id,'client_party_id'=>$c?->id??$i?->client_party_id,'payment_number'=>$d['payment_number']??'PAY-'.now()->format('Ymd').'-'.Str::upper(Str::random(5)),'amount'=>$d['amount'],'currency'=>strtoupper($d['currency']??'INR'),'method'=>$d['method']??null,'reference'=>$d['reference']??null,'status'=>'paid','paid_at'=>$d['paid_at']??now(),'created_at'=>now(),'updated_at'=>now()]);if($i)$this->recalc($i->id);return $this->success(['payment'=>$this->payPayload(DB::table('tenant_payments')->where('id',$id)->first())],'Payment recorded.',201);}
 public function paymentShow(string $uuid){return $this->success(['payment'=>$this->payPayload($this->payment($uuid))]);}
 public function paymentVoid(Request $r,string $uuid){$r->validate(['reason'=>'required|string']);$p=$this->payment($uuid);DB::table('tenant_payments')->where('id',$p->id)->update(['status'=>'void','updated_at'=>now()]);if($p->invoice_id)$this->recalc($p->invoice_id);return $this->paymentShow($uuid);}
 public function paymentReceipt(string $uuid){return $this->success(['payment'=>$this->payPayload($this->payment($uuid)),'receipt'=>['status'=>'pending']],'Payment receipt requested.',202);}
 public function expenses(Request $r){$q=DB::table('tenant_expenses')->where('tenant_id',$this->tid())->whereNull('deleted_at');if($r->filled('search'))$q->where('expense_number','like','%'.$r->input('search').'%');$page=$q->latest()->paginate(min(max((int)$r->input('per_page',25),1),100))->withQueryString();return $this->list(collect($page->items())->map(fn($x)=>$this->expPayload($x))->all(),$page,'Expenses fetched.');}
 public function expenseStore(Request $r){$d=$r->validate(['expense_number'=>'nullable|string|max:80','vendor_party_uuid'=>'nullable|uuid','project_uuid'=>'nullable|uuid','amount'=>'required|numeric|min:0','currency'=>'sometimes|string|size:3','expense_date'=>'required|date','category_id'=>'nullable|integer','status_id'=>'nullable|integer']);$v=$this->party($d['vendor_party_uuid']??null);$p=$this->project($d['project_uuid']??null);$id=DB::table('tenant_expenses')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'vendor_party_id'=>$v?->id,'project_id'=>$p?->id,'expense_number'=>$d['expense_number']??'EXP-'.now()->format('Ymd').'-'.Str::upper(Str::random(5)),'category_id'=>$d['category_id']??null,'amount'=>$d['amount'],'currency'=>strtoupper($d['currency']??'INR'),'expense_date'=>$d['expense_date'],'status_id'=>$d['status_id']??null,'created_at'=>now(),'updated_at'=>now()]);return $this->success(['expense'=>$this->expPayload(DB::table('tenant_expenses')->where('id',$id)->first())],'Expense created.',201);}
 public function expenseShow(string $uuid){return $this->success(['expense'=>$this->expPayload($this->expense($uuid),true)]);}
 public function expenseUpdate(Request $r,string $uuid){$e=$this->expense($uuid);$d=$r->validate(['amount'=>'sometimes|numeric|min:0','expense_date'=>'sometimes|date','category_id'=>'nullable|integer']);DB::table('tenant_expenses')->where('id',$e->id)->update($d+['updated_at'=>now()]);return $this->expenseShow($uuid);}
 public function expenseState(Request $r,string $uuid,string $state){$r->validate(['reason'=>'required|string']);$e=$this->expense($uuid);if(!in_array($state,['approved','rejected'],true))abort(404);$lookup=DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('code',$state)->value('id');DB::table('tenant_expenses')->where('id',$e->id)->update(['status_id'=>$lookup,'updated_at'=>now()]);return $this->expenseShow($uuid);}
 public function export(Request $r,string $module){$id=DB::table('tenant_import_export_jobs')->insertGetId(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'user_id'=>auth()->id(),'type'=>'export','module'=>$module,'status'=>'queued','payload'=>json_encode($r->all()),'created_at'=>now(),'updated_at'=>now()]);return $this->success(['job'=>DB::table('tenant_import_export_jobs')->where('id',$id)->first()],'Finance export queued.',202);}
}
