<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Shared\BaseApiController;
use App\Models\Party;
use App\Models\Renewal;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class TenantCrmController extends BaseApiController
{
 private function tid(): int{return (int)request()->attributes->get('tenant_id');}
 private function party(string $type,string $uuid): Party{return Party::where('tenant_id',$this->tid())->where('party_type',$type)->where('uuid',$uuid)->firstOrFail();}
 private function profileTable(string $type): string{return $type==='client'?'client_profiles':'vendor_profiles';}
 private function pPayload(Party $p,string $type): array{$profile=DB::table($this->profileTable($type))->where('tenant_id',$this->tid())->where('party_id',$p->id)->first();$data=$p->toArray();$data['profile']=$profile;$data['contacts']=DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$p->id)->whereNull('deleted_at')->get();$data['addresses']=DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id)->get();$data['party_uuid']=$p->uuid;$data['client_uuid']=$type==='client'?$p->uuid:null;$data['vendor_uuid']=$type==='vendor'?$p->uuid:null;$data['owner_user']=$p->owner?->only(['uuid','display_name','email']);if($profile){foreach((array)$profile as $key=>$value){if(!array_key_exists($key,$data))$data[$key]=$value;}}return $data;}
 private function pList(Request $r,string $type){$q=Party::where('parties.tenant_id',$this->tid())->where('parties.party_type',$type)->withTrashed(false)->leftJoin($this->profileTable($type).' as profiles','profiles.party_id','=','parties.id')->select('parties.*','profiles.'.($type==='client'?'client_code':'vendor_code'),'profiles.'.($type==='client'?'client_type':'vendor_category_id'));if($r->filled('search'))$q->where(fn($x)=>$x->where('parties.display_name','like','%'.$r->search.'%')->orWhere('parties.email','like','%'.$r->search.'%')->orWhere('profiles.'.($type==='client'?'client_code':'vendor_code'),'like','%'.$r->search.'%'));if($type==='client'&&$r->filled('filter.client_type'))$q->where('profiles.client_type',$r->input('filter.client_type'));$p=$q->orderBy('parties.display_name')->paginate((int)$r->integer('per_page',25));$rows=$p->getCollection()->map(fn($x)=>$this->pPayload(Party::find($x->id),$type))->all();return $this->list($rows,$p,ucfirst($type).'s fetched.');}
 public function clients(Request $r){return $this->pList($r,'client');} public function vendors(Request $r){return $this->pList($r,'vendor');}
 public function createParty(Request $r,string $type){$r->merge(array_merge((array)$r->input('party',[]),(array)$r->input('profile',[]),$r->except(['party','profile'])));$d=$r->validate(['display_name'=>'required|string|max:200','legal_name'=>'nullable|string|max:200','email'=>'nullable|email','phone'=>'nullable|string|max:30','website'=>'nullable|string','client_code'=>'nullable|string|max:80','vendor_code'=>'nullable|string|max:80','client_type'=>'nullable|string|max:80','vendor_category_id'=>'nullable|string']);if($type==='client'&&!filled($d['client_code']??null))abort(422,'The client code field is required.');if($type==='vendor'&&!filled($d['vendor_code']??null))abort(422,'The vendor code field is required.');$code=$type==='client'?$d['client_code']??null:$d['vendor_code']??null;if(DB::table($this->profileTable($type))->where('tenant_id',$this->tid())->where($type==='client'?'client_code':'vendor_code',$code)->exists())return $this->businessError('Code already exists.','DUPLICATE_PARTY_CODE');$p=Party::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'party_type'=>$type,'display_name'=>$d['display_name'],'legal_name'=>$d['legal_name']??null,'email'=>$d['email']??null,'phone'=>$d['phone']??null,'website'=>$d['website']??null,'owner_user_id'=>auth()->id(),'created_by'=>auth()->id()]);$profile=['tenant_id'=>$this->tid(),'party_id'=>$p->id,($type==='client'?'client_code':'vendor_code')=>$code];if($type==='client')$profile['client_type']=$d['client_type']??null;else$profile['vendor_category_id']=isset($d['vendor_category_id'])?DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('uuid',$d['vendor_category_id'])->value('id'):null;DB::table($this->profileTable($type))->insert($profile+['created_at'=>now(),'updated_at'=>now()]);return $this->success([$type=>$this->pPayload($p,$type)],ucfirst($type).' created.',201);}
 public function showParty(string $type,string $uuid){return $this->success([$type=>$this->pPayload($this->party($type,$uuid),$type)]);}
 public function updateParty(Request $r,string $type,string $uuid){$r->merge(array_merge((array)$r->input('party',[]),(array)$r->input('profile',[]),$r->except(['party','profile'])));$p=$this->party($type,$uuid);$d=$r->except(['uuid','tenant_id','party_type','id','client_code','vendor_code','client_type','vendor_category_id','contacts','addresses']);$p->fill($d)->save();$fields=$type==='client'?['client_code','client_type']:['vendor_code','vendor_category_id'];$pd=$r->only($fields);if(isset($pd['vendor_category_id']))$pd['vendor_category_id']=DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('uuid',$pd['vendor_category_id'])->value('id');if($pd)DB::table($this->profileTable($type))->where('tenant_id',$this->tid())->where('party_id',$p->id)->update($pd);return $this->showParty($type,$uuid);}
 public function deleteParty(string $type,string $uuid){$this->party($type,$uuid)->delete();return $this->success(null,ucfirst($type).' archived.');}public function restoreParty(string $type,string $uuid){$p=Party::withTrashed()->where('tenant_id',$this->tid())->where('party_type',$type)->where('uuid',$uuid)->firstOrFail();$p->restore();return $this->showParty($type,$uuid);}
 private function child(Request $r,string $type,string $uuid,string $kind,?string $childUuid=null){$p=$this->party($type,$uuid);$table=$kind==='contacts'?'party_contacts':'party_addresses';$q=DB::table($table)->where('tenant_id',$this->tid())->where('party_id',$p->id);if($childUuid)$q->where($kind==='contacts'?'uuid':'id',$childUuid);if($r->isMethod('get'))return $this->success([$kind=>$q->whereNull('deleted_at')->get()]);$d=$r->except(['id','uuid','tenant_id','party_id','deleted_at']);if($childUuid){$q->update($d);return $this->success([$kind=>[$q->first()]],'Updated.');}$d=array_merge($d,['tenant_id'=>$this->tid(),'party_id'=>$p->id]);if($kind==='contacts')$d['uuid']=(string)Str::uuid();$id=$kind==='contacts'?DB::table($table)->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]):DB::table($table)->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);return $this->success([$kind=>DB::table($table)->find($id)],'Created.',201);}
 public function contacts(Request $r,string $type,string $uuid){return $this->child($r,$type,$uuid,'contacts');}public function contact(Request $r,string $type,string $uuid,string $cid){return $this->child($r,$type,$uuid,'contacts',$cid);}public function addresses(Request $r,string $type,string $uuid){return $this->child($r,$type,$uuid,'addresses');}public function address(Request $r,string $type,string $uuid,int $id){return $this->child($r,$type,$uuid,'addresses',(string)$id);}
 public function related(string $type,string $uuid,string $resource){$p=$this->party($type,$uuid);$allowed=['client'=>['projects','invoices','payments','renewals','issues'],'vendor'=>['expenses','renewals']];abort_unless(in_array($resource,$allowed[$type],true),404);$rows=$resource==='renewals'?Renewal::where('tenant_id',$this->tid())->where('party_id',$p->id)->with(['party','owner'])->get()->map(fn($r)=>$this->rPayload($r)):DB::table($resource)->where('tenant_id',$this->tid())->where($type==='client'?'client_party_id':'vendor_party_id',$p->id)->get();return $this->success([$resource=>$rows]);}
 public function activity(string $type,string $uuid){$p=$this->party($type,$uuid);return $this->success(['activity'=>DB::table('activity_logs')->where('tenant_id',$this->tid())->where('subject_id',$p->id)->where('subject_type',Party::class)->latest()->limit(50)->get()]);}
 private function renewal(string $uuid):Renewal{return Renewal::where('tenant_id',$this->tid())->where('uuid',$uuid)->firstOrFail();}private function rPayload(Renewal $r):array{$r->load(['party','owner']);$d=$r->toArray();$d['party']=$r->party?->only(['uuid','display_name','party_type','email']);$d['owner']=$r->owner?->only(['uuid','display_name','email']);$d['items']=DB::table('renewal_items')->where('tenant_id',$this->tid())->where('renewal_id',$r->id)->get();$d['reminders']=DB::table('renewal_reminders')->where('tenant_id',$this->tid())->where('renewal_id',$r->id)->get();$d['amc']=DB::table('amc_services')->where('tenant_id',$this->tid())->where('renewal_id',$r->id)->first();if($d['amc'])$d['amc']->visits=DB::table('amc_visits')->where('tenant_id',$this->tid())->where('amc_service_id',$d['amc']->id)->orderBy('visit_number')->get();return $d;}
 public function renewalDashboard(Request $r){$rows=Renewal::where('tenant_id',$this->tid())->with(['party','owner'])->latest()->get();return $this->success(['dashboard'=>['total'=>$rows->count(),'active'=>$rows->where('status_id',1)->count(),'upcoming'=>$rows->take(10)->map(fn($x)=>$this->rPayload($x))->values()]]);} public function renewalCalendar(Request $r){$rows=Renewal::where('tenant_id',$this->tid())->with(['party','owner'])->whereNotNull('renewal_date')->orderBy('renewal_date')->get();return $this->success(['renewals'=>$rows->map(fn($x)=>$this->rPayload($x))]);} public function clientRenewals(Request $r){$r->merge(['renewal_type'=>'client_service']);return $this->renewals($r);} public function vendorRenewals(Request $r){$r->merge(['renewal_type'=>'vendor_service']);return $this->renewals($r);} public function renewals(Request $r){$q=Renewal::where('tenant_id',$this->tid())->with(['party','owner']);if($r->filled('renewal_type'))$q->where('renewal_type',$r->renewal_type);if($r->filled('status'))$q->where('status_id',DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('uuid',$r->status)->value('id'));if($r->filled('search'))$q->where(fn($x)=>$x->where('title','like','%'.$r->search.'%')->orWhere('renewal_number','like','%'.$r->search.'%'));$p=$q->latest()->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->map(fn($x)=>$this->rPayload($x))->all(),$p,'Renewals fetched.');}
 public function renewalShow(string $uuid){return $this->success(['renewal'=>$this->rPayload($this->renewal($uuid))]);}
 public function renewalStore(Request $r){$d=$r->validate(['renewal_number'=>'required|string|max:80','party_id'=>'nullable|string','renewal_type'=>'required|in:client_service,vendor_service','title'=>'required|string','description'=>'nullable|string','start_date'=>'nullable|date','end_date'=>'nullable|date','renewal_date'=>'required|date','amount'=>'sometimes|numeric','currency'=>'sometimes|string|max:3','reminder_days_before'=>'sometimes|integer|min:0','auto_renew'=>'sometimes|boolean','owner_user_id'=>'nullable|string']);foreach(['party_id'=>'parties','owner_user_id'=>'users'] as $f=>$t)if(isset($d[$f])){ $resolved=DB::table($t)->where('tenant_id',$this->tid())->where('uuid',$d[$f])->value('id');if(!$resolved)abort(422,'Invalid relationship for current tenant.');$d[$f]=$resolved; }$r0=Renewal::create($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'created_by'=>auth()->id()]);return $this->success(['renewal'=>$this->rPayload($r0)],'Renewal created.',201);}
 public function renewalUpdate(Request $r,string $uuid){$x=$this->renewal($uuid);$d=$r->except(['uuid','tenant_id','id','party_id','owner_user_id']);$x->fill($d)->save();return $this->renewalShow($uuid);}public function renewalDelete(string $uuid){$this->renewal($uuid)->delete();return $this->success(null,'Renewal archived.');}
 public function renew(Request $r,string $uuid){$x=$this->renewal($uuid);$d=$r->validate(['new_end_date'=>'required|date','remarks'=>'nullable|string']);DB::table('renewal_history')->insert(['tenant_id'=>$this->tid(),'renewal_id'=>$x->id,'old_end_date'=>$x->end_date,'new_end_date'=>$d['new_end_date'],'remarks'=>$d['remarks']??null,'created_by'=>auth()->id(),'created_at'=>now()]);$x->update(['end_date'=>$d['new_end_date'],'renewal_date'=>$d['new_end_date']]);return $this->renewalShow($uuid);}public function cancel(string $uuid){$x=$this->renewal($uuid);$x->update(['auto_renew'=>false]);return $this->renewalShow($uuid);}public function sendReminder(string $uuid){$this->renewal($uuid);return $this->success(['status'=>'queued'],'Reminder queued.',202);}
 public function renewalChild(Request $r,string $uuid,string $kind,?int $id=null){abort_unless(in_array($kind,['items','reminders'],true),404);$x=$this->renewal($uuid);$table=$kind==='items'?'renewal_items':'renewal_reminders';$q=DB::table($table)->where('tenant_id',$this->tid())->where('renewal_id',$x->id);if($r->isMethod('get'))return $this->success([$kind=>$q->get()]);if($r->isMethod('delete')){$q->where('id',$id)->delete();return $this->success(null,'Deleted.');}$d=$r->except(['id','tenant_id','renewal_id']);if($id){$q->where('id',$id)->update($d);return $this->success([$kind=>$q->where('id',$id)->first()]);}$id=DB::table($table)->insertGetId($d+['tenant_id'=>$this->tid(),'renewal_id'=>$x->id]);return $this->success([$kind=>DB::table($table)->find($id)],'Created.',201);}
 public function history(string $uuid){$x=$this->renewal($uuid);return $this->success(['history'=>DB::table('renewal_history')->where('tenant_id',$this->tid())->where('renewal_id',$x->id)->latest()->get()]);}
 public function amc(Request $r,string $uuid){$x=$this->renewal($uuid);$a=DB::table('amc_services')->where('tenant_id',$this->tid())->where('renewal_id',$x->id)->first();if($r->isMethod('get')){if(!$a)return $this->success(['amc'=>null]);$amc=(array)$a;$amc['visits']=DB::table('amc_visits')->where('tenant_id',$this->tid())->where('amc_service_id',$a->id)->orderBy('visit_number')->get();return $this->success(['amc'=>$amc]);}$d=$r->validate(['total_visits'=>'required|integer|min:1','amc_start_date'=>'required|date','amc_end_date'=>'required|date|after_or_equal:amc_start_date']);$completedMax=$a?(int)DB::table('amc_visits')->where('tenant_id',$this->tid())->where('amc_service_id',$a->id)->where('status','completed')->max('visit_number'):0;if((int)$d['total_visits']<$completedMax)abort(422,'Total visits cannot be lower than completed visit numbers.');if($a)DB::table('amc_services')->where('id',$a->id)->update($d);else{$id=DB::table('amc_services')->insertGetId($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'renewal_id'=>$x->id,'created_at'=>now(),'updated_at'=>now()]);$a=DB::table('amc_services')->find($id);} $a=DB::table('amc_services')->where('id',$a->id)->first();DB::table('amc_visits')->where('tenant_id',$this->tid())->where('amc_service_id',$a->id)->where('status','pending')->delete();$start=Carbon::parse($a->amc_start_date);$end=Carbon::parse($a->amc_end_date);for($n=1;$n<=$a->total_visits;$n++){ $date=$a->total_visits===1?$end:$start->copy()->addDays((int)round($start->diffInDays($end)*($n-1)/($a->total_visits-1)));DB::table('amc_visits')->insert(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'amc_service_id'=>$a->id,'visit_number'=>$n,'visit_date'=>$date->toDateString(),'status'=>'pending','created_at'=>now(),'updated_at'=>now()]);}return $this->amc(Request::create($r->getPathInfo(),'GET'),$uuid);}
 public function amcVisits(string $uuid){$x=$this->renewal($uuid);$a=DB::table('amc_services')->where('tenant_id',$this->tid())->where('renewal_id',$x->id)->firstOrFail();return $this->success(['visits'=>DB::table('amc_visits')->where('tenant_id',$this->tid())->where('amc_service_id',$a->id)->orderBy('visit_number')->get()]);}
 public function amcVisit(Request $r,string $uuid,int $id){$x=$this->renewal($uuid);$a=DB::table('amc_services')->where('tenant_id',$this->tid())->where('renewal_id',$x->id)->firstOrFail();$v=DB::table('amc_visits')->where('tenant_id',$this->tid())->where('amc_service_id',$a->id)->where('id',$id)->firstOrFail();$d=$r->validate(['status'=>'sometimes|in:pending,completed','details'=>'nullable|string','visit_date'=>'sometimes|date']);if(($d['status']??$v->status)==='completed')$d['completed_at']=now();if(($d['status']??$v->status)==='pending')$d['completed_at']=null;DB::table('amc_visits')->where('id',$id)->update($d);return $this->success(['visit'=>DB::table('amc_visits')->find($id)]);}
 public function createClient(Request $r){return $this->createParty($r,'client');} public function createVendor(Request $r){return $this->createParty($r,'vendor');}
 public function showClient(string $u){return $this->showParty('client',$u);} public function showVendor(string $u){return $this->showParty('vendor',$u);}
 public function updateClient(Request $r,string $u){return $this->updateParty($r,'client',$u);} public function updateVendor(Request $r,string $u){return $this->updateParty($r,'vendor',$u);}
 public function deleteClient(string $u){return $this->deleteParty('client',$u);} public function deleteVendor(string $u){return $this->deleteParty('vendor',$u);}
 public function restoreClient(string $u){return $this->restoreParty('client',$u);}
 public function clientContacts(Request $r,string $u){return $this->child($r,'client',$u,'contacts');} public function vendorContacts(Request $r,string $u){return $this->child($r,'vendor',$u,'contacts');}
 public function createClientContact(Request $r,string $u){return $this->child($r,'client',$u,'contacts');} public function createVendorContact(Request $r,string $u){return $this->child($r,'vendor',$u,'contacts');}
 public function updateClientContact(Request $r,string $u,string $c){return $this->child($r,'client',$u,'contacts',$c);} public function updateVendorContact(Request $r,string $u,string $c){return $this->child($r,'vendor',$u,'contacts',$c);}
 public function deleteClientContact(Request $r,string $u,string $c){$p=$this->party('client',$u);DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('uuid',$c)->update(['deleted_at'=>now()]);return $this->success(null,'Contact archived.');} public function deleteVendorContact(Request $r,string $u,string $c){$p=$this->party('vendor',$u);DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('uuid',$c)->update(['deleted_at'=>now()]);return $this->success(null,'Contact archived.');}
 public function clientAddresses(Request $r,string $u){return $this->child($r,'client',$u,'addresses');} public function vendorAddresses(Request $r,string $u){return $this->child($r,'vendor',$u,'addresses');}
 public function createClientAddress(Request $r,string $u){return $this->child($r,'client',$u,'addresses');} public function createVendorAddress(Request $r,string $u){return $this->child($r,'vendor',$u,'addresses');}
 public function updateClientAddress(Request $r,string $u,int $id){$p=$this->party('client',$u);DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('id',$id)->update($r->except(['id','tenant_id','party_id']));return $this->clientAddresses($r,$u);} public function updateVendorAddress(Request $r,string $u,int $id){$p=$this->party('vendor',$u);DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('id',$id)->update($r->except(['id','tenant_id','party_id']));return $this->vendorAddresses($r,$u);}
 public function deleteClientAddress(Request $r,string $u,int $id){$p=$this->party('client',$u);DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('id',$id)->delete();return $this->success(null,'Address deleted.');} public function deleteVendorAddress(Request $r,string $u,int $id){$p=$this->party('vendor',$u);DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('id',$id)->delete();return $this->success(null,'Address deleted.');}
 public function clientRelated(string $u,string $resource){return $this->related('client',$u,$resource);} public function vendorRelated(string $u,string $resource){return $this->related('vendor',$u,$resource);} public function clientActivity(string $u){return $this->activity('client',$u);} public function vendorActivity(string $u){return $this->activity('vendor',$u);}
 public function vendorBankAccounts(Request $r,string $u){$p=$this->party('vendor',$u);$rows=DB::table('bank_accounts')->where('tenant_id',$this->tid())->where('owner_type',Party::class)->where('owner_id',$p->id)->get()->map(fn($x)=>collect((array)$x)->except('account_number_encrypted','routing_number_encrypted')->put('account_number','****')->all());return $this->success(['bank_accounts'=>$rows]);}
 public function createVendorBankAccount(Request $r,string $u){$p=$this->party('vendor',$u);$d=$r->validate(['bank_name'=>'required|string','account_number'=>'required|string','routing_number'=>'nullable|string','ifsc_code'=>'nullable|string','is_primary'=>'sometimes|boolean']);$d['account_number_encrypted']=encrypt($d['account_number']);unset($d['account_number']);if(isset($d['routing_number'])){$d['routing_number_encrypted']=encrypt($d['routing_number']);unset($d['routing_number']);}$id=DB::table('bank_accounts')->insertGetId($d+['tenant_id'=>$this->tid(),'owner_type'=>Party::class,'owner_id'=>$p->id,'created_at'=>now(),'updated_at'=>now()]);return $this->success(['bank_account'=>DB::table('bank_accounts')->find($id)],'Bank account created.',201);}
 public function updateVendorBankAccount(Request $r,string $u,int $id){$p=$this->party('vendor',$u);$d=$r->except(['id','tenant_id','owner_type','owner_id','account_number','routing_number']);if($r->filled('account_number'))$d['account_number_encrypted']=encrypt($r->input('account_number'));if($r->filled('routing_number'))$d['routing_number_encrypted']=encrypt($r->input('routing_number'));DB::table('bank_accounts')->where('tenant_id',$this->tid())->where('owner_type',Party::class)->where('owner_id',$p->id)->where('id',$id)->update($d);return $this->vendorBankAccounts($r,$u);}
 public function deleteVendorBankAccount(Request $r,string $u,int $id){$p=$this->party('vendor',$u);DB::table('bank_accounts')->where('tenant_id',$this->tid())->where('owner_type',Party::class)->where('owner_id',$p->id)->where('id',$id)->delete();return $this->success(null,'Bank account deleted.');}
 public function import(){return $this->success(['status'=>'queued','job_id'=>(string)Str::uuid()],'Import queued.',202);} public function export(){return $this->success(['status'=>'queued','job_id'=>(string)Str::uuid()],'Export queued.',202);} public function merge(Request $r){$d=$r->validate(['primary_client_id'=>'required|string','duplicate_client_ids'=>'required|array|min:1','reason'=>'required|string']);$primary=$this->party('client',$d['primary_client_id']);foreach($d['duplicate_client_ids'] as $id){$dup=$this->party('client',$id);DB::table('renewals')->where('tenant_id',$this->tid())->where('party_id',$dup->id)->update(['party_id'=>$primary->id]);DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$dup->id)->update(['party_id'=>$primary->id]);$dup->delete();}return $this->showParty('client',$primary->uuid);}
}
