<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Shared\BaseApiController;
use App\Models\Party;
use App\Models\LeadProfile;
use App\Models\LeadActivity;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class TenantLeadController extends BaseApiController
{
 private function tid():int{return (int)request()->attributes->get('tenant_id');}
 private function party(string $uuid):Party{return Party::where('parties.tenant_id',$this->tid())->where('parties.party_type','lead')->where('uuid',$uuid)->firstOrFail();}
 private function profile(Party $p):LeadProfile{return LeadProfile::where('tenant_id',$this->tid())->where('party_id',$p->id)->firstOrFail();}
 private function rid(string $table,$uuid):?int{return $uuid?DB::table($table)->where('tenant_id',$this->tid())->where('uuid',$uuid)->value('id'):null;}
 private function payload(Party $p):array{$l=$this->profile($p);$d=$p->toArray();$d['party']=$p->only(['uuid','display_name','email','phone','website']);$d['profile']=$l->toArray();foreach((array)$l->toArray() as $k=>$v)if(!array_key_exists($k,$d))$d[$k]=$v;$d['stage']=$l->stage_id?DB::table('tenant_lookups')->where('id',$l->stage_id)->first(['uuid','code','name']):null;$d['priority']=$l->priority_id?DB::table('tenant_lookups')->where('id',$l->priority_id)->first(['uuid','code','name']):null;$d['contacts']=DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$p->id)->whereNull('deleted_at')->get();$d['addresses']=DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id)->get();$d['activities']=LeadActivity::where('tenant_id',$this->tid())->where('lead_profile_id',$l->id)->orderBy('scheduled_at')->get();$d['conversion_history']=DB::table('lead_conversion_history')->where('tenant_id',$this->tid())->where('lead_profile_id',$l->id)->latest('converted_at')->get();$d['converted_client']=$l->converted_client_party_id?DB::table('parties')->where('tenant_id',$this->tid())->where('id',$l->converted_client_party_id)->first(['uuid','display_name','email']):null;return $d;}
 private function page($q,Request $r,$map,string $msg){$p=$q->paginate((int)$r->integer('per_page',25));return $this->list($p->getCollection()->map($map)->all(),$p,$msg);}
 public function leads(Request $r){$q=Party::where('parties.tenant_id',$this->tid())->where('parties.party_type','lead')->withTrashed(false)->join('lead_profiles','lead_profiles.party_id','=','parties.id')->select('parties.*');if($r->filled('search'))$q->where(fn($x)=>$x->where('parties.display_name','like','%'.$r->search.'%')->orWhere('lead_profiles.lead_number','like','%'.$r->search.'%'));if($r->filled('filter.stage_id'))if($id=$this->rid('tenant_lookups',$r->input('filter.stage_id')))$q->where('lead_profiles.stage_id',$id);if($r->filled('filter.priority_id'))if($id=$this->rid('tenant_lookups',$r->input('filter.priority_id')))$q->where('lead_profiles.priority_id',$id);return $this->page($q->orderBy('parties.display_name'),$r,fn($x)=>$this->payload(Party::find($x->id)),'Leads fetched.');}
 public function dashboard(){ $q=Party::where('parties.tenant_id',$this->tid())->where('parties.party_type','lead')->withTrashed(false)->join('lead_profiles','lead_profiles.party_id','=','parties.id');$rows=$q->get(['parties.*','lead_profiles.expected_value','lead_profiles.probability','lead_profiles.expected_close_date']);return $this->success(['dashboard'=>['new_this_month'=>$rows->filter(fn($x)=>$x->created_at&&$x->created_at->isSameMonth(now()))->count(),'open'=>$rows->whereNull('converted_at')->whereNull('lost_reason')->count(),'converted'=>$rows->whereNotNull('converted_at')->count(),'lost'=>$rows->whereNotNull('lost_reason')->count(),'expected_pipeline'=>$rows->whereNull('converted_at')->whereNull('lost_reason')->sum('expected_value'),'weighted_pipeline'=>$rows->whereNull('converted_at')->whereNull('lost_reason')->sum(fn($x)=>(float)$x->expected_value*((int)$x->probability/100)),'upcoming_followups'=>LeadActivity::where('tenant_id',$this->tid())->whereNotNull('scheduled_at')->where('scheduled_at','>=',now())->orderBy('scheduled_at')->limit(10)->get()]]);}
 public function kanban(){ $rows=Party::where('parties.tenant_id',$this->tid())->where('parties.party_type','lead')->withTrashed(false)->join('lead_profiles','lead_profiles.party_id','=','parties.id')->get(['parties.*','lead_profiles.stage_id','lead_profiles.expected_value']);return $this->success(['view'=>'kanban','columns'=>$rows->groupBy('stage_id')->map(fn($x)=>['total'=>$x->count(),'value'=>$x->sum('expected_value'),'leads'=>$x->map(fn($p)=>$this->payload(Party::find($p->id)))->values()])]);}
 public function formOptions(){return $this->success(['stages'=>DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('group','lead_stage')->get(),'priorities'=>DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('group','lead_priority')->get(),'sources'=>DB::table('tenant_lookups')->where('tenant_id',$this->tid())->where('group','lead_source')->get(),'users'=>DB::table('users')->where('tenant_id',$this->tid())->get(['uuid','display_name','email']),'teams'=>DB::table('teams')->where('tenant_id',$this->tid())->get(['uuid','name']),'activity_types'=>['call','email','meeting','demo','follow_up','note']]);}
 public function store(Request $r){$d=$r->validate(['party.display_name'=>'required|string|max:200','party.email'=>'nullable|email','party.phone'=>'nullable|string|max:40','profile.lead_number'=>'required|string|max:80','profile.source_id'=>'nullable|string','profile.stage_id'=>'nullable|string','profile.priority_id'=>'nullable|string','profile.expected_value'=>'sometimes|numeric','profile.probability'=>'sometimes|integer|min:0|max:100','profile.expected_close_date'=>'nullable|date']);$party=$d['party'];$profile=$d['profile'];foreach(['source_id','stage_id','priority_id'] as $f)if(isset($profile[$f])){if(!$profile[$f]=$this->rid('tenant_lookups',$profile[$f]))abort(422,'Invalid lead relationship UUID.');}$p=Party::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'party_type'=>'lead','display_name'=>$party['display_name'],'email'=>$party['email']??null,'phone'=>$party['phone']??null,'owner_user_id'=>auth()->id(),'created_by'=>auth()->id()]);LeadProfile::create($profile+['tenant_id'=>$this->tid(),'party_id'=>$p->id]);return $this->success(['lead'=>$this->payload($p)],'Lead created.',201);}
 public function show(string $uuid){return $this->success(['lead'=>$this->payload($this->party($uuid))]);}
 public function update(Request $r,string $uuid){$p=$this->party($uuid);$l=$this->profile($p);$party=$r->input('party',[]);$profile=$r->input('profile',[]);$party=array_diff_key($party,array_flip(['id','uuid','tenant_id','party_type']));if(array_key_exists('owner_user_id',$party)){if(!$party['owner_user_id']=$this->rid('users',$party['owner_user_id']))abort(422,'Invalid owner UUID.');}$p->fill($party)->save();foreach(['source_id','stage_id','priority_id'] as $f)if(array_key_exists($f,$profile)){if(!$profile[$f]=$this->rid('tenant_lookups',$profile[$f]))abort(422,'Invalid lead relationship UUID.');}$old=$l->stage_id;$l->fill(array_diff_key($profile,array_flip(['id','tenant_id','party_id'])))->save();if(array_key_exists('stage_id',$profile)&&$old!==$l->stage_id)DB::table('lead_conversion_history')->whereRaw('1=0');return $this->show($uuid);}
 public function delete(string $uuid){$this->party($uuid)->delete();return $this->success(null,'Lead archived.');}
 public function duplicate(Request $r,string $uuid){$p=$this->party($uuid);$l=$this->profile($p);$number=$r->input('lead_number',$l->lead_number.'-COPY-'.strtoupper(Str::random(5)));$copy=Party::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'party_type'=>'lead','display_name'=>$p->display_name,'email'=>$p->email,'phone'=>$p->phone,'owner_user_id'=>auth()->id(),'created_by'=>auth()->id()]);$x=$l->replicate(['id','party_id','lead_number','converted_client_party_id','converted_at','lost_reason']);$x->tenant_id=$this->tid();$x->party_id=$copy->id;$x->lead_number=$number;$x->save();foreach(['party_contacts','party_addresses'] as $table){foreach(DB::table($table)->where('tenant_id',$this->tid())->where('party_id',$p->id)->whereNull('deleted_at')->get() as $row){$a=(array)$row;unset($a['id']);$a['party_id']=$copy->id;$a['created_at']=now();$a['updated_at']=now();DB::table($table)->insert($a);}}return $this->success(['lead'=>$this->payload($copy)],'Lead duplicated.',201);}
 public function lost(Request $r,string $uuid){$p=$this->party($uuid);$l=$this->profile($p);$d=$r->validate(['lost_reason'=>'required|string|max:255']);$l->update($d);return $this->show($uuid);}
 public function convert(Request $r,string $uuid){
    $p=$this->party($uuid);
    $l=$this->profile($p);
    if($l->converted_at) abort(409,'Lead is already converted.');
    $d=$r->validate(['client_id'=>['nullable','uuid'],'client_code'=>['prohibited'],'client_type'=>['nullable','string','max:80'],'account_manager_id'=>['nullable','uuid'],'conversion_note'=>['nullable','string']]);
    $tenantId=$this->tid();
    DB::transaction(function() use($p,$l,$d,$tenantId){
        if(!empty($d['client_id'])){
            $clientId=DB::table('parties')->where('tenant_id',$tenantId)->where('party_type','client')->where('uuid',$d['client_id'])->value('id');
            if(!$clientId) throw \Illuminate\Validation\ValidationException::withMessages(['client_id'=>'The selected client is invalid.']);
        }else{
            DB::table('tenants')->where('id',$tenantId)->lockForUpdate()->first();
            $next=DB::table('client_profiles')->where('tenant_id',$tenantId)->where('client_code','like','CL-%')->pluck('client_code')
                ->reduce(fn(int $max,string $code): int => preg_match('/^CL-(\d+)$/',$code,$matches) ? max($max,(int)$matches[1]) : $max,0)+1;
            $clientId=Party::create(['uuid'=>(string)Str::uuid(),'tenant_id'=>$tenantId,'party_type'=>'client','display_name'=>$p->display_name,'email'=>$p->email,'phone'=>$p->phone,'owner_user_id'=>auth()->id(),'created_by'=>auth()->id()])->id;
            $managerId=!empty($d['account_manager_id'])?$this->rid('users',$d['account_manager_id']):null;
            DB::table('client_profiles')->insert(['tenant_id'=>$tenantId,'party_id'=>$clientId,'client_code'=>sprintf('CL-%06d',$next),'client_type'=>$d['client_type']??'company','account_manager_id'=>$managerId,'created_at'=>now(),'updated_at'=>now()]);
        }
        DB::table('lead_profiles')->where('id',$l->id)->update(['converted_client_party_id'=>$clientId,'converted_at'=>now()]);
        DB::table('lead_conversion_history')->insert(['tenant_id'=>$tenantId,'lead_profile_id'=>$l->id,'client_party_id'=>$clientId,'converted_by'=>auth()->id(),'conversion_note'=>$d['conversion_note']??null,'converted_at'=>now()]);
    });
    return $this->show($uuid);
 }
 public function merge(Request $r){$d=$r->validate(['primary_lead_id'=>'required|string','duplicate_lead_ids'=>'required|array|min:1','reason'=>'required|string']);$primary=$this->party($d['primary_lead_id']);foreach($d['duplicate_lead_ids'] as $uuid){$dup=$this->party($uuid);$dl=$this->profile($dup);$pl=$this->profile($primary);DB::table('lead_activities')->where('tenant_id',$this->tid())->where('lead_profile_id',$dl->id)->update(['lead_profile_id'=>$pl->id]);DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$dup->id)->update(['party_id'=>$primary->id]);DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$dup->id)->update(['party_id'=>$primary->id]);$dup->delete();}return $this->show($primary->uuid);}
 public function activities(Request $r,string $uuid){$l=$this->profile($this->party($uuid));if($r->isMethod('get'))return $this->success(['activities'=>LeadActivity::where('tenant_id',$this->tid())->where('lead_profile_id',$l->id)->orderBy('scheduled_at')->get()]);$d=$r->validate(['activity_type'=>'required|string','subject'=>'required|string','description'=>'nullable|string','scheduled_at'=>'nullable|date','assigned_to'=>'nullable|string','outcome'=>'nullable|string']);if(isset($d['assigned_to'])){if(!$d['assigned_to']=$this->rid('users',$d['assigned_to']))abort(422,'Invalid assigned user UUID.');}$a=LeadActivity::create($d+['uuid'=>(string)Str::uuid(),'tenant_id'=>$this->tid(),'lead_profile_id'=>$l->id,'created_by'=>auth()->id()]);return $this->success(['activity'=>$a],'Activity created.',201);}
 public function activityUpdate(Request $r,string $uuid,string $activity){$l=$this->profile($this->party($uuid));$a=LeadActivity::where('tenant_id',$this->tid())->where('lead_profile_id',$l->id)->where('uuid',$activity)->firstOrFail();$a->update($r->except(['id','uuid','tenant_id','lead_profile_id','created_by']));return $this->success(['activity'=>$a]);}
 public function contacts(Request $r,string $uuid){$p=$this->party($uuid);$q=DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$p->id);if($r->isMethod('get'))return $this->success(['contacts'=>$q->whereNull('deleted_at')->get()]);$d=$r->except(['id','uuid','tenant_id','party_id','deleted_at']);$d['tenant_id']=$this->tid();$d['party_id']=$p->id;$d['uuid']=(string)Str::uuid();$id=DB::table('party_contacts')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);return $this->success(['contact'=>DB::table('party_contacts')->where('id',$id)->first()],'Contact created.',201);}
 public function addresses(Request $r,string $uuid){$p=$this->party($uuid);$q=DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id);if($r->isMethod('get'))return $this->success(['addresses'=>$q->get()]);$d=$r->except(['id','tenant_id','party_id']);$id=DB::table('party_addresses')->insertGetId($d+['tenant_id'=>$this->tid(),'party_id'=>$p->id,'created_at'=>now(),'updated_at'=>now()]);return $this->success(['address'=>DB::table('party_addresses')->where('id',$id)->first()],'Address created.',201);}
 public function contactChild(Request $r,string $uuid,string $id){$p=$this->party($uuid);$q=DB::table('party_contacts')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('uuid',$id);if($r->isMethod('delete')){$q->update(['deleted_at'=>now()]);return $this->success(null,'Contact archived.');}$q->update($r->except(['id','uuid','tenant_id','party_id','deleted_at']));return $this->success(['contact'=>$q->first()]);}
 public function addressChild(Request $r,string $uuid,int $id){$p=$this->party($uuid);$q=DB::table('party_addresses')->where('tenant_id',$this->tid())->where('party_id',$p->id)->where('id',$id);if($r->isMethod('delete')){$q->delete();return $this->success(null,'Address deleted.');}$q->update($r->except(['id','tenant_id','party_id']));return $this->success(['address'=>$q->first()]);}
 public function activityLog(string $uuid){$p=$this->party($uuid);return $this->success(['activity'=>DB::table('activity_logs')->where('tenant_id',$this->tid())->where('subject_id',$p->id)->latest()->limit(50)->get()]);}
 public function import(){return $this->success(['status'=>'queued','job_id'=>(string)Str::uuid()],'Import queued.',202);}
 public function export(){return $this->success(['status'=>'queued','job_id'=>(string)Str::uuid()],'Export queued.',202);}
}
